In [1]:
# import required library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# import api key related library
import os
from dotenv import load_dotenv
import requests
import json

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
	"x-rapidapi-key": "7cd1451496msh26d2809dcb7535ap12515bjsn5b15e7be8226",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
response = requests.get(url, headers=headers)
data = response.json()
print(data.keys())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matches': [{'matchInfo': {'matchId': 130019, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '2nd Match, Group A', 'matchFormat': 'T20', 'startDate': '1757514600000', 'endDate': '1757527200000', 'state': 'In Progress', 'status': 'India opt to bowl', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 719031}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'currBatTeamId': 7, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 54, 'wickets': 8, 'overs': 12.3}}}}]}}]}, {'matchType': 'Domestic', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matches': [{'matchInfo': {'matchId': 113199, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '56th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed by rain - Essex lead by 124 runs', 'team1': {'teamId': 141, 'teamName': 'Durham', 'teamSName': 'DUR', 'imageId': 172208}, 'team2': {'teamId': 152, 'teamName': 'Essex', 'teamSName': 'ESS', 'imageId': 172219}, 'venueInfo': {'id': 118, 'ground': 'County Ground', 'city': 'Chelmsford', 'timezone': '+01:00', 'latitude': '51.731580', 'longitude': '0.469004'}, 'currBatTeamId': 152, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 333, 'wickets': 10, 'overs': 100.2}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 457, 'wickets': 8, 'overs': 127.6}}}}, {'matchInfo': {'matchId': 113211, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '59th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Stumps', 'status': 'Day 3: Stumps - Sussex need 241 runs', 'team1': {'teamId': 153, 'teamName': 'Hampshire', 'teamSName': 'HAM', 'imageId': 172220}, 'team2': {'teamId': 41, 'teamName': 'Sussex', 'teamSName': 'SUS', 'imageId': 172148}, 'venueInfo': {'id': 292, 'ground': 'County Ground', 'city': 'Hove', 'timezone': '+01:00', 'latitude': '50.830995', 'longitude': '-0.163522'}, 'currBatTeamId': 41, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Stumps'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 226, 'wickets': 10, 'overs': 71.3}, 'inngs2': {'inningsId': 3, 'runs': 173, 'wickets': 10, 'overs': 50.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 122, 'wickets': 10, 'overs': 51.4}, 'inngs2': {'inningsId': 4, 'runs': 37, 'wickets': 1, 'overs': 12.6}}}}, {'matchInfo': {'matchId': 113202, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '57th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Rain stops play - Yorkshire trail by 424 runs', 'team1': {'teamId': 119, 'teamName': 'Somerset', 'teamSName': 'SOM', 'imageId': 172199}, 'team2': {'teamId': 146, 'teamName': 'Yorkshire', 'teamSName': 'YORKS', 'imageId': 172213}, 'venueInfo': {'id': 223, 'ground': 'The Cooper Associates County Ground', 'city': 'Taunton', 'timezone': '+01:00', 'latitude': '51.018913', 'longitude': '3.100894'}, 'currBatTeamId': 146, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 441, 'wickets': 6, 'overs': 126.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 17, 'overs': 1.6}}}}, {'matchInfo': {'matchId': 113217, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '60th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'In Progress', 'status': 'Day 3: 3rd Session - Nottinghamshire need 120 runs', 'team1': {'teamId': 147, 'teamName': 'Worcestershire', 'teamSName': 'WORCS', 'imageId': 172214}, 'team2': {'teamId': 139, 'teamName': 'Nottinghamshire', 'teamSName': 'NOTTS', 'imageId': 172206}, 'venueInfo': {'id': 225, 'ground': 'New Road', 'city': 'Worcester', 'timezone': '+01:00', 'latitude': '52.189294', 'longitude': '-2.2268'}, 'currBatTeamId': 139, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 10, 'overs': 52.5}, 'inngs2': {'inningsId': 3, 'runs': 160, 'wickets': 10, 'overs': 61.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 207, 'wickets': 10, 'overs': 70.2}, 'inngs2': {'inningsId': 4, 'runs': 16, 'wickets': 1, 'overs': 7.6}}}}, {'matchInfo': {'matchId': 113208, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '58th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Rain stops play - Surrey lead by 274 runs', 'team1': {'teamId': 148, 'teamName': 'Surrey', 'teamSName': 'SUR', 'imageId': 172215}, 'team2': {'teamId': 140, 'teamName': 'Warwickshire', 'teamSName': 'WARKS', 'imageId': 172207}, 'venueInfo': {'id': 12, 'ground': 'Kennington Oval', 'city': 'London', 'timezone': '+01:00', 'latitude': '51.48368', 'longitude': '-0.114885'}, 'currBatTeamId': 148, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 246, 'wickets': 10, 'overs': 59.5}, 'inngs2': {'inningsId': 3, 'runs': 276, 'wickets': 2, 'overs': 76.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 248, 'wickets': 10, 'overs': 74.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 9557, 'seriesName': 'New Zealand A tour of South Africa, 2025', 'matches': [{'matchInfo': {'matchId': 116495, 'seriesId': 9557, 'seriesName': 'New Zealand A tour of South Africa, 2025', 'matchDesc': '1st Unofficial Test', 'matchFormat': 'TEST', 'startDate': '1757232000000', 'endDate': '1757516400000', 'state': 'Complete', 'status': 'New Zealand A won by 185 runs', 'team1': {'teamId': 80, 'teamName': 'New Zealand A', 'teamSName': 'NZA', 'imageId': 172174}, 'team2': {'teamId': 268, 'teamName': 'South Africa A', 'teamSName': 'RSAA', 'imageId': 172321}, 'venueInfo': {'id': 102, 'ground': 'Senwes Park', 'city': 'Potchefstroom', 'timezone': '+02:00', 'latitude': '-26.695565', 'longitude': '27.100691'}, 'currBatTeamId': 80, 'seriesStartDt': '1756425600000', 'seriesEndDt': '1758153600000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 607, 'wickets': 7, 'overs': 128.5}, 'inngs2': {'inningsId': 3, 'runs': 126, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 236, 'wickets': 10, 'overs': 56.1}, 'inngs2': {'inningsId': 4, 'runs': 312, 'wickets': 10, 'overs': 85.5}}}}]}}, {'seriesAdWrapper': {'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matches': [{'matchInfo': {'matchId': 113607, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '45th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain  - Gloucestershire lead by 148 runs', 'team1': {'teamId': 151, 'teamName': 'Gloucestershire', 'teamSName': 'GLOUCS', 'imageId': 172218}, 'team2': {'teamId': 145, 'teamName': 'Leicestershire', 'teamSName': 'LEIC', 'imageId': 172212}, 'venueInfo': {'id': 222, 'ground': 'Grace Road', 'city': 'Leicester', 'timezone': '+01:00', 'latitude': '52.607861', 'longitude': '-1.142709'}, 'currBatTeamId': 151, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 482, 'wickets': 10, 'overs': 120.4}, 'inngs2': {'inningsId': 3, 'runs': 8, 'overs': 3.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 342, 'wickets': 10, 'overs': 93.4}}}}, {'matchInfo': {'matchId': 113625, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '48th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Tea', 'status': 'Day 3: Tea Break - Kent lead by 179 runs', 'team1': {'teamId': 150, 'teamName': 'Kent', 'teamSName': 'KENT', 'imageId': 172217}, 'team2': {'teamId': 143, 'teamName': 'Lancashire', 'teamSName': 'LANCS', 'imageId': 172210}, 'venueInfo': {'id': 67, 'ground': 'St Lawrence Ground', 'city': 'Canterbury', 'timezone': '+01:00', 'latitude': '51.267447', 'longitude': '1.091621'}, 'currBatTeamId': 150, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Tea'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 293, 'wickets': 10, 'overs': 85.6}, 'inngs2': {'inningsId': 3, 'runs': 170, 'wickets': 3, 'overs': 51.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 284, 'wickets': 10, 'overs': 77.2}}}}, {'matchInfo': {'matchId': 113613, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '46th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain  - Derbyshire lead by 18 runs', 'team1': {'teamId': 144, 'teamName': 'Derbyshire', 'teamSName': 'DERBY', 'imageId': 172211}, 'team2': {'teamId': 74, 'teamName': 'Middlesex', 'teamSName': 'MDX', 'imageId': 172170}, 'venueInfo': {'id': 19, 'ground': "Lord's", 'city': 'London', 'timezone': '+01:00', 'latitude': '51.529488', 'longitude': '-0.172926'}, 'currBatTeamId': 144, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 283, 'wickets': 10, 'overs': 86.4}, 'inngs2': {'inningsId': 3, 'runs': 33, 'wickets': 1, 'overs': 18.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 298, 'wickets': 10, 'overs': 91.1}}}}, {'matchInfo': {'matchId': 113616, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '47th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain - Northamptonshire trail by 54 runs', 'team1': {'teamId': 149, 'teamName': 'Glamorgan', 'teamSName': 'GLAM', 'imageId': 172216}, 'team2': {'teamId': 142, 'teamName': 'Northamptonshire', 'teamSName': 'NHNTS', 'imageId': 172209}, 'venueInfo': {'id': 119, 'ground': 'County Ground', 'city': 'Northampton', 'timezone': '+01:00', 'latitude': '52.248160', 'longitude': '-0.871060'}, 'currBatTeamId': 142, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 467, 'wickets': 10, 'overs': 121.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 413, 'wickets': 9, 'overs': 92.4}}}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 4}}]}, {'matchType': 'Women', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matches': [{'matchInfo': {'matchId': 131779, 'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matchDesc': '8th Match, Group A', 'matchFormat': 'T20', 'startDate': '1757467800000', 'endDate': '1757480400000', 'state': 'Complete', 'status': 'Vanuatu Women won by 7 wkts', 'team1': {'teamId': 1754, 'teamName': 'Cook Islands Women', 'teamSName': 'CISW', 'imageId': 341074}, 'team2': {'teamId': 506, 'teamName': 'Vanuatu Women', 'teamSName': 'VANW', 'imageId': 172555}, 'venueInfo': {'id': 1438123, 'ground': 'Albert Park 2', 'city': 'Suva', 'timezone': '+12:00', 'latitude': '-18.1471997', 'longitude': '178.4200685'}, 'currBatTeamId': 506, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1757980800000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 118, 'wickets': 1, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 122, 'wickets': 3, 'overs': 15.1}}}}, {'matchInfo': {'matchId': 131774, 'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matchDesc': '7th Match, Group B', 'matchFormat': 'T20', 'startDate': '1757467800000', 'endDate': '1757480400000', 'state': 'Complete', 'status': 'Papua New Guinea Women won by 168 runs', 'team1': {'teamId': 390, 'teamName': 'Papua New Guinea Women', 'teamSName': 'PNGW', 'imageId': 172443}, 'team2': {'teamId': 1514, 'teamName': 'Philippines Women', 'teamSName': 'PHIW', 'imageId': 307469}, 'venueInfo': {'id': 1438120, 'ground': 'Albert Park 1', 'city': 'Suva', 'timezone': '+12:00', 'latitude': '-18.1472049', 'longitude': '178.4223645'}, 'currBatTeamId': 390, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1757980800000', 'isTimeAnnounced': True, 'stateTitle': 'PNGW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 224, 'wickets': 1, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 56, 'wickets': 10, 'overs': 19.4}}}}]}}]}], 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']}, 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results', 'webURL': 'www.cricbuzz.com/live-cricket-scores/'}, 'responseLastUpdated': '1757518582'}
dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [ ]:
print(data.keys())
print(data['typeMatches'])

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])
[{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matches': [{'matchInfo': {'matchId': 130019, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '2nd Match, Group A', 'matchFormat': 'T20', 'startDate': '1757514600000', 'endDate': '1757527200000', 'state': 'In Progress', 'status': 'India opt to bowl', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 719031}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'currBatTeamId': 7, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 54, 'wickets': 8, 'overs': 12.3}}}}]}}]}, {'matchType': 'Domestic', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matches': [{'matchInfo': {'matchId': 113199, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '56th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed by rain - Essex lead by 124 runs', 'team1': {'teamId': 141, 'teamName': 'Durham', 'teamSName': 'DUR', 'imageId': 172208}, 'team2': {'teamId': 152, 'teamName': 'Essex', 'teamSName': 'ESS', 'imageId': 172219}, 'venueInfo': {'id': 118, 'ground': 'County Ground', 'city': 'Chelmsford', 'timezone': '+01:00', 'latitude': '51.731580', 'longitude': '0.469004'}, 'currBatTeamId': 152, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 333, 'wickets': 10, 'overs': 100.2}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 457, 'wickets': 8, 'overs': 127.6}}}}, {'matchInfo': {'matchId': 113211, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '59th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Stumps', 'status': 'Day 3: Stumps - Sussex need 241 runs', 'team1': {'teamId': 153, 'teamName': 'Hampshire', 'teamSName': 'HAM', 'imageId': 172220}, 'team2': {'teamId': 41, 'teamName': 'Sussex', 'teamSName': 'SUS', 'imageId': 172148}, 'venueInfo': {'id': 292, 'ground': 'County Ground', 'city': 'Hove', 'timezone': '+01:00', 'latitude': '50.830995', 'longitude': '-0.163522'}, 'currBatTeamId': 41, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Stumps'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 226, 'wickets': 10, 'overs': 71.3}, 'inngs2': {'inningsId': 3, 'runs': 173, 'wickets': 10, 'overs': 50.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 122, 'wickets': 10, 'overs': 51.4}, 'inngs2': {'inningsId': 4, 'runs': 37, 'wickets': 1, 'overs': 12.6}}}}, {'matchInfo': {'matchId': 113202, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '57th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Rain stops play - Yorkshire trail by 424 runs', 'team1': {'teamId': 119, 'teamName': 'Somerset', 'teamSName': 'SOM', 'imageId': 172199}, 'team2': {'teamId': 146, 'teamName': 'Yorkshire', 'teamSName': 'YORKS', 'imageId': 172213}, 'venueInfo': {'id': 223, 'ground': 'The Cooper Associates County Ground', 'city': 'Taunton', 'timezone': '+01:00', 'latitude': '51.018913', 'longitude': '3.100894'}, 'currBatTeamId': 146, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 441, 'wickets': 6, 'overs': 126.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 17, 'overs': 1.6}}}}, {'matchInfo': {'matchId': 113217, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '60th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'In Progress', 'status': 'Day 3: 3rd Session - Nottinghamshire need 120 runs', 'team1': {'teamId': 147, 'teamName': 'Worcestershire', 'teamSName': 'WORCS', 'imageId': 172214}, 'team2': {'teamId': 139, 'teamName': 'Nottinghamshire', 'teamSName': 'NOTTS', 'imageId': 172206}, 'venueInfo': {'id': 225, 'ground': 'New Road', 'city': 'Worcester', 'timezone': '+01:00', 'latitude': '52.189294', 'longitude': '-2.2268'}, 'currBatTeamId': 139, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 10, 'overs': 52.5}, 'inngs2': {'inningsId': 3, 'runs': 160, 'wickets': 10, 'overs': 61.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 207, 'wickets': 10, 'overs': 70.2}, 'inngs2': {'inningsId': 4, 'runs': 16, 'wickets': 1, 'overs': 7.6}}}}, {'matchInfo': {'matchId': 113208, 'seriesId': 9360, 'seriesName': 'County Championship Division One 2025', 'matchDesc': '58th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Rain stops play - Surrey lead by 274 runs', 'team1': {'teamId': 148, 'teamName': 'Surrey', 'teamSName': 'SUR', 'imageId': 172215}, 'team2': {'teamId': 140, 'teamName': 'Warwickshire', 'teamSName': 'WARKS', 'imageId': 172207}, 'venueInfo': {'id': 12, 'ground': 'Kennington Oval', 'city': 'London', 'timezone': '+01:00', 'latitude': '51.48368', 'longitude': '-0.114885'}, 'currBatTeamId': 148, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 246, 'wickets': 10, 'overs': 59.5}, 'inngs2': {'inningsId': 3, 'runs': 276, 'wickets': 2, 'overs': 76.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 248, 'wickets': 10, 'overs': 74.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 9557, 'seriesName': 'New Zealand A tour of South Africa, 2025', 'matches': [{'matchInfo': {'matchId': 116495, 'seriesId': 9557, 'seriesName': 'New Zealand A tour of South Africa, 2025', 'matchDesc': '1st Unofficial Test', 'matchFormat': 'TEST', 'startDate': '1757232000000', 'endDate': '1757516400000', 'state': 'Complete', 'status': 'New Zealand A won by 185 runs', 'team1': {'teamId': 80, 'teamName': 'New Zealand A', 'teamSName': 'NZA', 'imageId': 172174}, 'team2': {'teamId': 268, 'teamName': 'South Africa A', 'teamSName': 'RSAA', 'imageId': 172321}, 'venueInfo': {'id': 102, 'ground': 'Senwes Park', 'city': 'Potchefstroom', 'timezone': '+02:00', 'latitude': '-26.695565', 'longitude': '27.100691'}, 'currBatTeamId': 80, 'seriesStartDt': '1756425600000', 'seriesEndDt': '1758153600000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 607, 'wickets': 7, 'overs': 128.5}, 'inngs2': {'inningsId': 3, 'runs': 126, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 236, 'wickets': 10, 'overs': 56.1}, 'inngs2': {'inningsId': 4, 'runs': 312, 'wickets': 10, 'overs': 85.5}}}}]}}, {'seriesAdWrapper': {'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matches': [{'matchInfo': {'matchId': 113625, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '48th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Tea', 'status': 'Day 3: Tea Break - Kent lead by 179 runs', 'team1': {'teamId': 150, 'teamName': 'Kent', 'teamSName': 'KENT', 'imageId': 172217}, 'team2': {'teamId': 143, 'teamName': 'Lancashire', 'teamSName': 'LANCS', 'imageId': 172210}, 'venueInfo': {'id': 67, 'ground': 'St Lawrence Ground', 'city': 'Canterbury', 'timezone': '+01:00', 'latitude': '51.267447', 'longitude': '1.091621'}, 'currBatTeamId': 150, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Tea'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 293, 'wickets': 10, 'overs': 85.6}, 'inngs2': {'inningsId': 3, 'runs': 170, 'wickets': 3, 'overs': 51.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 284, 'wickets': 10, 'overs': 77.2}}}}, {'matchInfo': {'matchId': 113613, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '46th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain  - Derbyshire lead by 18 runs', 'team1': {'teamId': 144, 'teamName': 'Derbyshire', 'teamSName': 'DERBY', 'imageId': 172211}, 'team2': {'teamId': 74, 'teamName': 'Middlesex', 'teamSName': 'MDX', 'imageId': 172170}, 'venueInfo': {'id': 19, 'ground': "Lord's", 'city': 'London', 'timezone': '+01:00', 'latitude': '51.529488', 'longitude': '-0.172926'}, 'currBatTeamId': 144, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 283, 'wickets': 10, 'overs': 86.4}, 'inngs2': {'inningsId': 3, 'runs': 33, 'wickets': 1, 'overs': 18.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 298, 'wickets': 10, 'overs': 91.1}}}}, {'matchInfo': {'matchId': 113616, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '47th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain - Northamptonshire trail by 54 runs', 'team1': {'teamId': 149, 'teamName': 'Glamorgan', 'teamSName': 'GLAM', 'imageId': 172216}, 'team2': {'teamId': 142, 'teamName': 'Northamptonshire', 'teamSName': 'NHNTS', 'imageId': 172209}, 'venueInfo': {'id': 119, 'ground': 'County Ground', 'city': 'Northampton', 'timezone': '+01:00', 'latitude': '52.248160', 'longitude': '-0.871060'}, 'currBatTeamId': 142, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 467, 'wickets': 10, 'overs': 121.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 413, 'wickets': 9, 'overs': 92.4}}}}, {'matchInfo': {'matchId': 113607, 'seriesId': 9369, 'seriesName': 'County Championship Division Two 2025', 'matchDesc': '45th Match', 'matchFormat': 'TEST', 'startDate': '1757323800000', 'endDate': '1757608200000', 'state': 'Rain', 'status': 'Day 3: Match delayed due to rain  - Gloucestershire lead by 148 runs', 'team1': {'teamId': 151, 'teamName': 'Gloucestershire', 'teamSName': 'GLOUCS', 'imageId': 172218}, 'team2': {'teamId': 145, 'teamName': 'Leicestershire', 'teamSName': 'LEIC', 'imageId': 172212}, 'venueInfo': {'id': 222, 'ground': 'Grace Road', 'city': 'Leicester', 'timezone': '+01:00', 'latitude': '52.607861', 'longitude': '-1.142709'}, 'currBatTeamId': 151, 'seriesStartDt': '1743638400000', 'seriesEndDt': '1759017600000', 'isTimeAnnounced': True, 'stateTitle': 'Break'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 482, 'wickets': 10, 'overs': 120.4}, 'inngs2': {'inningsId': 3, 'runs': 8, 'overs': 3.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 342, 'wickets': 10, 'overs': 93.4}}}}]}}]}, {'matchType': 'Women', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matches': [{'matchInfo': {'matchId': 131779, 'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matchDesc': '8th Match, Group A', 'matchFormat': 'T20', 'startDate': '1757467800000', 'endDate': '1757480400000', 'state': 'Complete', 'status': 'Vanuatu Women won by 7 wkts', 'team1': {'teamId': 1754, 'teamName': 'Cook Islands Women', 'teamSName': 'CISW', 'imageId': 341074}, 'team2': {'teamId': 506, 'teamName': 'Vanuatu Women', 'teamSName': 'VANW', 'imageId': 172555}, 'venueInfo': {'id': 1438123, 'ground': 'Albert Park 2', 'city': 'Suva', 'timezone': '+12:00', 'latitude': '-18.1471997', 'longitude': '178.4200685'}, 'currBatTeamId': 506, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1757980800000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 118, 'wickets': 1, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 122, 'wickets': 3, 'overs': 15.1}}}}, {'matchInfo': {'matchId': 131774, 'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025', 'matchDesc': '7th Match, Group B', 'matchFormat': 'T20', 'startDate': '1757467800000', 'endDate': '1757480400000', 'state': 'Complete', 'status': 'Papua New Guinea Women won by 168 runs', 'team1': {'teamId': 390, 'teamName': 'Papua New Guinea Women', 'teamSName': 'PNGW', 'imageId': 172443}, 'team2': {'teamId': 1514, 'teamName': 'Philippines Women', 'teamSName': 'PHIW', 'imageId': 307469}, 'venueInfo': {'id': 1438120, 'ground': 'Albert Park 1', 'city': 'Suva', 'timezone': '+12:00', 'latitude': '-18.1472049', 'longitude': '178.4223645'}, 'currBatTeamId': 390, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1757980800000', 'isTimeAnnounced': True, 'stateTitle': 'PNGW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 224, 'wickets': 1, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 56, 'wickets': 10, 'overs': 19.4}}}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 5}}]}]

In [ ]:
# Examine the structure of a single match entry
if data and data['typeMatches']:
    first_match_type = data['typeMatches'][0]
    print("\nStructure of the first match type entry:")
    print(first_match_type.keys())

    if first_match_type and first_match_type['seriesMatches']:
        first_series_match = first_match_type['seriesMatches'][0]
        print("\nStructure of the first series match entry:")
        print(first_series_match.keys())

        if first_series_match and first_series_match['seriesAdWrapper'] and first_series_match['seriesAdWrapper']['matches']:
            first_match = first_series_match['seriesAdWrapper']['matches'][0]
            print("\nStructure of the first match entry:")
            print(first_match.keys())

            if first_match and 'matchInfo' in first_match:
                print("\nStructure of the matchInfo:")
                print(first_match['matchInfo'].keys())

            if first_match and 'matchScore' in first_match:
                print("\nStructure of the matchScore:")
                print(first_match['matchScore'].keys())
            else:
                print("\n'matchScore' not found for the first match entry.")


# Outline the path to access the list of matches and key details
print("\nPath to access the list of matches: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches']")
print("Path to access match info: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchInfo']")
print("Path to access match score: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchScore'] (Note: 'matchScore' may not be present for all matches)")

Structure of the first match type entry:
dict_keys(['matchType', 'seriesMatches'])

Structure of the first series match entry:
dict_keys(['seriesAdWrapper'])

Structure of the first match entry:
dict_keys(['matchInfo', 'matchScore'])

Structure of the matchInfo:
dict_keys(['matchId', 'seriesId', 'seriesName', 'matchDesc', 'matchFormat', 'startDate', 'endDate', 'state', 'status', 'team1', 'team2', 'venueInfo', 'currBatTeamId', 'seriesStartDt', 'seriesEndDt', 'isTimeAnnounced', 'stateTitle'])

Structure of the matchScore:
dict_keys(['team1Score'])

Path to access the list of matches: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches']
Path to access match info: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchInfo']
Path to access match score: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchScore'] (Note: 'matchScore' may not be present for all matches)

**Reasoning**:
Iterate through the nested data structure to extract the specified match details and store them in a list of dictionaries.

In [ ]:
match_Live_data = []

for match_type_entry in data['typeMatches']:
    for series_match_entry in match_type_entry['seriesMatches']:
        if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
            for match in series_match_entry['seriesAdWrapper']['matches']:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    extracted_details = {
                        'matchId': match_info.get('matchId'),
                        'seriesName': match_info.get('seriesName'),
                        'matchDesc': match_info.get('matchDesc'),
                        'matchFormat': match_info.get('matchFormat'),
                        'state': match_info.get('state'),
                        'status': match_info.get('status'),
                        'team1Name': match_info['team1'].get('teamName') if 'team1' in match_info else None,
                        'team2Name': match_info['team2'].get('teamName') if 'team2' in match_info else None
                    }
                    match_Live_data.append(extracted_details)

display(match_Live_data)

[{'matchId': 130019,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '2nd Match, Group A',
  'matchFormat': 'T20',
  'state': 'In Progress',
  'status': 'India opt to bowl',
  'team1Name': 'United Arab Emirates',
  'team2Name': 'India'},
 {'matchId': 113199,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '56th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Match delayed by rain - Essex lead by 124 runs',
  'team1Name': 'Durham',
  'team2Name': 'Essex'},
 {'matchId': 113211,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '59th Match',
  'matchFormat': 'TEST',
  'state': 'Stumps',
  'status': 'Day 3: Stumps - Sussex need 241 runs',
  'team1Name': 'Hampshire',
  'team2Name': 'Sussex'},
 {'matchId': 113202,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '57th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Rain stops play - Yorkshire trail by 424 runs',
  'team1Name': 'Somerset',
  'team2Name': 'Yorkshire'},
 {'matchId': 113217,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '60th Match',
  'matchFormat': 'TEST',
  'state': 'In Progress',
  'status': 'Day 3: 3rd Session - Nottinghamshire need 120 runs',
  'team1Name': 'Worcestershire',
  'team2Name': 'Nottinghamshire'},
 {'matchId': 113208,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '58th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Rain stops play - Surrey lead by 274 runs',
  'team1Name': 'Surrey',
  'team2Name': 'Warwickshire'},
 {'matchId': 116495,
  'seriesName': 'New Zealand A tour of South Africa, 2025',
  'matchDesc': '1st Unofficial Test',
  'matchFormat': 'TEST',
  'state': 'Complete',
  'status': 'New Zealand A won by 185 runs',
  'team1Name': 'New Zealand A',
  'team2Name': 'South Africa A'},
 {'matchId': 113625,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '48th Match',
  'matchFormat': 'TEST',
  'state': 'Tea',
  'status': 'Day 3: Tea Break - Kent lead by 179 runs',
  'team1Name': 'Kent',
  'team2Name': 'Lancashire'},
 {'matchId': 113613,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '46th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Match delayed due to rain  - Derbyshire lead by 18 runs',
  'team1Name': 'Derbyshire',
  'team2Name': 'Middlesex'},
 {'matchId': 113616,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '47th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Match delayed due to rain - Northamptonshire trail by 54 runs',
  'team1Name': 'Glamorgan',
  'team2Name': 'Northamptonshire'},
 {'matchId': 113607,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '45th Match',
  'matchFormat': 'TEST',
  'state': 'Rain',
  'status': 'Day 3: Match delayed due to rain  - Gloucestershire lead by 148 runs',
  'team1Name': 'Gloucestershire',
  'team2Name': 'Leicestershire'},
 {'matchId': 131779,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '8th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Complete',
  'status': 'Vanuatu Women won by 7 wkts',
  'team1Name': 'Cook Islands Women',
  'team2Name': 'Vanuatu Women'},
 {'matchId': 131774,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '7th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Complete',
  'status': 'Papua New Guinea Women won by 168 runs',
  'team1Name': 'Papua New Guinea Women',
  'team2Name': 'Philippines Women'}]

In [ ]:
df_Live_matches = pd.DataFrame(match_Live_data)
display(df_Live_matches)

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130019,Asia Cup 2025,"2nd Match, Group A",T20,In Progress,India opt to bowl,United Arab Emirates,India
1,113199,County Championship Division One 2025,56th Match,TEST,Rain,Day 3: Match delayed by rain - Essex lead by 1...,Durham,Essex
2,113211,County Championship Division One 2025,59th Match,TEST,Stumps,Day 3: Stumps - Sussex need 241 runs,Hampshire,Sussex
3,113202,County Championship Division One 2025,57th Match,TEST,Rain,Day 3: Rain stops play - Yorkshire trail by 42...,Somerset,Yorkshire
4,113217,County Championship Division One 2025,60th Match,TEST,In Progress,Day 3: 3rd Session - Nottinghamshire need 120 ...,Worcestershire,Nottinghamshire
5,113208,County Championship Division One 2025,58th Match,TEST,Rain,Day 3: Rain stops play - Surrey lead by 274 runs,Surrey,Warwickshire
6,116495,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,Complete,New Zealand A won by 185 runs,New Zealand A,South Africa A
7,113625,County Championship Division Two 2025,48th Match,TEST,Tea,Day 3: Tea Break - Kent lead by 179 runs,Kent,Lancashire
8,113613,County Championship Division Two 2025,46th Match,TEST,Rain,Day 3: Match delayed due to rain - Derbyshire...,Derbyshire,Middlesex
9,113616,County Championship Division Two 2025,47th Match,TEST,Rain,Day 3: Match delayed due to rain - Northampton...,Glamorgan,Northamptonshire
10,113607,County Championship Division Two 2025,45th Match,TEST,Rain,Day 3: Match delayed due to rain - Gloucester...,Gloucestershire,Leicestershire
11,131779,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,Complete,Vanuatu Women won by 7 wkts,Cook Islands Women,Vanuatu Women
12,131774,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,Complete,Papua New Guinea Women won by 168 runs,Papua New Guinea Women,Philippines Women

In [ ]:
display(df_Live_matches.head())

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130019,Asia Cup 2025,"2nd Match, Group A",T20,In Progress,India opt to bowl,United Arab Emirates,India
1,113199,County Championship Division One 2025,56th Match,TEST,Rain,Day 3: Match delayed by rain - Essex lead by 1...,Durham,Essex
2,113211,County Championship Division One 2025,59th Match,TEST,Stumps,Day 3: Stumps - Sussex need 241 runs,Hampshire,Sussex
3,113202,County Championship Division One 2025,57th Match,TEST,Rain,Day 3: Rain stops play - Yorkshire trail by 42...,Somerset,Yorkshire
4,113217,County Championship Division One 2025,60th Match,TEST,In Progress,Day 3: 3rd Session - Nottinghamshire need 120 ...,Worcestershire,Nottinghamshire

In [ ]:
# crete database sql as live database
import sqlite3 as sql
conn = sql.connect('Live_matches.db')

In [ ]:
# import live match data to db
df_Live_matches.to_sql('Live_matches', conn, if_exists='replace', index=False)

13

In [ ]:
# verify
pd.read_sql('SELECT * FROM Live_matches', conn)

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130019,Asia Cup 2025,"2nd Match, Group A",T20,In Progress,India opt to bowl,United Arab Emirates,India
1,113199,County Championship Division One 2025,56th Match,TEST,Rain,Day 3: Match delayed by rain - Essex lead by 1...,Durham,Essex
2,113211,County Championship Division One 2025,59th Match,TEST,Stumps,Day 3: Stumps - Sussex need 241 runs,Hampshire,Sussex
3,113202,County Championship Division One 2025,57th Match,TEST,Rain,Day 3: Rain stops play - Yorkshire trail by 42...,Somerset,Yorkshire
4,113217,County Championship Division One 2025,60th Match,TEST,In Progress,Day 3: 3rd Session - Nottinghamshire need 120 ...,Worcestershire,Nottinghamshire
5,113208,County Championship Division One 2025,58th Match,TEST,Rain,Day 3: Rain stops play - Surrey lead by 274 runs,Surrey,Warwickshire
6,116495,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,Complete,New Zealand A won by 185 runs,New Zealand A,South Africa A
7,113625,County Championship Division Two 2025,48th Match,TEST,Tea,Day 3: Tea Break - Kent lead by 179 runs,Kent,Lancashire
8,113613,County Championship Division Two 2025,46th Match,TEST,Rain,Day 3: Match delayed due to rain - Derbyshire...,Derbyshire,Middlesex
9,113616,County Championship Division Two 2025,47th Match,TEST,Rain,Day 3: Match delayed due to rain - Northampton...,Glamorgan,Northamptonshire
10,113607,County Championship Division Two 2025,45th Match,TEST,Rain,Day 3: Match delayed due to rain - Gloucester...,Gloucestershire,Leicestershire
11,131779,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,Complete,Vanuatu Women won by 7 wkts,Cook Islands Women,Vanuatu Women
12,131774,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,Complete,Papua New Guinea Women won by 168 runs,Papua New Guinea Women,Philippines Women

In [ ]:
# fetch upcoming matches data
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/upcoming"

headers = {
	"x-rapidapi-key": "7cd1451496msh26d2809dcb7535ap12515bjsn5b15e7be8226",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
response = requests.get(url, headers=headers)
data = response.json()
print(data.keys())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matches': [{'matchInfo': {'matchId': 130030, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '3rd Match, Group B', 'matchFormat': 'T20', 'startDate': '1757601000000', 'endDate': '1757613600000', 'state': 'Preview', 'status': 'Match starts at Sep 11, 14:30 GMT', 'team1': {'teamId': 6, 'teamName': 'Bangladesh', 'teamSName': 'BAN', 'imageId': 172120}, 'team2': {'teamId': 8, 'teamName': 'Hong Kong', 'teamSName': 'HK', 'imageId': 172122}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}, {'matchInfo': {'matchId': 130047, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '4th Match, Group A', 'matchFormat': 'T20', 'startDate': '1757687400000', 'endDate': '1757700000000', 'state': 'Upcoming', 'status': 'Match starts at Sep 12, 14:30 GMT', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 172353}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130058, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '5th Match, Group B', 'matchFormat': 'T20', 'startDate': '1757773800000', 'endDate': '1757786400000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 14:30 GMT', 'team1': {'teamId': 6, 'teamName': 'Bangladesh', 'teamSName': 'BAN', 'imageId': 172120}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130069, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '6th Match, Group A', 'matchFormat': 'T20', 'startDate': '1757860200000', 'endDate': '1757872800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 14, 14:30 GMT', 'team1': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 719031}, 'team2': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130074, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '7th Match, Group A', 'matchFormat': 'T20', 'startDate': '1757937600000', 'endDate': '1757950200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 15, 12:00 GMT', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'team2': {'teamId': 304, 'teamName': 'Oman', 'teamSName': 'OMAN', 'imageId': 172353}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130080, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '8th Match, Group B', 'matchFormat': 'T20', 'startDate': '1757946600000', 'endDate': '1757959200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 15, 14:30 GMT', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'team2': {'teamId': 8, 'teamName': 'Hong Kong', 'teamSName': 'HK', 'imageId': 172122}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130085, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '9th Match, Group B', 'matchFormat': 'T20', 'startDate': '1758033000000', 'endDate': '1758045600000', 'state': 'Upcoming', 'status': 'Match starts at Sep 16, 14:30 GMT', 'team1': {'teamId': 6, 'teamName': 'Bangladesh', 'teamSName': 'BAN', 'imageId': 172120}, 'team2': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 130096, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '10th Match, Group A', 'matchFormat': 'T20', 'startDate': '1758119400000', 'endDate': '1758132000000', 'state': 'Upcoming', 'status': 'Match starts at Sep 17, 14:30 GMT', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'isTournament': True, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}, {'seriesAdWrapper': {'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matches': [{'matchInfo': {'matchId': 105802, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757525400000', 'endDate': '1757538000000', 'state': 'Preview', 'status': 'Match starts at Sep 10, 17:30 GMT', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'venueInfo': {'id': 62, 'ground': 'Sophia Gardens', 'city': 'Cardiff', 'timezone': '+01:00', 'latitude': '51.484257', 'longitude': '-3.189187'}, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}, {'matchInfo': {'matchId': 105804, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757698200000', 'endDate': '1757710800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 12, 17:30 GMT', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'venueInfo': {'id': 65, 'ground': 'Emirates Old Trafford', 'city': 'Manchester', 'timezone': '+01:00', 'latitude': '53.463066', 'longitude': '-2.291301'}, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 105812, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757856600000', 'endDate': '1757869200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 14, 13:30 GMT', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'venueInfo': {'id': 18, 'ground': 'Trent Bridge', 'city': 'Nottingham', 'timezone': '+01:00', 'latitude': '52.936884', 'longitude': '-1.132230'}, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}, {'seriesAdWrapper': {'seriesId': 8802, 'seriesName': 'England tour of Ireland, 2025', 'matches': [{'matchInfo': {'matchId': 105844, 'seriesId': 8802, 'seriesName': 'England tour of Ireland, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1758112200000', 'endDate': '1758124800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 17, 12:30 GMT', 'team1': {'teamId': 27, 'teamName': 'Ireland', 'teamSName': 'IRE', 'imageId': 495001}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'venueInfo': {'id': 370, 'ground': 'The Village', 'city': 'Dublin', 'timezone': '+01:00', 'latitude': '53.32568', 'longitude': '-6.261829'}, 'seriesStartDt': '1757980800000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}, {'seriesAdWrapper': {'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matches': [{'matchInfo': {'matchId': 134667, 'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757662200000', 'endDate': '1757674800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 12, 07:30 GMT', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 551, 'teamName': 'Mozambique', 'teamSName': 'MOZ', 'imageId': 172603}, 'venueInfo': {'id': 1877, 'ground': 'Malkerns Country Club oval', 'city': 'Malkerns', 'timezone': '+02:00', 'latitude': '-26.52192', 'longitude': '31.19320'}, 'seriesStartDt': '1757548800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 134672, 'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757676600000', 'endDate': '1757689200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 12, 11:30 GMT', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 551, 'teamName': 'Mozambique', 'teamSName': 'MOZ', 'imageId': 172603}, 'venueInfo': {'id': 1877, 'ground': 'Malkerns Country Club oval', 'city': 'Malkerns', 'timezone': '+02:00', 'latitude': '-26.52192', 'longitude': '31.19320'}, 'seriesStartDt': '1757548800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 134683, 'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757748600000', 'endDate': '1757761200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 07:30 GMT', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 551, 'teamName': 'Mozambique', 'teamSName': 'MOZ', 'imageId': 172603}, 'venueInfo': {'id': 1877, 'ground': 'Malkerns Country Club oval', 'city': 'Malkerns', 'timezone': '+02:00', 'latitude': '-26.52192', 'longitude': '31.19320'}, 'seriesStartDt': '1757548800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 134694, 'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matchDesc': '4th T20I', 'matchFormat': 'T20', 'startDate': '1757763000000', 'endDate': '1757775600000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 11:30 GMT', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 551, 'teamName': 'Mozambique', 'teamSName': 'MOZ', 'imageId': 172603}, 'venueInfo': {'id': 1877, 'ground': 'Malkerns Country Club oval', 'city': 'Malkerns', 'timezone': '+02:00', 'latitude': '-26.52192', 'longitude': '31.19320'}, 'seriesStartDt': '1757548800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 134705, 'seriesId': 10917, 'seriesName': 'Mozambique tour of Eswatini 2025', 'matchDesc': '5th T20I', 'matchFormat': 'T20', 'startDate': '1757847600000', 'endDate': '1757860200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 14, 11:00 GMT', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 551, 'teamName': 'Mozambique', 'teamSName': 'MOZ', 'imageId': 172603}, 'venueInfo': {'id': 1877, 'ground': 'Malkerns Country Club oval', 'city': 'Malkerns', 'timezone': '+02:00', 'latitude': '-26.52192', 'longitude': '31.19320'}, 'seriesStartDt': '1757548800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 4}}, {'seriesAdWrapper': {'seriesId': 10928, 'seriesName': 'Namibia tour of Zimbabwe 2025', 'matches': [{'matchInfo': {'matchId': 134711, 'seriesId': 10928, 'seriesName': 'Namibia tour of Zimbabwe 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757921400000', 'endDate': '1757934000000', 'state': 'Upcoming', 'status': 'Match starts at Sep 15, 07:30 GMT', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 172229}, 'venueInfo': {'id': 70, 'ground': 'Queens Sports Club', 'city': 'Bulawayo', 'timezone': '+02:00', 'latitude': '-20.145151', 'longitude': '28.588901'}, 'seriesStartDt': '1757808000000', 'seriesEndDt': '1758240000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 134722, 'seriesId': 10928, 'seriesName': 'Namibia tour of Zimbabwe 2025', 'matchDesc': ' 2nd T20I', 'matchFormat': 'T20', 'startDate': '1758022200000', 'endDate': '1758034800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 16, 11:30 GMT', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 172229}, 'venueInfo': {'id': 70, 'ground': 'Queens Sports Club', 'city': 'Bulawayo', 'timezone': '+02:00', 'latitude': '-20.145151', 'longitude': '28.588901'}, 'seriesStartDt': '1757808000000', 'seriesEndDt': '1758240000000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}]}, {'matchType': 'League', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matches': [{'matchInfo': {'matchId': 116783, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '26th Match', 'matchFormat': 'T20', 'startDate': '1757545200000', 'endDate': '1757557800000', 'state': 'Preview', 'status': 'Match starts at Sep 11, 23:00 GMT', 'team1': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'team2': {'teamId': 1978, 'teamName': 'Antigua and Barbuda Falcons', 'teamSName': 'ABF', 'imageId': 507236}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Preview'}}, {'matchInfo': {'matchId': 116786, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '27th Match', 'matchFormat': 'T20', 'startDate': '1757631600000', 'endDate': '1757644200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 12, 23:00 GMT', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 302, 'teamName': 'St Kitts and Nevis Patriots', 'teamSName': 'SNP', 'imageId': 172351}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 116795, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '28th Match', 'matchFormat': 'T20', 'startDate': '1757718000000', 'endDate': '1757730600000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 23:00 GMT', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 271, 'teamName': 'Trinbago Knight Riders', 'teamSName': 'TKR', 'imageId': 172325}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 116801, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '29th Match', 'matchFormat': 'T20', 'startDate': '1757775600000', 'endDate': '1757788200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 15:00 GMT', 'team1': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'team2': {'teamId': 263, 'teamName': 'Saint Lucia Kings', 'teamSName': 'SLK', 'imageId': 172316}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 116810, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '30th Match', 'matchFormat': 'T20', 'startDate': '1757890800000', 'endDate': '1757903400000', 'state': 'Upcoming', 'status': 'Match starts at Sep 15, 23:00 GMT', 'team1': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'team2': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}, {'matchInfo': {'matchId': 116813, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': 'Eliminator', 'matchFormat': 'T20', 'startDate': '1758067200000', 'endDate': '1758079800000', 'state': 'Upcoming', 'status': 'Match starts at Sep 16, 00:00 GMT', 'team1': {'teamId': 106, 'teamName': 'TBC', 'teamSName': 'TBC', 'imageId': 172198}, 'team2': {'teamId': 106, 'teamName': 'TBC', 'teamSName': 'TBC', 'imageId': 172198}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'isTournament': True, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'Upcoming Match'}}]}}, {'seriesAdWrapper': {'seriesId': 9257, 'seriesName': 'T20 Blast 2025', 'matches': [{'matchInfo': {'matchId': 111085, 'seriesId': 9257, 'seriesName': 'T20 Blast 2025', 'matchDesc': '1st Semi-Final', 'matchFormat': 'T20', 'startDate': '1757757600000', 'endDate': '1757770200000', 'state': 'Upcoming', 'status': 'Match starts at Sep 13, 10:00 GMT', 'team1': {'teamId': 142, 'teamName': 'Northamptonshire', 'teamSName': 'NHNTS', 'imageId': 172209}, 'team2': {'teamId': 153, 'teamName': 'Hampshire', 'teamSName': 'HAM', 'imageId': 172220}, 'venueInfo': {'id'

In [ ]:
# Examine the structure of a single match type entry
if data and data['typeMatches']:
    first_match_type = data['typeMatches'][0]
    print("\nStructure of the first match type entry:")
    print(first_match_type.keys())

    if first_match_type and first_match_type['seriesMatches']:
        first_series_match = first_match_type['seriesMatches'][0]
        print("\nStructure of the first series match entry:")
        print(first_series_match.keys())

        if first_series_match and 'seriesAdWrapper' in first_series_match and 'matches' in first_series_match['seriesAdWrapper']:
            if first_series_match['seriesAdWrapper']['matches']:
                first_match = first_series_match['seriesAdWrapper']['matches'][0]
                print("\nStructure of the first match entry:")
                print(first_match.keys())

                if first_match and 'matchInfo' in first_match:
                    print("\nStructure of the matchInfo:")
                    print(first_match['matchInfo'].keys())
            else:
                print("\nNo matches found in the first series match entry.")
        else:
             print("\n'seriesAdWrapper' or 'matches' not found in the first series match entry.")
    else:
        print("\n'seriesMatches' not found in the first match type entry.")
else:
    print("\n'typeMatches' not found or is empty in the data.")


# Outline the path to access the list of matches and key details
print("\nPath to access the list of matches: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches']")
print("Path to access match info: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchInfo']")

Structure of the first match type entry:
dict_keys(['matchType', 'seriesMatches'])

Structure of the first series match entry:
dict_keys(['seriesAdWrapper'])

Structure of the first match entry:
dict_keys(['matchInfo'])

Structure of the matchInfo:
dict_keys(['matchId', 'seriesId', 'seriesName', 'matchDesc', 'matchFormat', 'startDate', 'endDate', 'state', 'status', 'team1', 'team2', 'venueInfo', 'isTournament', 'seriesStartDt', 'seriesEndDt', 'isTimeAnnounced', 'stateTitle'])

Path to access the list of matches: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches']
Path to access match info: data['typeMatches'][i]['seriesMatches'][j]['seriesAdWrapper']['matches'][k]['matchInfo']

In [ ]:
upcoming_match_data = []

for match_type_entry in data['typeMatches']:
    for series_match_entry in match_type_entry['seriesMatches']:
        if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
            for match in series_match_entry['seriesAdWrapper']['matches']:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    extracted_details = {
                        'matchId': match_info.get('matchId'),
                        'seriesName': match_info.get('seriesName'),
                        'matchDesc': match_info.get('matchDesc'),
                        'matchFormat': match_info.get('matchFormat'),
                        'state': match_info.get('state'),
                        'status': match_info.get('status'),
                        'team1Name': match_info['team1'].get('teamName') if 'team1' in match_info else None,
                        'team2Name': match_info['team2'].get('teamName') if 'team2' in match_info else None
                    }
                    upcoming_match_data.append(extracted_details)

display(upcoming_match_data)

[{'matchId': 130030,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '3rd Match, Group B',
  'matchFormat': 'T20',
  'state': 'Preview',
  'status': 'Match starts at Sep 11, 14:30 GMT',
  'team1Name': 'Bangladesh',
  'team2Name': 'Hong Kong'},
 {'matchId': 130047,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '4th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 14:30 GMT',
  'team1Name': 'Pakistan',
  'team2Name': 'Oman'},
 {'matchId': 130058,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '5th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 14:30 GMT',
  'team1Name': 'Bangladesh',
  'team2Name': 'Sri Lanka'},
 {'matchId': 130069,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '6th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 14:30 GMT',
  'team1Name': 'India',
  'team2Name': 'Pakistan'},
 {'matchId': 130074,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '7th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 12:00 GMT',
  'team1Name': 'United Arab Emirates',
  'team2Name': 'Oman'},
 {'matchId': 130080,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '8th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 14:30 GMT',
  'team1Name': 'Sri Lanka',
  'team2Name': 'Hong Kong'},
 {'matchId': 130085,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '9th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 14:30 GMT',
  'team1Name': 'Bangladesh',
  'team2Name': 'Afghanistan'},
 {'matchId': 130096,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '10th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 17, 14:30 GMT',
  'team1Name': 'Pakistan',
  'team2Name': 'United Arab Emirates'},
 {'matchId': 105802,
  'seriesName': 'South Africa tour of England, 2025',
  'matchDesc': '1st T20I',
  'matchFormat': 'T20',
  'state': 'Preview',
  'status': 'Match starts at Sep 10, 17:30 GMT',
  'team1Name': 'England',
  'team2Name': 'South Africa'},
 {'matchId': 105804,
  'seriesName': 'South Africa tour of England, 2025',
  'matchDesc': '2nd T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 17:30 GMT',
  'team1Name': 'England',
  'team2Name': 'South Africa'},
 {'matchId': 105812,
  'seriesName': 'South Africa tour of England, 2025',
  'matchDesc': '3rd T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 13:30 GMT',
  'team1Name': 'England',
  'team2Name': 'South Africa'},
 {'matchId': 105844,
  'seriesName': 'England tour of Ireland, 2025',
  'matchDesc': '1st T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 17, 12:30 GMT',
  'team1Name': 'Ireland',
  'team2Name': 'England'},
 {'matchId': 134667,
  'seriesName': 'Mozambique tour of Eswatini 2025',
  'matchDesc': '1st T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 07:30 GMT',
  'team1Name': 'Eswatini',
  'team2Name': 'Mozambique'},
 {'matchId': 134672,
  'seriesName': 'Mozambique tour of Eswatini 2025',
  'matchDesc': '2nd T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 11:30 GMT',
  'team1Name': 'Eswatini',
  'team2Name': 'Mozambique'},
 {'matchId': 134683,
  'seriesName': 'Mozambique tour of Eswatini 2025',
  'matchDesc': '3rd T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 07:30 GMT',
  'team1Name': 'Eswatini',
  'team2Name': 'Mozambique'},
 {'matchId': 134694,
  'seriesName': 'Mozambique tour of Eswatini 2025',
  'matchDesc': '4th T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 11:30 GMT',
  'team1Name': 'Eswatini',
  'team2Name': 'Mozambique'},
 {'matchId': 134705,
  'seriesName': 'Mozambique tour of Eswatini 2025',
  'matchDesc': '5th T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 11:00 GMT',
  'team1Name': 'Eswatini',
  'team2Name': 'Mozambique'},
 {'matchId': 134711,
  'seriesName': 'Namibia tour of Zimbabwe 2025',
  'matchDesc': '1st T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 07:30 GMT',
  'team1Name': 'Zimbabwe',
  'team2Name': 'Namibia'},
 {'matchId': 134722,
  'seriesName': 'Namibia tour of Zimbabwe 2025',
  'matchDesc': ' 2nd T20I',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 11:30 GMT',
  'team1Name': 'Zimbabwe',
  'team2Name': 'Namibia'},
 {'matchId': 116783,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '26th Match',
  'matchFormat': 'T20',
  'state': 'Preview',
  'status': 'Match starts at Sep 11, 23:00 GMT',
  'team1Name': 'Guyana Amazon Warriors',
  'team2Name': 'Antigua and Barbuda Falcons'},
 {'matchId': 116786,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '27th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 23:00 GMT',
  'team1Name': 'Barbados Royals',
  'team2Name': 'St Kitts and Nevis Patriots'},
 {'matchId': 116795,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '28th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 23:00 GMT',
  'team1Name': 'Barbados Royals',
  'team2Name': 'Trinbago Knight Riders'},
 {'matchId': 116801,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '29th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 15:00 GMT',
  'team1Name': 'Guyana Amazon Warriors',
  'team2Name': 'Saint Lucia Kings'},
 {'matchId': 116810,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '30th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 23:00 GMT',
  'team1Name': 'Guyana Amazon Warriors',
  'team2Name': 'Barbados Royals'},
 {'matchId': 116813,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': 'Eliminator',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 00:00 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 111085,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': '1st Semi-Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 10:00 GMT',
  'team1Name': 'Northamptonshire',
  'team2Name': 'Hampshire'},
 {'matchId': 111093,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': '2nd Semi-Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 13:30 GMT',
  'team1Name': 'Lancashire',
  'team2Name': 'Somerset'},
 {'matchId': 111101,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': 'Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 17:45 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 123688,
  'seriesName': 'Duleep Trophy 2025',
  'matchDesc': 'Final',
  'matchFormat': 'TEST',
  'state': 'Preview',
  'status': 'Match starts at Sep 11, 04:00 GMT',
  'team1Name': 'South Zone',
  'team2Name': 'Central Zone'},
 {'matchId': 133451,
  'seriesName': 'Australia Domestic One-Day Cup 2025-26',
  'matchDesc': '1st Match',
  'matchFormat': 'ODI',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 23:30 GMT',
  'team1Name': 'New South Wales',
  'team2Name': 'Tasmania'},
 {'matchId': 133462,
  'seriesName': 'Australia Domestic One-Day Cup 2025-26',
  'matchDesc': '2nd Match',
  'matchFormat': 'ODI',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 17, 23:30 GMT',
  'team1Name': 'Queensland',
  'team2Name': 'Victoria'},
 {'matchId': 119843,
  'seriesName': 'Australia A tour of India, 2025',
  'matchDesc': '1st Unofficial Test',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 03:30 GMT',
  'team1Name': 'India A',
  'team2Name': 'Australia A'},
 {'matchId': 113226,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '61st Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Warwickshire',
  'team2Name': 'Essex'},
 {'matchId': 113229,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '62nd Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Durham',
  'team2Name': 'Worcestershire'},
 {'matchId': 113235,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '63rd Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Sussex',
  'team2Name': 'Yorkshire'},
 {'matchId': 113244,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '64th Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Surrey',
  'team2Name': 'Nottinghamshire'},
 {'matchId': 113253,
  'seriesName': 'County Championship Division One 2025',
  'matchDesc': '65th Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Somerset',
  'team2Name': 'Hampshire'},
 {'matchId': 116498,
  'seriesName': 'New Zealand A tour of South Africa, 2025',
  'matchDesc': '2nd Unofficial Test',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 08:00 GMT',
  'team1Name': 'South Africa A',
  'team2Name': 'New Zealand A'},
 {'matchId': 113631,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '49th Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Leicestershire',
  'team2Name': 'Kent'},
 {'matchId': 113634,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '50th Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Lancashire',
  'team2Name': 'Middlesex'},
 {'matchId': 113640,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '51st Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Gloucestershire',
  'team2Name': 'Northamptonshire'},
 {'matchId': 113649,
  'seriesName': 'County Championship Division Two 2025',
  'matchDesc': '52nd Match',
  'matchFormat': 'TEST',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 10:00 GMT',
  'team1Name': 'Derbyshire',
  'team2Name': 'Glamorgan'},
 {'matchId': 119819,
  'seriesName': 'Australia Women tour of India, 2025',
  'matchDesc': '1st ODI',
  'matchFormat': 'ODI',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 08:00 GMT',
  'team1Name': 'India Women',
  'team2Name': 'Australia Women'},
 {'matchId': 119825,
  'seriesName': 'Australia Women tour of India, 2025',
  'matchDesc': '2nd ODI',
  'matchFormat': 'ODI',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 17, 08:00 GMT',
  'team1Name': 'India Women',
  'team2Name': 'Australia Women'},
 {'matchId': 131790,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '9th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 09:30 GMT',
  'team1Name': 'Cook Islands Women',
  'team2Name': 'Indonesia Women'},
 {'matchId': 131801,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '10th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 09:30 GMT',
  'team1Name': 'Philippines Women',
  'team2Name': 'Japan Women'},
 {'matchId': 131807,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '11th Match, Group A',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 13:30 GMT',
  'team1Name': 'Fiji Women',
  'team2Name': 'Vanuatu Women'},
 {'matchId': 131818,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '12th Match, Group B',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 13:30 GMT',
  'team1Name': 'Samoa Women',
  'team2Name': 'Papua New Guinea Women'},
 {'matchId': 131823,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': 'Playoffs - Match 1',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 09:00 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131829,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': 'Playoffs - Match 2',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Aug 13, 09:00 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131845,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '2nd Semi-Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 13:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131834,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '1st Semi-Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 13:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131856,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '5th Place Play-off',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 09:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131867,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '7th Place Play-off',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 09:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131873,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': 'Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 13:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 131884,
  'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025',
  'matchDesc': '3rd place play-off',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 15, 13:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 133814,
  'seriesName': 'Luxembourg Womens T20I Tri-Series, 2025',
  'matchDesc': '1st Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 12, 14:00 GMT',
  'team1Name': 'Luxembourg Women',
  'team2Name': 'Switzerland Women'},
 {'matchId': 133820,
  'seriesName': 'Luxembourg Womens T20I Tri-Series, 2025',
  'matchDesc': '2nd Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 08:30 GMT',
  'team1Name': 'Austria Women',
  'team2Name': 'Luxembourg Women'},
 {'matchId': 133831,
  'seriesName': 'Luxembourg Womens T20I Tri-Series, 2025',
  'matchDesc': '3rd Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 13, 12:30 GMT',
  'team1Name': 'Austria Women',
  'team2Name': 'Switzerland Women'},
 {'matchId': 133836,
  'seriesName': 'Luxembourg Womens T20I Tri-Series, 2025',
  'matchDesc': '3rd Place Play-off',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 08:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 133847,
  'seriesName': 'Luxembourg Womens T20I Tri-Series, 2025',
  'matchDesc': 'Final',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 12:30 GMT',
  'team1Name': 'TBC',
  'team2Name': 'TBC'},
 {'matchId': 133688,
  'seriesName': 'South Africa Women tour of Pakistan, 2025',
  'matchDesc': '1st ODI',
  'matchFormat': 'ODI',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 16, 04:30 GMT',
  'team1Name': 'Pakistan Women',
  'team2Name': 'South Africa Women'},
 {'matchId': 122104,
  'seriesName': 'Womens Caribbean Premier League 2025',
  'matchDesc': '3rd Match',
  'matchFormat': 'T20',
  'state': 'Preview',
  'status': 'Match starts at Sep 10, 18:00 GMT',
  'team1Name': 'Barbados Royals Women',
  'team2Name': 'Trinbago Knight Riders Women'},
 {'matchId': 122115,
  'seriesName': 'Womens Caribbean Premier League 2025',
  'matchDesc': '4th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 20:00 GMT',
  'team1Name': 'Guyana Amazon Warriors Women',
  'team2Name': 'Trinbago Knight Riders Women'},
 {'matchId': 122126,
  'seriesName': 'Womens Caribbean Premier League 2025',
  'matchDesc': '5th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 14, 18:00 GMT',
  'team1Name': 'Guyana Amazon Warriors Women',
  'team2Name': 'Barbados Royals Women'},
 {'matchId': 122137,
  'seriesName': 'Womens Caribbean Premier League 2025',
  'matchDesc': '6th Match',
  'matchFormat': 'T20',
  'state': 'Upcoming',
  'status': 'Match starts at Sep 17, 19:00 GMT',
  'team1Name': 'Barbados Royals Women',
  'team2Name': 'Trinbago Knight Riders Women'}]

In [ ]:
df_upcoming_matches = pd.DataFrame(upcoming_match_data)

In [ ]:
display(df_upcoming_matches.head())

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130030,Asia Cup 2025,"3rd Match, Group B",T20,Preview,"Match starts at Sep 11, 14:30 GMT",Bangladesh,Hong Kong
1,130047,Asia Cup 2025,"4th Match, Group A",T20,Upcoming,"Match starts at Sep 12, 14:30 GMT",Pakistan,Oman
2,130058,Asia Cup 2025,"5th Match, Group B",T20,Upcoming,"Match starts at Sep 13, 14:30 GMT",Bangladesh,Sri Lanka
3,130069,Asia Cup 2025,"6th Match, Group A",T20,Upcoming,"Match starts at Sep 14, 14:30 GMT",India,Pakistan
4,130074,Asia Cup 2025,"7th Match, Group A",T20,Upcoming,"Match starts at Sep 15, 12:00 GMT",United Arab Emirates,Oman

In [ ]:
display(df_upcoming_matches.head())

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130030,Asia Cup 2025,"3rd Match, Group B",T20,Preview,"Match starts at Sep 11, 14:30 GMT",Bangladesh,Hong Kong
1,130047,Asia Cup 2025,"4th Match, Group A",T20,Upcoming,"Match starts at Sep 12, 14:30 GMT",Pakistan,Oman
2,130058,Asia Cup 2025,"5th Match, Group B",T20,Upcoming,"Match starts at Sep 13, 14:30 GMT",Bangladesh,Sri Lanka
3,130069,Asia Cup 2025,"6th Match, Group A",T20,Upcoming,"Match starts at Sep 14, 14:30 GMT",India,Pakistan
4,130074,Asia Cup 2025,"7th Match, Group A",T20,Upcoming,"Match starts at Sep 15, 12:00 GMT",United Arab Emirates,Oman

In [ ]:
# save this data in diffent table as ucoming match save in live matches db
df_upcoming_matches.to_sql('upcoming_matches', conn, if_exists='replace', index=False)

66

In [ ]:
# verify
pd.read_sql('SELECT * FROM upcoming_matches', conn)

,matchId,seriesName,matchDesc,matchFormat,state,status,team1Name,team2Name
0,130030,Asia Cup 2025,"3rd Match, Group B",T20,Preview,"Match starts at Sep 11, 14:30 GMT",Bangladesh,Hong Kong
1,130047,Asia Cup 2025,"4th Match, Group A",T20,Upcoming,"Match starts at Sep 12, 14:30 GMT",Pakistan,Oman
2,130058,Asia Cup 2025,"5th Match, Group B",T20,Upcoming,"Match starts at Sep 13, 14:30 GMT",Bangladesh,Sri Lanka
3,130069,Asia Cup 2025,"6th Match, Group A",T20,Upcoming,"Match starts at Sep 14, 14:30 GMT",India,Pakistan
4,130074,Asia Cup 2025,"7th Match, Group A",T20,Upcoming,"Match starts at Sep 15, 12:00 GMT",United Arab Emirates,Oman
...,...,...,...,...,...,...,...,...
61,133688,"South Africa Women tour of Pakistan, 2025",1st ODI,ODI,Upcoming,"Match starts at Sep 16, 04:30 GMT",Pakistan Women,South Africa Women
62,122104,Womens Caribbean Premier League 2025,3rd Match,T20,Preview,"Match starts at Sep 10, 18:00 GMT",Barbados Royals Women,Trinbago Knight Riders Women
63,122115,Womens Caribbean Premier League 2025,4th Match,T20,Upcoming,"Match starts at Sep 14, 20:00 GMT",Guyana Amazon Warriors Women,Trinbago Knight Riders Women
64,122126,Womens Caribbean Premier League 2025,5th Match,T20,Upcoming,"Match starts at Sep 14, 18:00 GMT",Guyana Amazon Warriors Women,Barbados Royals Women
65,122137,Womens Caribbean Premier League 2025,6th Match,T20,Upcoming,"Match starts at Sep 17, 19:00 GMT",Barbados Royals Women,Trinbago Knight Riders Women

In [ ]:
# now fetch recent match data
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "7cd1451496msh26d2809dcb7535ap12515bjsn5b15e7be8226",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)


print(response.json())
response = requests.get(url, headers=headers)
data = response.json()
print(data.keys())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matches': [{'matchInfo': {'matchId': 130008, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '1st Match, Group B', 'matchFormat': 'T20', 'startDate': '1757428200000', 'endDate': '1757440800000', 'state': 'Complete', 'status': 'Afghanistan won by 94 runs', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'team2': {'teamId': 8, 'teamName': 'Hong Kong', 'teamSName': 'HK', 'imageId': 172122}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'currBatTeamId': 96, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 188, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 94, 'wickets': 9, 'overs': 19.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matches': [{'matchInfo': {'matchId': 105788, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1756987200000', 'endDate': '1757016000000', 'state': 'Complete', 'status': 'South Africa won by 5 runs', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'venueInfo': {'id': 19, 'ground': "Lord's", 'city': 'London', 'timezone': '+01:00', 'latitude': '51.529488', 'longitude': '-0.172926'}, 'currBatTeamId': 11, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 330, 'wickets': 8, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 325, 'wickets': 9, 'overs': 49.6}}}}, {'matchInfo': {'matchId': 105794, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1757239200000', 'endDate': '1757268000000', 'state': 'Complete', 'status': 'England won by 342 runs', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'venueInfo': {'id': 21, 'ground': 'The Rose Bowl', 'city': 'Southampton', 'timezone': '+01:00', 'latitude': '50.924131', 'longitude': '-1.322163'}, 'currBatTeamId': 9, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 414, 'wickets': 5, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 72, 'wickets': 10, 'overs': 20.5}}}}]}}, {'seriesAdWrapper': {'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matches': [{'matchInfo': {'matchId': 131086, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1757084400000', 'endDate': '1757097000000', 'state': 'Complete', 'status': 'Afghanistan won by 4 runs', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 96, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 170, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 5, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 131075, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1756998000000', 'endDate': '1757010600000', 'state': 'Complete', 'status': 'Pakistan won by 31 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 3, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 171, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 140, 'wickets': 7, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 131092, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': 'Final', 'matchFormat': 'T20', 'startDate': '1757257200000', 'endDate': '1757269800000', 'state': 'Complete', 'status': 'Pakistan won by 75 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 3, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 141, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 66, 'wickets': 10, 'overs': 15.5}}}}]}}, {'seriesAdWrapper': {'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matches': [{'matchInfo': {'matchId': 128919, 'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matchDesc': '85th Match', 'matchFormat': 'ODI', 'startDate': '1757169000000', 'endDate': '1757197800000', 'state': 'Abandon', 'status': 'Match abandoned due to wet outfield (no toss)', 'team1': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 172140}, 'team2': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 172137}, 'venueInfo': {'id': 139, 'ground': 'Maple Leaf North-West Ground', 'city': 'King City', 'timezone': '-04:00', 'latitude': '36.210861', 'longitude': '-121.126602'}, 'isTournament': True, 'seriesStartDt': '1707868800000', 'seriesEndDt': '1806451200000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 128908, 'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matchDesc': '84th Match', 'matchFormat': 'ODI', 'startDate': '1756996200000', 'endDate': '1757025000000', 'state': 'Complete', 'status': 'Scotland won by 55 runs (24 overs game due to rain)', 'team1': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 172137}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 172229}, 'venueInfo': {'id': 139, 'ground': 'Maple Leaf North-West Ground', 'city': 'King City', 'timezone': '-04:00', 'latitude': '36.210861', 'longitude': '-121.126602'}, 'currBatTeamId': 23, 'seriesStartDt': '1707868800000', 'seriesEndDt': '1806451200000', 'isTimeAnnounced': True, 'stateTitle': 'SCO Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 164, 'wickets': 10, 'overs': 23.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 109, 'wickets': 10, 'overs': 21.2}}}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 4}}, {'seriesAdWrapper': {'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matches': [{'matchInfo': {'matchId': 122973, 'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757244600000', 'endDate': '1757257200000', 'state': 'Complete', 'status': 'Sri Lanka won by 8 wkts', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'venueInfo': {'id': 69, 'ground': 'Harare Sports Club', 'city': 'Harare', 'timezone': '+02:00', 'latitude': '-17.814114', 'longitude': '31.050962'}, 'currBatTeamId': 5, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SL Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 191, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 193, 'wickets': 2, 'overs': 17.4}}}}, {'matchInfo': {'matchId': 122968, 'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757158200000', 'endDate': '1757170800000', 'state': 'Complete', 'status': 'Zimbabwe won by 5 wkts', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'venueInfo': {'id': 69, 'ground': 'Harare Sports Club', 'city': 'Harare', 'timezone': '+02:00', 'latitude': '-17.814114', 'longitude': '31.050962'}, 'currBatTeamId': 12, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'ZIM Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 80, 'wickets': 10, 'overs': 17.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 84, 'wickets': 5, 'overs': 14.2}}}}]}}, {'seriesAdWrapper': {'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matches': [{'matchInfo': {'matchId': 133187, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1757255400000', 'endDate': '1757268000000', 'state': 'Abandon', 'status': 'Match abandoned without toss', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 133176, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757239200000', 'endDate': '1757251800000', 'state': 'Abandon', 'status': 'Match abandoned without toss', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 133171, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757169000000', 'endDate': '1757181600000', 'state': 'Complete', 'status': 'Sweden won by 3 wkts', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'currBatTeamId': 534, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SWE Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 114, 'wickets': 10, 'overs': 19.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 116, 'wickets': 7, 'overs': 14.3}}}}, {'matchInfo': {'matchId': 133160, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757152800000', 'endDate': '1757165400000', 'state': 'Complete', 'status': 'Sweden won by 10 wkts', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'currBatTeamId': 534, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SWE Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 78, 'wickets': 10, 'overs': 16.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 81, 'overs': 10.5}}}}]}}]}, {'matchType': 'League', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matches': [{'matchInfo': {'matchId': 116765, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '24th Match', 'matchFormat': 'T20', 'startDate': '1757257200000', 'endDate': '1757269800000', 'state': 'Complete', 'status': 'Barbados Royals won by 27 runs', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 263, 'teamName': 'Saint Lucia Kings', 'teamSName': 'SLK', 'imageId': 172316}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 262, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'BR Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 191, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 164, 'wickets': 9, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116774, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '25th Match', 'matchFormat': 'T20', 'startDate': '1757289600000', 'endDate': '1757302200000', 'state': 'Complete', 'status': 'St Kitts and Nevis Patriots won by 5 runs', 'team1': {'teamId': 302, 'teamName': 'St Kitts and Nevis Patriots', 'teamSName': 'SNP', 'imageId': 172351}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'currBatTeamId': 302, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'SNP Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 149, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 144, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116759, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '23rd Match', 'matchFormat': 'T20', 'startDate': '1757199600000', 'endDate': '1757212200000', 'state': 'Complete', 'status': 'Guyana Amazon Warriors won by 3 wkts', 'team1': {'teamId': 271, 'teamName': 'Trinbago Knight Riders', 'teamSName': 'TKR', 'imageId': 172325}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'currBatTeamId': 159, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'GAW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 167, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 168, 'wickets': 7, 'overs': 19.5}}}}, {'matchInfo': {'matchId': 116750, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '22nd Match', 'matchFormat': 'T20', 'startDate': '1757113200000', 'endDate': '1757125800000', 'state': 'Complete', 'status': 'Antigua and Barbuda Falcons won by 4 wkts', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 1978, 'teamName': 'Antigua and Barbuda Falcons', 'teamSName': 'ABF', 'imageId': 507236}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 1978, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'ABF Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 187, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 188, 'wickets': 6, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116738, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '20th Match', 'matchFormat': 'T20', 'startDate': '1756940400000', 'endDate': '1756953000000', 'state': 'Complete', 'status': 'Saint Lucia Kings won by 7 wkts', 'team1': {'teamId': 271, 'teamName': 'Trinbago Knight Riders', 'teamSName': 'TKR', 'imageId': 172325}, 'team2': {'teamId': 263, 'teamName': 'Saint Lucia Kings', 'teamSName': 'SLK', 'imageId': 172316}, 'venueInfo': {'id': 500, 'ground': 'Brian Lara Stadium', 'city': 'Tarouba, Trinidad', 'timezone': '-04:00', 'latitude': '10.295034', 'longitude': '-61.445609'}, 'currBatTeamId': 263, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'SLK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 109, 'wickets': 10, 'overs': 18.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 112, 'wickets': 3, 'overs': 11.1}}}}, {'matchInfo': {'matchId': 116741, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '21st Match', 'matchFormat': 'T20', 'startDate': '1757026800000', 'endDate': '1757039400000', 'state': 'Complete', 'status': 'Guyana Amazon Warriors won by 4 wkts', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 159, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'GAW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 165, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 170, 'wickets': 6, 'overs': 19.4}}}}]}}, {'seriesAdWrapper': {'seriesId': 9257, 'seriesName': 'T20 Blast 2025', 'matches': [{'matchInfo': {'matchId': 111061, 'seriesId': 9257, 'seriesName': 'T20 Blast 2025', 'matchDesc': 'Quarter Final 1', 'matchFormat': 'T20', 'startDate': '1756920600000', 'endDate': '1756933200000', 'state': 'Complete', 'status': 'Northamptonshire won by 7 runs (14 Overs game  -  due to rain)', 'team1': {'teamId': 142, 'teamName': 'Northamptonshire', 'teamSName': 'NHNTS', 'imageId': 172209}, 'team2': {'teamId': 148, 'teamName': 'Surrey', 'teamSName': 'SUR', 'imageId': 172215}, 'venueInfo': {'id': 12, 'ground': 'Kennington Oval', 'city': 'London', 'timezone': '+01:00', 'latitude': '51.48368', 'longitude': '-0.114885'}, 'currBatTeamId': 142, 'seriesStartDt': '1748390400000', 'seriesEndDt': '1757808000

In [ ]:
# Examine the structure of the recent match data
print(data.keys())
print(data['typeMatches'])

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [ ]:
# Examine the structure of a single match type entry
if data and data['typeMatches']:
    first_match_type = data['typeMatches'][0]
    print("\nStructure of the first match type entry:")
    print(first_match_type.keys())
    if first_match_type and first_match_type['seriesMatches']:
        first_series_match = first_match_type['seriesMatches'][0]
        print("\nStructure of the first series match entry:")
        print(first_series_match.keys())
        if first_series_match and 'seriesAdWrapper' in first_series_match and 'matches' in first_series_match['seriesAdWrapper']:
            if first_series_match['seriesAdWrapper']['matches']:
                first_match = first_series_match['seriesAdWrapper']['matches'][0]
                print("\nStructure of the first match entry:")
                print(first_match.keys())
                if first_match and 'matchInfo' in first_match:
                    print("\nStructure of the matchInfo:")
                    print(first_match['matchInfo'].keys())
            else:
                print("\nNo matches found in the first series match entry.")
        else:
            print("\n'seriesAdWrapper' or 'matches' not found in the first series match entry.")
    else:
        print("\n'seriesMatches' not found in the first match type entry.")

Structure of the first match type entry:
dict_keys(['matchType', 'seriesMatches'])

Structure of the first series match entry:
dict_keys(['seriesAdWrapper'])

Structure of the first match entry:
dict_keys(['matchInfo', 'matchScore'])

Structure of the matchInfo:
dict_keys(['matchId', 'seriesId', 'seriesName', 'matchDesc', 'matchFormat', 'startDate', 'endDate', 'state', 'status', 'team1', 'team2', 'venueInfo', 'currBatTeamId', 'seriesStartDt', 'seriesEndDt', 'isTimeAnnounced', 'stateTitle'])

In [ ]:
recent_match_data = []

for match_type_entry in data['typeMatches']:
    for series_match_entry in match_type_entry['seriesMatches']:
        if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
            for match in series_match_entry['seriesAdWrapper']['matches']:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    extracted_details = {
                        'matchId': match_info.get('matchId'),
                        'seriesId': match_info.get('seriesId'),
                        'seriesName': match_info.get('seriesName'),
                        'matchDesc': match_info.get('matchDesc'),
                        'matchFormat': match_info.get('matchFormat'),
                        'startDate': match_info.get('startDate'),
                        'endDate': match_info.get('endDate'),
                        'state': match_info.get('state'),
                        'status': match_info.get('status'),
                        'team1': match_info.get('team1'),
                        'team2': match_info.get('team2'),
                        'venueInfo': match_info.get('venueInfo'),
                        'currBatTeamId': match_info.get('currBatTeamId'),
                        'seriesStartDt': match_info.get('seriesStartDt'),
                        'seriesEndDt': match_info.get('seriesEndDt'),
                        'isTimeAnnounced': match_info.get('isTimeAnnounced'),
                        'stateTitle': match_info.get('stateTitle')
                    }
                    # Extract overs from team1Score if available
                    if 'matchScore' in match and 'team1Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team1Score']:
                        extracted_details['team1_overs'] = match['matchScore']['team1Score']['inngs1'].get('overs')
                    else:
                        extracted_details['team1_overs'] = None

                    # Extract overs from team2Score if available
                    if 'matchScore' in match and 'team2Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team2Score']:
                        extracted_details['team2_overs'] = match['matchScore']['team2Score']['inngs1'].get('overs')
                    else:
                        extracted_details['team2_overs'] = None

                    recent_match_data.append(extracted_details)

display(recent_match_data)

[{'matchId': 130008,
  'seriesId': 10587,
  'seriesName': 'Asia Cup 2025',
  'matchDesc': '1st Match, Group B',
  'matchFormat': 'T20',
  'startDate': '1757428200000',
  'endDate': '1757440800000',
  'state': 'Complete',
  'status': 'Afghanistan won by 94 runs',
  'team1': {'teamId': 96,
   'teamName': 'Afghanistan',
   'teamSName': 'AFG',
   'imageId': 172188},
  'team2': {'teamId': 8,
   'teamName': 'Hong Kong',
   'teamSName': 'HK',
   'imageId': 172122},
  'venueInfo': {'id': 94,
   'ground': 'Sheikh Zayed Stadium',
   'city': 'Abu Dhabi',
   'timezone': '+04:00',
   'latitude': '24.416138',
   'longitude': '54.453566'},
  'currBatTeamId': 96,
  'seriesStartDt': '1757289600000',
  'seriesEndDt': '1759104000000',
  'isTimeAnnounced': True,
  'stateTitle': 'AFG Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 105788,
  'seriesId': 8788,
  'seriesName': 'South Africa tour of England, 2025',
  'matchDesc': '2nd ODI',
  'matchFormat': 'ODI',
  'startDate': '1756987200000',
  'endDate': '1757016000000',
  'state': 'Complete',
  'status': 'South Africa won by 5 runs',
  'team1': {'teamId': 11,
   'teamName': 'South Africa',
   'teamSName': 'RSA',
   'imageId': 172126},
  'team2': {'teamId': 9,
   'teamName': 'England',
   'teamSName': 'ENG',
   'imageId': 172123},
  'venueInfo': {'id': 19,
   'ground': "Lord's",
   'city': 'London',
   'timezone': '+01:00',
   'latitude': '51.529488',
   'longitude': '-0.172926'},
  'currBatTeamId': 11,
  'seriesStartDt': '1756684800000',
  'seriesEndDt': '1757894400000',
  'isTimeAnnounced': True,
  'stateTitle': 'RSA Won',
  'team1_overs': 49.6,
  'team2_overs': 49.6},
 {'matchId': 105794,
  'seriesId': 8788,
  'seriesName': 'South Africa tour of England, 2025',
  'matchDesc': '3rd ODI',
  'matchFormat': 'ODI',
  'startDate': '1757239200000',
  'endDate': '1757268000000',
  'state': 'Complete',
  'status': 'England won by 342 runs',
  'team1': {'teamId': 9,
   'teamName': 'England',
   'teamSName': 'ENG',
   'imageId': 172123},
  'team2': {'teamId': 11,
   'teamName': 'South Africa',
   'teamSName': 'RSA',
   'imageId': 172126},
  'venueInfo': {'id': 21,
   'ground': 'The Rose Bowl',
   'city': 'Southampton',
   'timezone': '+01:00',
   'latitude': '50.924131',
   'longitude': '-1.322163'},
  'currBatTeamId': 9,
  'seriesStartDt': '1756684800000',
  'seriesEndDt': '1757894400000',
  'isTimeAnnounced': True,
  'stateTitle': 'ENG Won',
  'team1_overs': 49.6,
  'team2_overs': 20.5},
 {'matchId': 131086,
  'seriesId': 10642,
  'seriesName': 'United Arab Emirates T20I Tri-Series 2025',
  'matchDesc': '6th Match',
  'matchFormat': 'T20',
  'startDate': '1757084400000',
  'endDate': '1757097000000',
  'state': 'Complete',
  'status': 'Afghanistan won by 4 runs',
  'team1': {'teamId': 96,
   'teamName': 'Afghanistan',
   'teamSName': 'AFG',
   'imageId': 172188},
  'team2': {'teamId': 7,
   'teamName': 'United Arab Emirates',
   'teamSName': 'UAE',
   'imageId': 172121},
  'venueInfo': {'id': 140,
   'ground': 'Sharjah Cricket Stadium',
   'city': 'Sharjah',
   'timezone': '+04:00',
   'latitude': '25.33095',
   'longitude': '55.420902'},
  'currBatTeamId': 96,
  'seriesStartDt': '1756339200000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'AFG Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 131075,
  'seriesId': 10642,
  'seriesName': 'United Arab Emirates T20I Tri-Series 2025',
  'matchDesc': '5th Match',
  'matchFormat': 'T20',
  'startDate': '1756998000000',
  'endDate': '1757010600000',
  'state': 'Complete',
  'status': 'Pakistan won by 31 runs',
  'team1': {'teamId': 3,
   'teamName': 'Pakistan',
   'teamSName': 'PAK',
   'imageId': 591986},
  'team2': {'teamId': 7,
   'teamName': 'United Arab Emirates',
   'teamSName': 'UAE',
   'imageId': 172121},
  'venueInfo': {'id': 140,
   'ground': 'Sharjah Cricket Stadium',
   'city': 'Sharjah',
   'timezone': '+04:00',
   'latitude': '25.33095',
   'longitude': '55.420902'},
  'currBatTeamId': 3,
  'seriesStartDt': '1756339200000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'PAK Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 131092,
  'seriesId': 10642,
  'seriesName': 'United Arab Emirates T20I Tri-Series 2025',
  'matchDesc': 'Final',
  'matchFormat': 'T20',
  'startDate': '1757257200000',
  'endDate': '1757269800000',
  'state': 'Complete',
  'status': 'Pakistan won by 75 runs',
  'team1': {'teamId': 3,
   'teamName': 'Pakistan',
   'teamSName': 'PAK',
   'imageId': 591986},
  'team2': {'teamId': 96,
   'teamName': 'Afghanistan',
   'teamSName': 'AFG',
   'imageId': 172188},
  'venueInfo': {'id': 140,
   'ground': 'Sharjah Cricket Stadium',
   'city': 'Sharjah',
   'timezone': '+04:00',
   'latitude': '25.33095',
   'longitude': '55.420902'},
  'currBatTeamId': 3,
  'seriesStartDt': '1756339200000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'PAK Won',
  'team1_overs': 19.6,
  'team2_overs': 15.5},
 {'matchId': 128919,
  'seriesId': 7572,
  'seriesName': 'ICC Cricket World Cup League Two 2023-27',
  'matchDesc': '85th Match',
  'matchFormat': 'ODI',
  'startDate': '1757169000000',
  'endDate': '1757197800000',
  'state': 'Abandon',
  'status': 'Match abandoned due to wet outfield (no toss)',
  'team1': {'teamId': 26,
   'teamName': 'Canada',
   'teamSName': 'CAN',
   'imageId': 172140},
  'team2': {'teamId': 23,
   'teamName': 'Scotland',
   'teamSName': 'SCO',
   'imageId': 172137},
  'venueInfo': {'id': 139,
   'ground': 'Maple Leaf North-West Ground',
   'city': 'King City',
   'timezone': '-04:00',
   'latitude': '36.210861',
   'longitude': '-121.126602'},
  'currBatTeamId': None,
  'seriesStartDt': '1707868800000',
  'seriesEndDt': '1806451200000',
  'isTimeAnnounced': True,
  'stateTitle': 'Abandon',
  'team1_overs': None,
  'team2_overs': None},
 {'matchId': 128908,
  'seriesId': 7572,
  'seriesName': 'ICC Cricket World Cup League Two 2023-27',
  'matchDesc': '84th Match',
  'matchFormat': 'ODI',
  'startDate': '1756996200000',
  'endDate': '1757025000000',
  'state': 'Complete',
  'status': 'Scotland won by 55 runs (24 overs game due to rain)',
  'team1': {'teamId': 23,
   'teamName': 'Scotland',
   'teamSName': 'SCO',
   'imageId': 172137},
  'team2': {'teamId': 161,
   'teamName': 'Namibia',
   'teamSName': 'NAM',
   'imageId': 172229},
  'venueInfo': {'id': 139,
   'ground': 'Maple Leaf North-West Ground',
   'city': 'King City',
   'timezone': '-04:00',
   'latitude': '36.210861',
   'longitude': '-121.126602'},
  'currBatTeamId': 23,
  'seriesStartDt': '1707868800000',
  'seriesEndDt': '1806451200000',
  'isTimeAnnounced': True,
  'stateTitle': 'SCO Won',
  'team1_overs': 23.6,
  'team2_overs': 21.2},
 {'matchId': 122973,
  'seriesId': 10267,
  'seriesName': 'Sri Lanka tour of Zimbabwe, 2025',
  'matchDesc': '3rd T20I',
  'matchFormat': 'T20',
  'startDate': '1757244600000',
  'endDate': '1757257200000',
  'state': 'Complete',
  'status': 'Sri Lanka won by 8 wkts',
  'team1': {'teamId': 12,
   'teamName': 'Zimbabwe',
   'teamSName': 'ZIM',
   'imageId': 172127},
  'team2': {'teamId': 5,
   'teamName': 'Sri Lanka',
   'teamSName': 'SL',
   'imageId': 172119},
  'venueInfo': {'id': 69,
   'ground': 'Harare Sports Club',
   'city': 'Harare',
   'timezone': '+02:00',
   'latitude': '-17.814114',
   'longitude': '31.050962'},
  'currBatTeamId': 5,
  'seriesStartDt': '1756339200000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'SL Won',
  'team1_overs': 19.6,
  'team2_overs': 17.4},
 {'matchId': 122968,
  'seriesId': 10267,
  'seriesName': 'Sri Lanka tour of Zimbabwe, 2025',
  'matchDesc': '2nd T20I',
  'matchFormat': 'T20',
  'startDate': '1757158200000',
  'endDate': '1757170800000',
  'state': 'Complete',
  'status': 'Zimbabwe won by 5 wkts',
  'team1': {'teamId': 5,
   'teamName': 'Sri Lanka',
   'teamSName': 'SL',
   'imageId': 172119},
  'team2': {'teamId': 12,
   'teamName': 'Zimbabwe',
   'teamSName': 'ZIM',
   'imageId': 172127},
  'venueInfo': {'id': 69,
   'ground': 'Harare Sports Club',
   'city': 'Harare',
   'timezone': '+02:00',
   'latitude': '-17.814114',
   'longitude': '31.050962'},
  'currBatTeamId': 12,
  'seriesStartDt': '1756339200000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'ZIM Won',
  'team1_overs': 17.4,
  'team2_overs': 14.2},
 {'matchId': 133187,
  'seriesId': 10812,
  'seriesName': 'Sweden tour of Isle Of Man 2025',
  'matchDesc': '4th Match',
  'matchFormat': 'T20',
  'startDate': '1757255400000',
  'endDate': '1757268000000',
  'state': 'Abandon',
  'status': 'Match abandoned without toss',
  'team1': {'teamId': 557,
   'teamName': 'Isle of Man',
   'teamSName': 'IOM',
   'imageId': 172609},
  'team2': {'teamId': 534,
   'teamName': 'Sweden',
   'teamSName': 'SWE',
   'imageId': 248454},
  'venueInfo': {'id': 1438142,
   'ground': 'Cronkbourne Sports and Social Club Ground',
   'city': 'Tromode',
   'timezone': '+01:00',
   'latitude': '54.1692678',
   'longitude': '-4.4754267'},
  'currBatTeamId': None,
  'seriesStartDt': '1757030400000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'Abandon',
  'team1_overs': None,
  'team2_overs': None},
 {'matchId': 133176,
  'seriesId': 10812,
  'seriesName': 'Sweden tour of Isle Of Man 2025',
  'matchDesc': '3rd T20I',
  'matchFormat': 'T20',
  'startDate': '1757239200000',
  'endDate': '1757251800000',
  'state': 'Abandon',
  'status': 'Match abandoned without toss',
  'team1': {'teamId': 557,
   'teamName': 'Isle of Man',
   'teamSName': 'IOM',
   'imageId': 172609},
  'team2': {'teamId': 534,
   'teamName': 'Sweden',
   'teamSName': 'SWE',
   'imageId': 248454},
  'venueInfo': {'id': 1438142,
   'ground': 'Cronkbourne Sports and Social Club Ground',
   'city': 'Tromode',
   'timezone': '+01:00',
   'latitude': '54.1692678',
   'longitude': '-4.4754267'},
  'currBatTeamId': None,
  'seriesStartDt': '1757030400000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'Abandon',
  'team1_overs': None,
  'team2_overs': None},
 {'matchId': 133171,
  'seriesId': 10812,
  'seriesName': 'Sweden tour of Isle Of Man 2025',
  'matchDesc': '2nd T20I',
  'matchFormat': 'T20',
  'startDate': '1757169000000',
  'endDate': '1757181600000',
  'state': 'Complete',
  'status': 'Sweden won by 3 wkts',
  'team1': {'teamId': 557,
   'teamName': 'Isle of Man',
   'teamSName': 'IOM',
   'imageId': 172609},
  'team2': {'teamId': 534,
   'teamName': 'Sweden',
   'teamSName': 'SWE',
   'imageId': 248454},
  'venueInfo': {'id': 1438142,
   'ground': 'Cronkbourne Sports and Social Club Ground',
   'city': 'Tromode',
   'timezone': '+01:00',
   'latitude': '54.1692678',
   'longitude': '-4.4754267'},
  'currBatTeamId': 534,
  'seriesStartDt': '1757030400000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'SWE Won',
  'team1_overs': 19.5,
  'team2_overs': 14.3},
 {'matchId': 133160,
  'seriesId': 10812,
  'seriesName': 'Sweden tour of Isle Of Man 2025',
  'matchDesc': '1st T20I',
  'matchFormat': 'T20',
  'startDate': '1757152800000',
  'endDate': '1757165400000',
  'state': 'Complete',
  'status': 'Sweden won by 10 wkts',
  'team1': {'teamId': 557,
   'teamName': 'Isle of Man',
   'teamSName': 'IOM',
   'imageId': 172609},
  'team2': {'teamId': 534,
   'teamName': 'Sweden',
   'teamSName': 'SWE',
   'imageId': 248454},
  'venueInfo': {'id': 1438142,
   'ground': 'Cronkbourne Sports and Social Club Ground',
   'city': 'Tromode',
   'timezone': '+01:00',
   'latitude': '54.1692678',
   'longitude': '-4.4754267'},
  'currBatTeamId': 534,
  'seriesStartDt': '1757030400000',
  'seriesEndDt': '1757289600000',
  'isTimeAnnounced': True,
  'stateTitle': 'SWE Won',
  'team1_overs': 16.1,
  'team2_overs': 10.5},
 {'matchId': 116765,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '24th Match',
  'matchFormat': 'T20',
  'startDate': '1757257200000',
  'endDate': '1757269800000',
  'state': 'Complete',
  'status': 'Barbados Royals won by 27 runs',
  'team1': {'teamId': 262,
   'teamName': 'Barbados Royals',
   'teamSName': 'BR',
   'imageId': 210485},
  'team2': {'teamId': 263,
   'teamName': 'Saint Lucia Kings',
   'teamSName': 'SLK',
   'imageId': 172316},
  'venueInfo': {'id': 55,
   'ground': 'Kensington Oval',
   'city': 'Bridgetown, Barbados',
   'timezone': '-04:00',
   'latitude': '13.105021',
   'longitude': '-59.62257'},
  'currBatTeamId': 262,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'BR Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 116774,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '25th Match',
  'matchFormat': 'T20',
  'startDate': '1757289600000',
  'endDate': '1757302200000',
  'state': 'Complete',
  'status': 'St Kitts and Nevis Patriots won by 5 runs',
  'team1': {'teamId': 302,
   'teamName': 'St Kitts and Nevis Patriots',
   'teamSName': 'SNP',
   'imageId': 172351},
  'team2': {'teamId': 159,
   'teamName': 'Guyana Amazon Warriors',
   'teamSName': 'GAW',
   'imageId': 172227},
  'venueInfo': {'id': 110,
   'ground': 'Providence Stadium',
   'city': 'Guyana',
   'timezone': '-04:00',
   'latitude': '41.823872',
   'longitude': '-71.411987'},
  'currBatTeamId': 302,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'SNP Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 116759,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '23rd Match',
  'matchFormat': 'T20',
  'startDate': '1757199600000',
  'endDate': '1757212200000',
  'state': 'Complete',
  'status': 'Guyana Amazon Warriors won by 3 wkts',
  'team1': {'teamId': 271,
   'teamName': 'Trinbago Knight Riders',
   'teamSName': 'TKR',
   'imageId': 172325},
  'team2': {'teamId': 159,
   'teamName': 'Guyana Amazon Warriors',
   'teamSName': 'GAW',
   'imageId': 172227},
  'venueInfo': {'id': 110,
   'ground': 'Providence Stadium',
   'city': 'Guyana',
   'timezone': '-04:00',
   'latitude': '41.823872',
   'longitude': '-71.411987'},
  'currBatTeamId': 159,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'GAW Won',
  'team1_overs': 19.6,
  'team2_overs': 19.5},
 {'matchId': 116750,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '22nd Match',
  'matchFormat': 'T20',
  'startDate': '1757113200000',
  'endDate': '1757125800000',
  'state': 'Complete',
  'status': 'Antigua and Barbuda Falcons won by 4 wkts',
  'team1': {'teamId': 262,
   'teamName': 'Barbados Royals',
   'teamSName': 'BR',
   'imageId': 210485},
  'team2': {'teamId': 1978,
   'teamName': 'Antigua and Barbuda Falcons',
   'teamSName': 'ABF',
   'imageId': 507236},
  'venueInfo': {'id': 55,
   'ground': 'Kensington Oval',
   'city': 'Bridgetown, Barbados',
   'timezone': '-04:00',
   'latitude': '13.105021',
   'longitude': '-59.62257'},
  'currBatTeamId': 1978,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'ABF Won',
  'team1_overs': 19.6,
  'team2_overs': 19.6},
 {'matchId': 116738,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '20th Match',
  'matchFormat': 'T20',
  'startDate': '1756940400000',
  'endDate': '1756953000000',
  'state': 'Complete',
  'status': 'Saint Lucia Kings won by 7 wkts',
  'team1': {'teamId': 271,
   'teamName': 'Trinbago Knight Riders',
   'teamSName': 'TKR',
   'imageId': 172325},
  'team2': {'teamId': 263,
   'teamName': 'Saint Lucia Kings',
   'teamSName': 'SLK',
   'imageId': 172316},
  'venueInfo': {'id': 500,
   'ground': 'Brian Lara Stadium',
   'city': 'Tarouba, Trinidad',
   'timezone': '-04:00',
   'latitude': '10.295034',
   'longitude': '-61.445609'},
  'currBatTeamId': 263,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'SLK Won',
  'team1_overs': 18.1,
  'team2_overs': 11.1},
 {'matchId': 116741,
  'seriesId': 9575,
  'seriesName': 'Caribbean Premier League 2025',
  'matchDesc': '21st Match',
  'matchFormat': 'T20',
  'startDate': '1757026800000',
  'endDate': '1757039400000',
  'state': 'Complete',
  'status': 'Guyana Amazon Warriors won by 4 wkts',
  'team1': {'teamId': 262,
   'teamName': 'Barbados Royals',
   'teamSName': 'BR',
   'imageId': 210485},
  'team2': {'teamId': 159,
   'teamName': 'Guyana Amazon Warriors',
   'teamSName': 'GAW',
   'imageId': 172227},
  'venueInfo': {'id': 55,
   'ground': 'Kensington Oval',
   'city': 'Bridgetown, Barbados',
   'timezone': '-04:00',
   'latitude': '13.105021',
   'longitude': '-59.62257'},
  'currBatTeamId': 159,
  'seriesStartDt': '1755043200000',
  'seriesEndDt': '1758499200000',
  'isTimeAnnounced': True,
  'stateTitle': 'GAW Won',
  'team1_overs': 19.6,
  'team2_overs': 19.4},
 {'matchId': 111061,
  'seriesId': 9257,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': 'Quarter Final 1',
  'matchFormat': 'T20',
  'startDate': '1756920600000',
  'endDate': '1756933200000',
  'state': 'Complete',
  'status': 'Northamptonshire won by 7 runs (14 Overs game  -  due to rain)',
  'team1': {'teamId': 142,
   'teamName': 'Northamptonshire',
   'teamSName': 'NHNTS',
   'imageId': 172209},
  'team2': {'teamId': 148,
   'teamName': 'Surrey',
   'teamSName': 'SUR',
   'imageId': 172215},
  'venueInfo': {'id': 12,
   'ground': 'Kennington Oval',
   'city': 'London',
   'timezone': '+01:00',
   'latitude': '51.48368',
   'longitude': '-0.114885'},
  'currBatTeamId': 142,
  'seriesStartDt': '1748390400000',
  'seriesEndDt': '1757808000000',
  'isTimeAnnounced': True,
  'stateTitle': 'NHNTS Won',
  'team1_overs': 13.6,
  'team2_overs': 13.6},
 {'matchId': 111081,
  'seriesId': 9257,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': 'Quarter Final 4',
  'matchFormat': 'T20',
  'startDate': '1757179800000',
  'endDate': '1757192400000',
  'state': 'Complete',
  'status': 'Somerset won by 4 wkts',
  'team1': {'teamId': 140,
   'teamName': 'Warwickshire',
   'teamSName': 'WARKS',
   'imageId': 172207},
  'team2': {'teamId': 119,
   'teamName': 'Somerset',
   'teamSName': 'SOM',
   'imageId': 172199},
  'venueInfo': {'id': 223,
   'ground': 'The Cooper Associates County Ground',
   'city': 'Taunton',
   'timezone': '+01:00',
   'latitude': '51.018913',
   'longitude': '3.100894'},
  'currBatTeamId': 119,
  'seriesStartDt': '1748390400000',
  'seriesEndDt': '1757808000000',
  'isTimeAnnounced': True,
  'stateTitle': 'SOM Won',
  'team1_overs': 19.6,
  'team2_overs': 19.5},
 {'matchId': 111073,
  'seriesId': 9257,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': 'Quarter Final 3',
  'matchFormat': 'T20',
  'startDate': '1757165400000',
  'endDate': '1757178000000',
  'state': 'Complete',
  'status': 'Lancashire won by 3 wkts',
  'team1': {'teamId': 150,
   'teamName': 'Kent',
   'teamSName': 'KENT',
   'imageId': 172217},
  'team2': {'teamId': 143,
   'teamName': 'Lancashire',
   'teamSName': 'LANCS',
   'imageId': 172210},
  'venueInfo': {'id': 65,
   'ground': 'Emirates Old Trafford',
   'city': 'Manchester',
   'timezone': '+01:00',
   'latitude': '53.463066',
   'longitude': '-2.291301'},
  'currBatTeamId': 143,
  'seriesStartDt': '1748390400000',
  'seriesEndDt': '1757808000000',
  'isTimeAnnounced': True,
  'stateTitle': 'LANCS Won',
  'team1_overs': 19.6,
  'team2_overs': 18.3},
 {'matchId': 111069,
  'seriesId': 9257,
  'seriesName': 'T20 Blast 2025',
  'matchDesc': 'Quarter Final 2',
  'matchFormat': 'T20',
  'startDate': '1757093400000',
  'endDate': '1757106000000',
  'state': 'Complete',
  'status': 'Hampshire won by 26 runs',
  'team1': {'teamId': 153,
   'teamName': 'Hampshire',
   'teamSName': 'HAM',
   'imageId': 172220},

In [ ]:
df_recent_matches = pd.DataFrame(recent_match_data)
display(df_recent_matches.head())

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,team2,venueInfo,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,1757428200000,1757440800000,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 8, 'teamName': 'Hong Kong', 'teamSN...","{'id': 94, 'ground': 'Sheikh Zayed Stadium', '...",96.0,1757289600000,1759104000000,True,AFG Won,19.6,19.6
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,1756987200000,1757016000000,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 19, 'ground': 'Lord's', 'city': 'London...",11.0,1756684800000,1757894400000,True,RSA Won,49.6,49.6
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,1757239200000,1757268000000,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'teamId': 11, 'teamName': 'South Africa', 'te...","{'id': 21, 'ground': 'The Rose Bowl', 'city': ...",9.0,1756684800000,1757894400000,True,ENG Won,49.6,20.5
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,1757084400000,1757097000000,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",96.0,1756339200000,1757289600000,True,AFG Won,19.6,19.6
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,1756998000000,1757010600000,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",3.0,1756339200000,1757289600000,True,PAK Won,19.6,19.6

In [ ]:
df_recent_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          61 non-null     int64
 1   seriesId         61 non-null     int64
 2   seriesName       61 non-null     object
 3   matchDesc        61 non-null     object
 4   matchFormat      61 non-null     object
 5   startDate        61 non-null     object
 6   endDate          61 non-null     object
 7   state            61 non-null     object
 8   status           61 non-null     object
 9   team1            61 non-null     object
 10  team2            61 non-null     object
 11  venueInfo        61 non-null     object
 12  currBatTeamId    56 non-null     float64
 13  seriesStartDt    61 non-null     object
 14  seriesEndDt      61 non-null     object
 15  isTimeAnnounced  61 non-null     bool
 16  stateTitle       61 non-null     object
 17  team1_overs      58 non-null     float64
 18  team2_overs      58 non-null     float64
dtypes: bool(1), float64(3), int64(2), object(13)
memory usage: 8.8+ KB

In [ ]:
# change 1757428200000	 to perfect date time
df_recent_matches['seriesStartDt'] = pd.to_datetime(df_recent_matches['seriesStartDt'], unit='ms')

In [ ]:
df_recent_matches['seriesEndDt'] = pd.to_datetime(df_recent_matches['seriesEndDt'], unit='ms')

In [ ]:
# same goes to start date and end date
df_recent_matches['startDate'] = pd.to_datetime(df_recent_matches['startDate'], unit='ms')

In [ ]:
df_recent_matches['endDate']= pd.to_datetime(df_recent_matches['endDate'], unit='ms')

In [ ]:
# unique value of team 1
df_recent_matches['team1'].apply(lambda x: x.get('teamName')).unique()

array(['Afghanistan', 'South Africa', 'England', 'Pakistan', 'Canada',
       'Scotland', 'Zimbabwe', 'Sri Lanka', 'Isle of Man',
       'Barbados Royals', 'St Kitts and Nevis Patriots',
       'Trinbago Knight Riders', 'Northamptonshire', 'Warwickshire',
       'Kent', 'Hampshire', 'Meerut Mavericks', 'Lucknow Falcons',
       'Kochi Blue Tigers', 'Aries Kollam Sailors', 'Thrissur Titans',
       'Calicut Globstars', 'Alleppey Ripples', 'South Zone', 'West Zone',
       'New Zealand A', 'Czech Republic Women', 'Estonia Women',
       'Jersey Women', 'Brazil Women', 'Japan Women', 'Namibia Women',
       'Rwanda Women', 'Nigeria Women', 'Kenya Women', 'Tanzania Women',
       'Uganda Women', 'Papua New Guinea Women', 'Cook Islands Women',
       'Indonesia Women', 'Vanuatu Women', 'Philippines Women',
       'Guyana Amazon Warriors Women'], dtype=object)

In [ ]:
df_recent_matches

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,team2,venueInfo,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 8, 'teamName': 'Hong Kong', 'teamSN...","{'id': 94, 'ground': 'Sheikh Zayed Stadium', '...",96.0,2025-09-08,2025-09-29,True,AFG Won,19.6,19.6
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 19, 'ground': 'Lord's', 'city': 'London...",11.0,2025-09-01,2025-09-15,True,RSA Won,49.6,49.6
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'teamId': 11, 'teamName': 'South Africa', 'te...","{'id': 21, 'ground': 'The Rose Bowl', 'city': ...",9.0,2025-09-01,2025-09-15,True,ENG Won,49.6,20.5
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",96.0,2025-08-28,2025-09-08,True,AFG Won,19.6,19.6
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",3.0,2025-08-28,2025-09-08,True,PAK Won,19.6,19.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,"{'teamId': 506, 'teamName': 'Vanuatu Women', '...","{'teamId': 484, 'teamName': 'Indonesia Women',...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",506.0,2025-09-08,2025-09-16,True,VANW Won,19.6,19.6
57,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,"{'teamId': 1514, 'teamName': 'Philippines Wome...","{'teamId': 482, 'teamName': 'Samoa Women', 'te...","{'id': 1438123, 'ground': 'Albert Park 2', 'ci...",482.0,2025-09-08,2025-09-16,True,WSMW Won,17.3,6.2
58,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,"{'teamId': 1754, 'teamName': 'Cook Islands Wom...","{'teamId': 1181, 'teamName': 'Fiji Women', 'te...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",1181.0,2025-09-08,2025-09-16,True,FIJIW Won,19.6,17.2
59,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,"{'teamId': 1144, 'teamName': 'Guyana Amazon Wa...","{'teamId': 1139, 'teamName': 'Trinbago Knight ...","{'id': 110, 'ground': 'Providence Stadium', 'c...",1144.0,2025-09-05,2025-09-18,True,GAWW Won,19.6,19.6
60,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),"{'teamId': 1144, 'teamName': 'Guyana Amazon Wa...","{'teamId': 1137, 'teamName': 'Barbados Royals ...","{'id': 110, 'ground': 'Providence Stadium', 'c...",1137.0,2025-09-05,2025-09-18,True,BRW Won,19.6,17.2

In [ ]:
df_recent_matches['venue_id'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('id'))
df_recent_matches['ground'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('ground'))
df_recent_matches['city'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('city'))
df_recent_matches['timezone'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('timezone'))
df_recent_matches['latitude'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('latitude'))
df_recent_matches['longitude'] = df_recent_matches['venueInfo'].apply(lambda x: x.get('longitude'))

# Display the updated DataFrame to verify the new columns
display(df_recent_matches.head())

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,...,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...",...,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...",...,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...",...,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902

In [ ]:
df_recent_matches['team1_id'] = df_recent_matches['team1'].apply(lambda x: x.get('teamId'))
df_recent_matches['team1_name'] = df_recent_matches['team1'].apply(lambda x: x.get('teamName'))
df_recent_matches['team1_sname'] = df_recent_matches['team1'].apply(lambda x: x.get('teamSName'))
df_recent_matches['team1_image_id'] = df_recent_matches['team1'].apply(lambda x: x.get('imageId'))

# Display the updated DataFrame to verify the new columns
display(df_recent_matches.head())

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,...,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,2025-09-08,2025-09-29,True,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...",...,2025-09-01,2025-09-15,True,RSA Won,49.6,49.6,11,South Africa,RSA,172126
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...",...,2025-09-01,2025-09-15,True,ENG Won,49.6,20.5,9,England,ENG,172123
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,2025-08-28,2025-09-08,True,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...",...,2025-08-28,2025-09-08,True,PAK Won,19.6,19.6,3,Pakistan,PAK,591986

In [ ]:
df_recent_matches['team2_id'] = df_recent_matches['team2'].apply(lambda x: x.get('teamId'))
df_recent_matches['team2_name'] = df_recent_matches['team2'].apply(lambda x: x.get('teamName'))
df_recent_matches['team2_sname'] = df_recent_matches['team2'].apply(lambda x: x.get('teamSName'))
df_recent_matches['team2_image_id'] = df_recent_matches['team2'].apply(lambda x: x.get('imageId'))

# Display the updated DataFrame to verify the new columns
display(df_recent_matches.head())

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,...,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...",...,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...",...,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...",...,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...",...,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121

In [ ]:
df_recent_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          61 non-null     int64
 1   seriesId         61 non-null     int64
 2   seriesName       61 non-null     object
 3   matchDesc        61 non-null     object
 4   matchFormat      61 non-null     object
 5   startDate        61 non-null     datetime64[ns]
 6   endDate          61 non-null     datetime64[ns]
 7   state            61 non-null     object
 8   status           61 non-null     object
 9   currBatTeamId    56 non-null     float64
 10  seriesStartDt    61 non-null     datetime64[ns]
 11  seriesEndDt      61 non-null     datetime64[ns]
 12  isTimeAnnounced  61 non-null     bool
 13  stateTitle       61 non-null     object
 14  team1_overs      58 non-null     float64
 15  team2_overs      58 non-null     float64
 16  team1_id         61 non-null     int64
 17  team1_name       61 non-null     object
 18  team1_sname      61 non-null     object
 19  team1_image_id   61 non-null     int64
 20  team2_id         61 non-null     int64
 21  team2_name       61 non-null     object
 22  team2_sname      61 non-null     object
 23  team2_image_id   61 non-null     int64
 24  venue_id         61 non-null     int64
 25  ground           61 non-null     object
 26  city             61 non-null     object
 27  timezone         61 non-null     object
 28  latitude         61 non-null     object
 29  longitude        61 non-null     object
dtypes: bool(1), datetime64[ns](4), float64(3), int64(7), object(15)
memory usage: 14.0+ KB

In [ ]:
# drop column team1 team2,venueInfo
df_recent_matches.drop(columns=['team1', 'team2', 'venueInfo'], inplace=True)

In [ ]:
#set full column view
pd.set_option('display.max_columns', None)

In [ ]:
df_recent_matches

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08,2025-09-29,True,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01,2025-09-15,True,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01,2025-09-15,True,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,96.0,2025-08-28,2025-09-08,True,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,3.0,2025-08-28,2025-09-08,True,PAK Won,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,506.0,2025-09-08,2025-09-16,True,VANW Won,19.6,19.6,506,Vanuatu Women,VANW,172555,484,Indonesia Women,IDNW,172532,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
57,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,482.0,2025-09-08,2025-09-16,True,WSMW Won,17.3,6.2,1514,Philippines Women,PHIW,307469,482,Samoa Women,WSMW,172530,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
58,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,1181.0,2025-09-08,2025-09-16,True,FIJIW Won,19.6,17.2,1754,Cook Islands Women,CISW,341074,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
59,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,1144.0,2025-09-05,2025-09-18,True,GAWW Won,19.6,19.6,1144,Guyana Amazon Warriors Women,GAWW,241607,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
60,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),1137.0,2025-09-05,2025-09-18,True,BRW Won,19.6,17.2,1144,Guyana Amazon Warriors Women,GAWW,241607,1137,Barbados Royals Women,BRW,241608,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987

In [ ]:
# nan value show
df_recent_matches.isna().sum()

matchId            0
seriesId           0
seriesName         0
matchDesc          0
matchFormat        0
startDate          0
endDate            0
state              0
status             0
currBatTeamId      0
seriesStartDt      0
seriesEndDt        0
isTimeAnnounced    0
stateTitle         0
team1_overs        0
team2_overs        0
team1_id           0
team1_name         0
team1_sname        0
team1_image_id     0
team2_id           0
team2_name         0
team2_sname        0
team2_image_id     0
venue_id           0
ground             0
city               0
timezone           0
latitude           0
longitude          0
dtype: int64

In [ ]:
# fill nan value with mode
df_recent_matches['team1_overs'].fillna(df_recent_matches['team1_overs'].mode()[0], inplace=True)
df_recent_matches['currBatTeamId'].fillna(df_recent_matches['currBatTeamId'].mode()[0], inplace=True)
df_recent_matches['team2_overs'].fillna(df_recent_matches['team2_overs'].mode()[0], inplace=True)

In [ ]:
df_recent_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          61 non-null     int64
 1   seriesId         61 non-null     int64
 2   seriesName       61 non-null     object
 3   matchDesc        61 non-null     object
 4   matchFormat      61 non-null     object
 5   startDate        61 non-null     datetime64[ns]
 6   endDate          61 non-null     datetime64[ns]
 7   state            61 non-null     object
 8   status           61 non-null     object
 9   currBatTeamId    61 non-null     float64
 10  seriesStartDt    61 non-null     datetime64[ns]
 11  seriesEndDt      61 non-null     datetime64[ns]
 12  isTimeAnnounced  61 non-null     bool
 13  stateTitle       61 non-null     object
 14  team1_overs      61 non-null     float64
 15  team2_overs      61 non-null     float64
 16  team1_id         61 non-null     int64
 17  team1_name       61 non-null     object
 18  team1_sname      61 non-null     object
 19  team1_image_id   61 non-null     int64
 20  team2_id         61 non-null     int64
 21  team2_name       61 non-null     object
 22  team2_sname      61 non-null     object
 23  team2_image_id   61 non-null     int64
 24  venue_id         61 non-null     int64
 25  ground           61 non-null     object
 26  city             61 non-null     object
 27  timezone         61 non-null     object
 28  latitude         61 non-null     object
 29  longitude        61 non-null     object
dtypes: bool(1), datetime64[ns](4), float64(3), int64(7), object(15)
memory usage: 14.0+ KB

In [ ]:
# save this data to db
df_recent_matches.to_sql('recent_matches', conn, if_exists='replace', index=False)

61

In [ ]:
# verify
pd.read_sql('SELECT * FROM recent_matches', conn)

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
1,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
2,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
3,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,96.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
4,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,19.6,506,Vanuatu Women,VANW,172555,484,Indonesia Women,IDNW,172532,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
57,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,482.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,WSMW Won,17.3,6.2,1514,Philippines Women,PHIW,307469,482,Samoa Women,WSMW,172530,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
58,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,1181.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,FIJIW Won,19.6,17.2,1754,Cook Islands Women,CISW,341074,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
59,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,1144.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,GAWW Won,19.6,19.6,1144,Guyana Amazon Warriors Women,GAWW,241607,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
60,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,17.2,1144,Guyana Amazon Warriors Women,GAWW,241607,1137,Barbados Royals Women,BRW,241608,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987

In [ ]:
# in live match db show table

In [ ]:
# Show tables in the database
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Tables in the database:")
display(tables)

Tables in the database:

               name
0      Live_matches
1  upcoming_matches
2    recent_matches

In [ ]:
%%writefile live_match_page.py
import streamlit as st
import requests
import pandas as pd
import time

Writing live_match_page.py

**Reasoning**:
Import the necessary libraries for the Streamlit application.

In [ ]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.49.1-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.3.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.49.1-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 92.0 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 104.6 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.49.1

In [ ]:
import streamlit as st
import requests
import pandas as pd

## Define api endpoint and headers

### Subtask:
Define the URL for fetching live match data and the headers including the API key within the `live_match_page.py` file.

**Reasoning**:
Define the API endpoint URL and headers for fetching live match data.

In [ ]:
url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
    "x-rapidapi-key": "7cd1451496msh26d2809dcb7535ap12515bjsn5b15e7be8226", # Replace with your actual API key
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

## Fetch live match data

### Subtask:
Create a function to fetch live match data from the Cricbuzz API. Implement a caching mechanism with a time-to-live (TTL) to avoid making excessive API requests and respect the user's request limit.

**Reasoning**:
Define a function to fetch live match data from the Cricbuzz API with caching using the `@st.cache_data` decorator.

In [ ]:
@st.cache_data(ttl=60)
def fetch_live_matches(url, headers):
    """Fetches live match data from the Cricbuzz API with caching."""
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.RequestException as e:
        st.error(f"Error fetching live match data: {e}")
        return None

2025-09-10 17:21:06.266 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

## Process and display data

### Subtask:
Create a function to process the fetched data and display relevant information in the Streamlit app. This will involve iterating through the match data and presenting details like series name, match description, teams, status, and scores.

**Reasoning**:
Define a function to process and display the fetched live match data, iterating through the nested structure and extracting relevant details.

In [ ]:
def display_live_matches(data):
    """Processes and displays live match data in the Streamlit app."""
    if data and 'typeMatches' in data:
        for match_type_entry in data['typeMatches']:
            if 'seriesMatches' in match_type_entry:
                for series_match_entry in match_type_entry['seriesMatches']:
                    if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
                        for match in series_match_entry['seriesAdWrapper']['matches']:
                            if 'matchInfo' in match:
                                match_info = match['matchInfo']
                                st.subheader(f"{match_info.get('seriesName')} - {match_info.get('matchDesc')}")
                                st.write(f"**Format:** {match_info.get('matchFormat')}")
                                st.write(f"**State:** {match_info.get('state')}")
                                st.write(f"**Status:** {match_info.get('status')}")

                                team1_name = match_info.get('team1', {}).get('teamName')
                                team2_name = match_info.get('team2', {}).get('teamName')

                                if team1_name and team2_name:
                                    st.write(f"**Teams:** {team1_name} vs {team2_name}")
                                elif team1_name:
                                    st.write(f"**Team 1:** {team1_name}")
                                elif team2_name:
                                     st.write(f"**Team 2:** {team2_name}")


                                if 'matchScore' in match:
                                    st.write("**Score:**")
                                    if 'team1Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team1Score']:
                                        score1 = match['matchScore']['team1Score']['inngs1']
                                        st.write(f"  {team1_name}: {score1.get('runs', 'N/A')}/{score1.get('wickets', 'N/A')} ({score1.get('overs', 'N/A')} Overs)")
                                    if 'team2Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team2Score']:
                                        score2 = match['matchScore']['team2Score']['inngs1']
                                        st.write(f"  {team2_name}: {score2.get('runs', 'N/A')}/{score2.get('wickets', 'N/A')} ({score2.get('overs', 'N/A')} Overs)")
                                st.markdown("---")
    else:
        st.write("No live match data available.")

## Implement auto-refresh

### Subtask:
Use Streamlit's capabilities to automatically re-run the script periodically to fetch and display updated live data.

**Reasoning**:
Add the Streamlit page title, call the functions to fetch and display data, and implement the auto-refresh mechanism.

In [ ]:
import time

st.title("Live Cricket Matches")

# Fetch and display live matches
live_matches_data = fetch_live_matches(url, headers)
display_live_matches(live_matches_data)

# Auto-refresh mechanism (every 60 seconds)
time.sleep(60)
st.rerun()

2025-09-10 17:22:17.411 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.503
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2025-09-10 17:22:17.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.507 No runtime found, using MemoryCacheStorageManager
2025-09-10 17:22:17.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.905 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.927 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.927 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.929 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.929 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.931 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.936 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.938 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.942 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.944 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.950 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.994 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:17.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:18.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:18.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-09-10 17:22:18.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
%%writefile -a live_match_page.py

url_live = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"
url_upcoming = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/upcoming"
url_recent = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
    "x-rapidapi-key": "7cd1451496msh26d2809dcb7535ap12515bjsn5b15e7be8226", # Replace with your actual API key
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

Appending to live_match_page.py

In [ ]:
%%writefile -a live_match_page.py

import time

st.title("Cricket Match Updates")

# Add buttons for filtering
if st.button("Show Live Matches"):
    # Fetch live matches and display
    live_matches_data = fetch_live_matches(url_live, headers)
    display_live_matches(live_matches_data)

if st.button("Show Recent Matches"):
    # Fetch recent matches, process, and display
    recent_matches_data_raw = fetch_recent_matches(url_recent, headers)
    df_recent_matches = process_recent_matches(recent_matches_data_raw)
    display_recent_matches(df_recent_matches)

if st.button("Show Upcoming Matches"):
    # Fetch upcoming matches and display
    upcoming_matches_data = fetch_upcoming_matches(url_upcoming, headers)
    display_upcoming_matches(upcoming_matches_data)

# Auto-refresh mechanism (every 60 seconds) - applies to the whole app
time.sleep(60)
st.rerun()

Appending to live_match_page.py

In [ ]:
%%writefile -a live_match_page.py

def display_live_matches(data):
    """Processes and displays live match data in the Streamlit app."""
    st.header("Live Matches")
    if data and 'typeMatches' in data:
        for match_type_entry in data['typeMatches']:
            if 'seriesMatches' in match_type_entry:
                for series_match_entry in match_type_entry['seriesMatches']:
                    if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
                        for match in series_match_entry['seriesAdWrapper']['matches']:
                            if 'matchInfo' in match:
                                match_info = match['matchInfo']
                                st.subheader(f"{match_info.get('seriesName', 'N/A')} - {match_info.get('matchDesc', 'N/A')}")
                                st.write(f"**Format:** {match_info.get('matchFormat', 'N/A')}")
                                st.write(f"**State:** {match_info.get('state', 'N/A')}")
                                st.write(f"**Status:** {match_info.get('status', 'N/A')}")

                                team1_name = match_info.get('team1', {}).get('teamName')
                                team2_name = match_info.get('team2', {}).get('teamName')

                                if team1_name and team2_name:
                                    st.write(f"**Teams:** {team1_name} vs {team2_name}")
                                elif team1_name:
                                    st.write(f"**Team 1:** {team1_name}")
                                elif team2_name:
                                     st.write(f"**Team 2:** {team2_name}")

                                if 'matchScore' in match:
                                    st.write("**Score:**")
                                    if 'team1Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team1Score']:
                                        score1 = match['matchScore']['team1Score']['inngs1']
                                        st.write(f"  {team1_name}: {score1.get('runs', 'N/A')}/{score1.get('wickets', 'N/A')} ({score1.get('overs', 'N/A')} Overs)")
                                    if 'team2Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team2Score']:
                                        score2 = match['matchScore']['team2Score']['inngs1']
                                        st.write(f"  {team2_name}: {score2.get('runs', 'N/A')}/{score2.get('wickets', 'N/A')} ({score2.get('overs', 'N/A')} Overs)")
                                st.markdown("---")
    else:
        st.info("No live match data available at the moment.")

def display_upcoming_matches(data):
    """Processes and displays upcoming match data in the Streamlit app."""
    st.header("Upcoming Matches")
    if data and 'typeMatches' in data:
        for match_type_entry in data['typeMatches']:
            if 'seriesMatches' in match_type_entry:
                for series_match_entry in match_type_entry['seriesMatches']:
                    if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
                        for match in series_match_entry['seriesAdWrapper']['matches']:
                            if 'matchInfo' in match:
                                match_info = match['matchInfo']
                                st.subheader(f"{match_info.get('seriesName', 'N/A')} - {match_info.get('matchDesc', 'N/A')}")
                                st.write(f"**Format:** {match_info.get('matchFormat', 'N/A')}")
                                st.write(f"**State:** {match_info.get('state', 'N/A')}")
                                st.write(f"**Status:** {match_info.get('status', 'N/A')}")
                                team1_name = match_info.get('team1', {}).get('teamName')
                                team2_name = match_info.get('team2', {}).get('teamName')

                                if team1_name and team2_name:
                                    st.write(f"**Teams:** {team1_name} vs {team2_name}")
                                elif team1_name:
                                    st.write(f"**Team 1:** {team1_name}")
                                elif team2_name:
                                     st.write(f"**Team 2:** {team2_name}")
                                st.markdown("---")
    else:
        st.info("No upcoming match data available at the moment.")

def display_recent_matches(df):
    """Displays recent match data from a DataFrame in the Streamlit app."""
    st.header("Recent Matches")
    if not df.empty:
        st.dataframe(df)
    else:
        st.info("No recent match data available.")

Appending to live_match_page.py

In [ ]:
%%writefile -a live_match_page.py

def process_recent_matches(data):
    """Processes recent match data to extract team and venue details."""
    recent_match_data = []
    if data and 'typeMatches' in data:
        for match_type_entry in data['typeMatches']:
            if 'seriesMatches' in match_type_entry:
                for series_match_entry in match_type_entry['seriesMatches']: # Corrected line
                    if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
                        for match in series_match_entry['seriesAdWrapper']['matches']:
                            if 'matchInfo' in match:
                                match_info = match['matchInfo']
                                extracted_details = {
                                    'matchId': match_info.get('matchId'),
                                    'seriesId': match_info.get('seriesId'),
                                    'seriesName': match_info.get('seriesName'),
                                    'matchDesc': match_info.get('matchDesc'),
                                    'matchFormat': match_info.get('matchFormat'),
                                    'startDate': match_info.get('startDate'),
                                    'endDate': match_info.get('endDate'),
                                    'state': match_info.get('state'),
                                    'status': match_info.get('status'),
                                    'currBatTeamId': match_info.get('currBatTeamId'),
                                    'seriesStartDt': match_info.get('seriesStartDt'),
                                    'seriesEndDt': match_info.get('seriesEndDt'),
                                    'isTimeAnnounced': match_info.get('isTimeAnnounced'),
                                    'stateTitle': match_info.get('stateTitle')
                                }
                                # Extract team details
                                if 'team1' in match_info:
                                    extracted_details['team1_id'] = match_info['team1'].get('teamId')
                                    extracted_details['team1_name'] = match_info['team1'].get('teamName')
                                    extracted_details['team1_sname'] = match_info['team1'].get('teamSName')
                                    extracted_details['team1_image_id'] = match_info['team1'].get('imageId')
                                else:
                                    extracted_details['team1_id'] = None
                                    extracted_details['team1_name'] = None
                                    extracted_details['team1_sname'] = None
                                    extracted_details['team1_image_id'] = None

                                if 'team2' in match_info:
                                    extracted_details['team2_id'] = match_info['team2'].get('teamId')
                                    extracted_details['team2_name'] = match_info['team2'].get('teamName')
                                    extracted_details['team2_sname'] = match_info['team2'].get('teamSName')
                                    extracted_details['team2_image_id'] = match_info['team2'].get('imageId')
                                else:
                                    extracted_details['team2_id'] = None
                                    extracted_details['team2_name'] = None
                                    extracted_details['team2_sname'] = None
                                    extracted_details['team2_image_id'] = None

                                # Extract venue details
                                if 'venueInfo' in match_info:
                                    extracted_details['venue_id'] = match_info['venueInfo'].get('id')
                                    extracted_details['ground'] = match_info['venueInfo'].get('ground')
                                    extracted_details['city'] = match_info['venueInfo'].get('city')
                                    extracted_details['timezone'] = match_info['venueInfo'].get('timezone')
                                    extracted_details['latitude'] = match_info['venueInfo'].get('latitude')
                                    extracted_details['longitude'] = match_info['venueInfo'].get('longitude')
                                else:
                                    extracted_details['venue_id'] = None
                                    extracted_details['ground'] = None
                                    extracted_details['city'] = None
                                    extracted_details['timezone'] = None
                                    extracted_details['latitude'] = None
                                    extracted_details['longitude'] = None

                                # Extract overs from matchScore if available
                                if 'matchScore' in match:
                                    if 'team1Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team1Score']:
                                        extracted_details['team1_overs'] = match['matchScore']['team1Score']['inngs1'].get('overs')
                                    else:
                                        extracted_details['team1_overs'] = None

                                    if 'team2Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team2Score']:
                                        extracted_details['team2_overs'] = match['matchScore']['team2Score']['inngs1'].get('overs')
                                    else:
                                        extracted_details['team2_overs'] = None
                                else:
                                    extracted_details['team1_overs'] = None
                                    extracted_details['team2_overs'] = None

                                recent_match_data.append(extracted_details)

    df_recent_matches = pd.DataFrame(recent_match_data)

    # Convert date columns to datetime objects
    date_cols = ['startDate', 'endDate', 'seriesStartDt', 'seriesEndDt']
    for col in date_cols:
        if col in df_recent_matches.columns:
            df_recent_matches[col] = pd.to_datetime(df_recent_matches[col], unit='ms', errors='coerce')

    # Fill NaN values in overs and currBatTeamId columns
    if 'team1_overs' in df_recent_matches.columns:
        df_recent_matches['team1_overs'].fillna(df_recent_matches['team1_overs'].mode()[0] if not df_recent_matches['team1_overs'].empty else 0, inplace=True)
    if 'team2_overs' in df_recent_matches.columns:
        df_recent_matches['team2_overs'].fillna(df_recent_matches['team2_overs'].mode()[0] if not df_recent_matches['team2_overs'].empty else 0, inplace=True)
    if 'currBatTeamId' in df_recent_matches.columns:
        df_recent_matches['currBatTeamId'].fillna(df_recent_matches['currBatTeamId'].mode()[0] if not df_recent_matches['currBatTeamId'].empty else 0, inplace=True)


    return df_recent_matches

Appending to live_match_page.py

In [ ]:
%%writefile -a live_match_page.py

@st.cache_data(ttl=60)  # Cache for 60 seconds
def fetch_live_matches(url, headers):
    """Fetches live match data from the Cricbuzz API with caching."""
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.RequestException as e:
        st.error(f"Error fetching live match data: {e}")
        return None

@st.cache_data(ttl=300) # Cache for 5 minutes (upcoming matches change less frequently)
def fetch_upcoming_matches(url, headers):
    """Fetches upcoming match data from the Cricbuzz API with caching."""
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        st.error(f"Error fetching upcoming match data: {e}")
        return None

@st.cache_data(ttl=300) # Cache for 5 minutes (recent matches change less frequently)
def fetch_recent_matches(url, headers):
    """Fetches recent match data from the Cricbuzz API with caching."""
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        st.error(f"Error fetching recent match data: {e}")
        return None

Appending to live_match_page.py

In [ ]:
# show live match db table
tables

               name
0      Live_matches
1  upcoming_matches
2    recent_matches

In [ ]:
# import sql liberiry
import sqlite3 as sql
from sqlalchemy import create_engine

In [ ]:
# fetch match list data
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
response = requests.get(url, headers=headers)
data = response.json()
print(data.keys())

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matches': [{'matchInfo': {'matchId': 130019, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '2nd Match, Group A', 'matchFormat': 'T20', 'startDate': '1757514600000', 'endDate': '1757527200000', 'state': 'Complete', 'status': 'India won by 9 wkts', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 719031}, 'venueInfo': {'id': 153, 'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '+04:00', 'latitude': '25.046842', 'longitude': '55.218969'}, 'currBatTeamId': 2, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 57, 'wickets': 10, 'overs': 13.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 60, 'wickets': 1, 'overs': 4.3}}}}, {'matchInfo': {'matchId': 130008, 'seriesId': 10587, 'seriesName': 'Asia Cup 2025', 'matchDesc': '1st Match, Group B', 'matchFormat': 'T20', 'startDate': '1757428200000', 'endDate': '1757440800000', 'state': 'Complete', 'status': 'Afghanistan won by 94 runs', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'team2': {'teamId': 8, 'teamName': 'Hong Kong', 'teamSName': 'HK', 'imageId': 172122}, 'venueInfo': {'id': 94, 'ground': 'Sheikh Zayed Stadium', 'city': 'Abu Dhabi', 'timezone': '+04:00', 'latitude': '24.416138', 'longitude': '54.453566'}, 'currBatTeamId': 96, 'seriesStartDt': '1757289600000', 'seriesEndDt': '1759104000000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 188, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 94, 'wickets': 9, 'overs': 19.6}}}}], 'isLiveStreamEnabled': True}}, {'seriesAdWrapper': {'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matches': [{'matchInfo': {'matchId': 105802, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757525400000', 'endDate': '1757538000000', 'state': 'Complete', 'status': 'South Africa won by 14 runs (DLS Method)', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'venueInfo': {'id': 62, 'ground': 'Sophia Gardens', 'city': 'Cardiff', 'timezone': '+01:00', 'latitude': '51.484257', 'longitude': '-3.189187'}, 'currBatTeamId': 11, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 97, 'wickets': 5, 'overs': 7.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 54, 'wickets': 5, 'overs': 4.6}}}}, {'matchInfo': {'matchId': 105794, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1757239200000', 'endDate': '1757268000000', 'state': 'Complete', 'status': 'England won by 342 runs', 'team1': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'venueInfo': {'id': 21, 'ground': 'The Rose Bowl', 'city': 'Southampton', 'timezone': '+01:00', 'latitude': '50.924131', 'longitude': '-1.322163'}, 'currBatTeamId': 9, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 414, 'wickets': 5, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 72, 'wickets': 10, 'overs': 20.5}}}}, {'matchInfo': {'matchId': 105788, 'seriesId': 8788, 'seriesName': 'South Africa tour of England, 2025', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1756987200000', 'endDate': '1757016000000', 'state': 'Complete', 'status': 'South Africa won by 5 runs', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 172126}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 172123}, 'venueInfo': {'id': 19, 'ground': "Lord's", 'city': 'London', 'timezone': '+01:00', 'latitude': '51.529488', 'longitude': '-0.172926'}, 'currBatTeamId': 11, 'seriesStartDt': '1756684800000', 'seriesEndDt': '1757894400000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 330, 'wickets': 8, 'overs': 49.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 325, 'wickets': 9, 'overs': 49.6}}}}], 'isLiveStreamEnabled': True}}, {'seriesAdWrapper': {'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matches': [{'matchInfo': {'matchId': 131075, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1756998000000', 'endDate': '1757010600000', 'state': 'Complete', 'status': 'Pakistan won by 31 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 3, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 171, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 140, 'wickets': 7, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 131092, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': 'Final', 'matchFormat': 'T20', 'startDate': '1757257200000', 'endDate': '1757269800000', 'state': 'Complete', 'status': 'Pakistan won by 75 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 591986}, 'team2': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 3, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 141, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 66, 'wickets': 10, 'overs': 15.5}}}}, {'matchInfo': {'matchId': 131086, 'seriesId': 10642, 'seriesName': 'United Arab Emirates T20I Tri-Series 2025', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1757084400000', 'endDate': '1757097000000', 'state': 'Complete', 'status': 'Afghanistan won by 4 runs', 'team1': {'teamId': 96, 'teamName': 'Afghanistan', 'teamSName': 'AFG', 'imageId': 172188}, 'team2': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 172121}, 'venueInfo': {'id': 140, 'ground': 'Sharjah Cricket Stadium', 'city': 'Sharjah', 'timezone': '+04:00', 'latitude': '25.33095', 'longitude': '55.420902'}, 'currBatTeamId': 96, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'AFG Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 170, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 5, 'overs': 19.6}}}}]}}, {'seriesAdWrapper': {'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matches': [{'matchInfo': {'matchId': 128919, 'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matchDesc': '85th Match', 'matchFormat': 'ODI', 'startDate': '1757169000000', 'endDate': '1757197800000', 'state': 'Abandon', 'status': 'Match abandoned due to wet outfield (no toss)', 'team1': {'teamId': 26, 'teamName': 'Canada', 'teamSName': 'CAN', 'imageId': 172140}, 'team2': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 172137}, 'venueInfo': {'id': 139, 'ground': 'Maple Leaf North-West Ground', 'city': 'King City', 'timezone': '-04:00', 'latitude': '36.210861', 'longitude': '-121.126602'}, 'isTournament': True, 'seriesStartDt': '1707868800000', 'seriesEndDt': '1806451200000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 128908, 'seriesId': 7572, 'seriesName': 'ICC Cricket World Cup League Two 2023-27', 'matchDesc': '84th Match', 'matchFormat': 'ODI', 'startDate': '1756996200000', 'endDate': '1757025000000', 'state': 'Complete', 'status': 'Scotland won by 55 runs (24 overs game due to rain)', 'team1': {'teamId': 23, 'teamName': 'Scotland', 'teamSName': 'SCO', 'imageId': 172137}, 'team2': {'teamId': 161, 'teamName': 'Namibia', 'teamSName': 'NAM', 'imageId': 172229}, 'venueInfo': {'id': 139, 'ground': 'Maple Leaf North-West Ground', 'city': 'King City', 'timezone': '-04:00', 'latitude': '36.210861', 'longitude': '-121.126602'}, 'currBatTeamId': 23, 'seriesStartDt': '1707868800000', 'seriesEndDt': '1806451200000', 'isTimeAnnounced': True, 'stateTitle': 'SCO Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 164, 'wickets': 10, 'overs': 23.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 109, 'wickets': 10, 'overs': 21.2}}}}]}}, {'ad': {'name': 'native_matches', 'layout': 'native_large', 'position': 4}}, {'seriesAdWrapper': {'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matches': [{'matchInfo': {'matchId': 122973, 'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757244600000', 'endDate': '1757257200000', 'state': 'Complete', 'status': 'Sri Lanka won by 8 wkts', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'venueInfo': {'id': 69, 'ground': 'Harare Sports Club', 'city': 'Harare', 'timezone': '+02:00', 'latitude': '-17.814114', 'longitude': '31.050962'}, 'currBatTeamId': 5, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SL Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 191, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 193, 'wickets': 2, 'overs': 17.4}}}}, {'matchInfo': {'matchId': 122968, 'seriesId': 10267, 'seriesName': 'Sri Lanka tour of Zimbabwe, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757158200000', 'endDate': '1757170800000', 'state': 'Complete', 'status': 'Zimbabwe won by 5 wkts', 'team1': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 172119}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 172127}, 'venueInfo': {'id': 69, 'ground': 'Harare Sports Club', 'city': 'Harare', 'timezone': '+02:00', 'latitude': '-17.814114', 'longitude': '31.050962'}, 'currBatTeamId': 12, 'seriesStartDt': '1756339200000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'ZIM Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 80, 'wickets': 10, 'overs': 17.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 84, 'wickets': 5, 'overs': 14.2}}}}], 'isLiveStreamEnabled': True}}, {'seriesAdWrapper': {'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matches': [{'matchInfo': {'matchId': 133187, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1757255400000', 'endDate': '1757268000000', 'state': 'Abandon', 'status': 'Match abandoned without toss', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 133176, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1757239200000', 'endDate': '1757251800000', 'state': 'Abandon', 'status': 'Match abandoned without toss', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}}, {'matchInfo': {'matchId': 133171, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1757169000000', 'endDate': '1757181600000', 'state': 'Complete', 'status': 'Sweden won by 3 wkts', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'currBatTeamId': 534, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SWE Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 114, 'wickets': 10, 'overs': 19.5}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 116, 'wickets': 7, 'overs': 14.3}}}}, {'matchInfo': {'matchId': 133160, 'seriesId': 10812, 'seriesName': 'Sweden tour of Isle Of Man 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1757152800000', 'endDate': '1757165400000', 'state': 'Complete', 'status': 'Sweden won by 10 wkts', 'team1': {'teamId': 557, 'teamName': 'Isle of Man', 'teamSName': 'IOM', 'imageId': 172609}, 'team2': {'teamId': 534, 'teamName': 'Sweden', 'teamSName': 'SWE', 'imageId': 248454}, 'venueInfo': {'id': 1438142, 'ground': 'Cronkbourne Sports and Social Club Ground', 'city': 'Tromode', 'timezone': '+01:00', 'latitude': '54.1692678', 'longitude': '-4.4754267'}, 'currBatTeamId': 534, 'seriesStartDt': '1757030400000', 'seriesEndDt': '1757289600000', 'isTimeAnnounced': True, 'stateTitle': 'SWE Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 78, 'wickets': 10, 'overs': 16.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 81, 'overs': 10.5}}}}]}}]}, {'matchType': 'League', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matches': [{'matchInfo': {'matchId': 116765, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '24th Match', 'matchFormat': 'T20', 'startDate': '1757257200000', 'endDate': '1757269800000', 'state': 'Complete', 'status': 'Barbados Royals won by 27 runs', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 263, 'teamName': 'Saint Lucia Kings', 'teamSName': 'SLK', 'imageId': 172316}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 262, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'BR Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 191, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 164, 'wickets': 9, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116774, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '25th Match', 'matchFormat': 'T20', 'startDate': '1757289600000', 'endDate': '1757302200000', 'state': 'Complete', 'status': 'St Kitts and Nevis Patriots won by 5 runs', 'team1': {'teamId': 302, 'teamName': 'St Kitts and Nevis Patriots', 'teamSName': 'SNP', 'imageId': 172351}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'currBatTeamId': 302, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'SNP Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 149, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 144, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116759, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '23rd Match', 'matchFormat': 'T20', 'startDate': '1757199600000', 'endDate': '1757212200000', 'state': 'Complete', 'status': 'Guyana Amazon Warriors won by 3 wkts', 'team1': {'teamId': 271, 'teamName': 'Trinbago Knight Riders', 'teamSName': 'TKR', 'imageId': 172325}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 110, 'ground': 'Providence Stadium', 'city': 'Guyana', 'timezone': '-04:00', 'latitude': '41.823872', 'longitude': '-71.411987'}, 'currBatTeamId': 159, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'GAW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 167, 'wickets': 5, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 168, 'wickets': 7, 'overs': 19.5}}}}, {'matchInfo': {'matchId': 116750, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '22nd Match', 'matchFormat': 'T20', 'startDate': '1757113200000', 'endDate': '1757125800000', 'state': 'Complete', 'status': 'Antigua and Barbuda Falcons won by 4 wkts', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 1978, 'teamName': 'Antigua and Barbuda Falcons', 'teamSName': 'ABF', 'imageId': 507236}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 1978, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'ABF Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 187, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 188, 'wickets': 6, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 116741, 'seriesId': 9575, 'seriesName': 'Caribbean Premier League 2025', 'matchDesc': '21st Match', 'matchFormat': 'T20', 'startDate': '1757026800000', 'endDate': '1757039400000', 'state': 'Complete', 'status': 'Guyana Amazon Warriors won by 4 wkts', 'team1': {'teamId': 262, 'teamName': 'Barbados Royals', 'teamSName': 'BR', 'imageId': 210485}, 'team2': {'teamId': 159, 'teamName': 'Guyana Amazon Warriors', 'teamSName': 'GAW', 'imageId': 172227}, 'venueInfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'timezone': '-04:00', 'latitude': '13.105021', 'longitude': '-59.62257'}, 'currBatTeamId': 159, 'seriesStartDt': '1755043200000', 'seriesEndDt': '1758499200000', 'isTimeAnnounced': True, 'stateTitle': 'GAW Won'}, 

In [ ]:
match_list_data = []

for match_type_entry in data['typeMatches']:
    for series_match_entry in match_type_entry['seriesMatches']:
        if 'seriesAdWrapper' in series_match_entry and 'matches' in series_match_entry['seriesAdWrapper']:
            for match in series_match_entry['seriesAdWrapper']['matches']:
                if 'matchInfo' in match:
                    match_info = match['matchInfo']
                    extracted_details = {
                        'matchId': match_info.get('matchId'),
                        'seriesId': match_info.get('seriesId'),
                        'seriesName': match_info.get('seriesName'),
                        'matchDesc': match_info.get('matchDesc'),
                        'matchFormat': match_info.get('matchFormat'),
                        'startDate': match_info.get('startDate'),
                        'endDate': match_info.get('endDate'),
                        'state': match_info.get('state'),
                        'status': match_info.get('status'),
                        'team1': match_info.get('team1'),
                        'team2': match_info.get('team2'),
                        'venueInfo': match_info.get('venueInfo'),
                        'currBatTeamId': match_info.get('currBatTeamId'),
                        'seriesStartDt': match_info.get('seriesStartDt'),
                        'seriesEndDt': match_info.get('seriesEndDt'),
                        'isTimeAnnounced': match_info.get('isTimeAnnounced'),
                        'stateTitle': match_info.get('stateTitle')
                    }
                    # Extract overs from team1Score if available
                    if 'matchScore' in match and 'team1Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team1Score']:
                        extracted_details['team1_overs'] = match['matchScore']['team1Score']['inngs1'].get('overs')
                    else:
                        extracted_details['team1_overs'] = None

                    # Extract overs from team2Score if available
                    if 'matchScore' in match and 'team2Score' in match['matchScore'] and 'inngs1' in match['matchScore']['team2Score']:
                        extracted_details['team2_overs'] = match['matchScore']['team2Score']['inngs1'].get('overs')
                    else:
                        extracted_details['team2_overs'] = None

                    match_list_data.append(extracted_details)

df_match_list = pd.DataFrame(match_list_data)
display(df_match_list.head())

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,team2,venueInfo,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,1757514600000,1757527200000,Complete,India won by 9 wkts,"{'teamId': 7, 'teamName': 'United Arab Emirate...","{'teamId': 2, 'teamName': 'India', 'teamSName'...","{'id': 153, 'ground': 'Dubai International Cri...",2.0,1757289600000,1759104000000,True,IND Won,13.1,4.3
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,1757428200000,1757440800000,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 8, 'teamName': 'Hong Kong', 'teamSN...","{'id': 94, 'ground': 'Sheikh Zayed Stadium', '...",96.0,1757289600000,1759104000000,True,AFG Won,19.6,19.6
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,1757525400000,1757538000000,Complete,South Africa won by 14 runs (DLS Method),"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 62, 'ground': 'Sophia Gardens', 'city':...",11.0,1756684800000,1757894400000,True,Complete,7.5,4.6
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,1757239200000,1757268000000,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'teamId': 11, 'teamName': 'South Africa', 'te...","{'id': 21, 'ground': 'The Rose Bowl', 'city': ...",9.0,1756684800000,1757894400000,True,ENG Won,49.6,20.5
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,1756987200000,1757016000000,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 19, 'ground': 'Lord's', 'city': 'London...",11.0,1756684800000,1757894400000,True,RSA Won,49.6,49.6

In [ ]:
df_match_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          57 non-null     int64
 1   seriesId         57 non-null     int64
 2   seriesName       57 non-null     object
 3   matchDesc        57 non-null     object
 4   matchFormat      57 non-null     object
 5   startDate        57 non-null     object
 6   endDate          57 non-null     object
 7   state            57 non-null     object
 8   status           57 non-null     object
 9   team1            57 non-null     object
 10  team2            57 non-null     object
 11  venueInfo        57 non-null     object
 12  currBatTeamId    52 non-null     float64
 13  seriesStartDt    57 non-null     object
 14  seriesEndDt      57 non-null     object
 15  isTimeAnnounced  57 non-null     bool
 16  stateTitle       57 non-null     object
 17  team1_overs      54 non-null     float64
 18  team2_overs      54 non-null     float64
dtypes: bool(1), float64(3), int64(2), object(13)
memory usage: 8.2+ KB

In [ ]:
df_match_list

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,team1,team2,venueInfo,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,1757514600000,1757527200000,Complete,India won by 9 wkts,"{'teamId': 7, 'teamName': 'United Arab Emirate...","{'teamId': 2, 'teamName': 'India', 'teamSName'...","{'id': 153, 'ground': 'Dubai International Cri...",2.0,1757289600000,1759104000000,True,IND Won,13.1,4.3
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,1757428200000,1757440800000,Complete,Afghanistan won by 94 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 8, 'teamName': 'Hong Kong', 'teamSN...","{'id': 94, 'ground': 'Sheikh Zayed Stadium', '...",96.0,1757289600000,1759104000000,True,AFG Won,19.6,19.6
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,1757525400000,1757538000000,Complete,South Africa won by 14 runs (DLS Method),"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 62, 'ground': 'Sophia Gardens', 'city':...",11.0,1756684800000,1757894400000,True,Complete,7.5,4.6
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,1757239200000,1757268000000,Complete,England won by 342 runs,"{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'teamId': 11, 'teamName': 'South Africa', 'te...","{'id': 21, 'ground': 'The Rose Bowl', 'city': ...",9.0,1756684800000,1757894400000,True,ENG Won,49.6,20.5
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,1756987200000,1757016000000,Complete,South Africa won by 5 runs,"{'teamId': 11, 'teamName': 'South Africa', 'te...","{'teamId': 9, 'teamName': 'England', 'teamSNam...","{'id': 19, 'ground': 'Lord's', 'city': 'London...",11.0,1756684800000,1757894400000,True,RSA Won,49.6,49.6
5,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,1756998000000,1757010600000,Complete,Pakistan won by 31 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",3.0,1756339200000,1757289600000,True,PAK Won,19.6,19.6
6,131092,10642,United Arab Emirates T20I Tri-Series 2025,Final,T20,1757257200000,1757269800000,Complete,Pakistan won by 75 runs,"{'teamId': 3, 'teamName': 'Pakistan', 'teamSNa...","{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",3.0,1756339200000,1757289600000,True,PAK Won,19.6,15.5
7,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,1757084400000,1757097000000,Complete,Afghanistan won by 4 runs,"{'teamId': 96, 'teamName': 'Afghanistan', 'tea...","{'teamId': 7, 'teamName': 'United Arab Emirate...","{'id': 140, 'ground': 'Sharjah Cricket Stadium...",96.0,1756339200000,1757289600000,True,AFG Won,19.6,19.6
8,128919,7572,ICC Cricket World Cup League Two 2023-27,85th Match,ODI,1757169000000,1757197800000,Abandon,Match abandoned due to wet outfield (no toss),"{'teamId': 26, 'teamName': 'Canada', 'teamSNam...","{'teamId': 23, 'teamName': 'Scotland', 'teamSN...","{'id': 139, 'ground': 'Maple Leaf North-West G...",NaN,1707868800000,1806451200000,True,Abandon,NaN,NaN
9,128908,7572,ICC Cricket World Cup League Two 2023-27,84th Match,ODI,1756996200000,1757025000000,Complete,Scotland won by 55 runs (24 overs game due to ...,"{'teamId': 23, 'teamName': 'Scotland', 'teamSN...","{'teamId': 161, 'teamName': 'Namibia', 'teamSN...","{'id': 139, 'ground': 'Maple Leaf North-West G...",23.0,1707868800000,1806451200000,True,SCO Won,23.6,21.2
10,122973,10267,"Sri Lanka tour of Zimbabwe, 2025",3rd T20I,T20,1757244600000,1757257200000,Complete,Sri Lanka won by 8 wkts,"{'teamId': 12, 'teamName': 'Zimbabwe', 'teamSN...","{'teamId': 5, 'teamName': 'Sri Lanka', 'teamSN...","{'id': 69, 'ground': 'Harare Sports Club', 'ci...",5.0,1756339200000,1757289600000,True,SL Won,19.6,17.4
11,122968,10267,"Sri Lanka tour of Zimbabwe, 2025",2nd T20I,T20,1757158200000,1757170800000,Complete,Zimbabwe won by 5 wkts,"{'teamId': 5, 'teamName': 'Sri Lanka', 'teamSN...","{'teamId': 12, 'teamName': 'Zimbabwe', 'teamSN...","{'id': 69, 'ground': 'Harare Sports Club', 'ci...",12.0,1756339200000,1757289600000,True,ZIM Won,17.4,14.2
12,133187,10812,Sweden tour of Isle Of Man 2025,4th Match,T20,1757255400000,1757268000000,Abandon,Match abandoned without toss,"{'teamId': 557, 'teamName': 'Isle of Man', 'te...","{'teamId': 534, 'teamName': 'Sweden', 'teamSNa...","{'id': 1438142, 'ground': 'Cronkbourne Sports ...",NaN,1757030400000,1757289600000,True,Abandon,NaN,NaN
13,133176,10812,Sweden tour of Isle Of Man 2025,3rd T20I,T20,1757239200000,1757251800000,Abandon,Match abandoned without toss,"{'teamId': 557, 'teamName': 'Isle of Man', 'te...","{'teamId': 534, 'teamName': 'Sweden', 'teamSNa...","{'id': 1438142, 'ground': 'Cronkbourne Sports ...",NaN,1757030400000,1757289600000,True,Abandon,NaN,NaN
14,133171,10812,Sweden tour of Isle Of Man 2025,2nd T20I,T20,1757169000000,1757181600000,Complete,Sweden won by 3 wkts,"{'teamId': 557, 'teamName': 'Isle of Man', 'te...","{'teamId': 534, 'teamName': 'Sweden', 'teamSNa...","{'id': 1438142, 'ground': 'Cronkbourne Sports ...",534.0,1757030400000,1757289600000,True,SWE Won,19.5,14.3
15,133160,10812,Sweden tour of Isle Of Man 2025,1st T20I,T20,1757152800000,1757165400000,Complete,Sweden won by 10 wkts,"{'teamId': 557, 'teamName': 'Isle of Man', 'te...","{'teamId': 534, 'teamName': 'Sweden', 'teamSNa...","{'id': 1438142, 'ground': 'Cronkbourne Sports ...",534.0,1757030400000,1757289600000,True,SWE Won,16.1,10.5
16,116765,9575,Caribbean Premier League 2025,24th Match,T20,1757257200000,1757269800000,Complete,Barbados Royals won by 27 runs,"{'teamId': 262, 'teamName': 'Barbados Royals',...","{'teamId': 263, 'teamName': 'Saint Lucia Kings...","{'id': 55, 'ground': 'Kensington Oval', 'city'...",262.0,1755043200000,1758499200000,True,BR Won,19.6,19.6
17,116774,9575,Caribbean Premier League 2025,25th Match,T20,1757289600000,1757302200000,Complete,St Kitts and Nevis Patriots won by 5 runs,"{'teamId': 302, 'teamName': 'St Kitts and Nevi...","{'teamId': 159, 'teamName': 'Guyana Amazon War...","{'id': 110, 'ground': 'Providence Stadium', 'c...",302.0,1755043200000,1758499200000,True,SNP Won,19.6,19.6
18,116759,9575,Caribbean Premier League 2025,23rd Match,T20,1757199600000,1757212200000,Complete,Guyana Amazon Warriors won by 3 wkts,"{'teamId': 271, 'teamName': 'Trinbago Knight R...","{'teamId': 159, 'teamName': 'Guyana Amazon War...","{'id': 110, 'ground': 'Providence Stadium', 'c...",159.0,1755043200000,1758499200000,True,GAW Won,19.6,19.5
19,116750,9575,Caribbean Premier League 2025,22nd Match,T20,1757113200000,1757125800000,Complete,Antigua and Barbuda Falcons won by 4 wkts,"{'teamId': 262, 'teamName': 'Barbados Royals',...","{'teamId': 1978, 'teamName': 'Antigua and Barb...","{'id': 55, 'ground': 'Kensington Oval', 'city'...",1978.0,1755043200000,1758499200000,True,ABF Won,19.6,19.6
20,116741,9575,Caribbean Premier League 2025,21st Match,T20,1757026800000,1757039400000,Complete,Guyana Amazon Warriors won by 4 wkts,"{'teamId': 262, 'teamName': 'Barbados Royals',...","{'teamId': 159, 'teamName': 'Guyana Amazon War...","{'id': 55, 'ground': 'Kensington Oval', 'city'...",159.0,1755043200000,1758499200000,True,GAW Won,19.6,19.4
21,116783,9575,Caribbean Premier League 2025,26th Match,T20,1757545200000,1757557800000,Complete,Antigua and Barbuda Falcons won by 4 wkts,"{'teamId': 159, 'teamName': 'Guyana Amazon War...","{'teamId': 1978, 'teamName': 'Antigua and Barb...","{'id': 110, 'ground': 'Providence Stadium', 'c...",1978.0,1755043200000,1758499200000,True,ABF Won,18.1,19.1
22,111073,9257,T20 Blast 2025,Quarter Final 3,T20,1757165400000,1757178000000,Complete,Lancashire won by 3 wkts,"{'teamId': 150, 'teamName': 'Kent', 'teamSName...","{'teamId': 143, 'teamName': 'Lancashire', 'tea...","{'id': 65, 'ground': 'Emirates Old Trafford', ...",143.0,1748390400000,1757808000000,True,LANCS Won,19.6,18.3
23,111069,9257,T20 Blast 2025,Quarter Final 2,T20,1757093400000,1757106000000,Complete,Hampshire won by 26 runs,"{'teamId': 153, 'teamName': 'Hampshire', 'team...","{'teamId': 141, 'teamName': 'Durham', 'teamSNa...","{'id': 60, 'ground': 'Riverside Ground', 'city...",153.0,1748390400000,1757808000000,True,HAM Won,19.6,19.6
24,111081,9257,T20 Blast 2025,Quarter Final 4,T20,1757179800000,1757192400000,Complete,Somerset won by 4 wkts,"{'teamId': 140, 'teamName': 'Warwickshire', 't...","{'teamId': 119, 'teamName': 'Somerset', 'teamS...","{'id': 223, 'ground': 'The Cooper Associates C...",119.0,1748390400000,1757808000000,True,SOM Won,19.6,19.5
25,132637,10735,Uttar Pradesh Premier League 2025,Qualifier 2,T20,1756994400000,1757007000000,Complete,Meerut Mavericks won by 19 runs,"{'teamId': 2833, 'teamName': 'Meerut Mavericks...","{'teamId': 2844, 'teamName': 'Lucknow Falcons'...","{'id': 485, 'ground': 'Bharat Ratna Shri Atal ...",2833.0,1755302400000,1757203200000,True,MRM Won,19.6,19.6
26,132648,10735,Uttar Pradesh Premier League 2025,Final,T20,1757167200000,1757179800000,Complete,Kashi Rudras won by 8 wkts,"{'teamId': 2833, 'teamName': 'Meerut Mavericks...","{'teamId': 2800, 'teamName': 'Kashi Rudras', '...","{'id': 485, 'ground': 'Bharat Ratna Shri Atal ...",2800.0,1755302400000,1757203200000,True,KRD Won,19.6,15.4
27,130806,10620,Kerala Cricket League 2025,Final,T20,1757250900000,1757263500000,Complete,Kochi Blue Tigers won by 75 runs,"{'teamId': 2733, 'teamName': 'Kochi Blue Tiger...","{'teamId': 2778, 'teamName': 'Aries Kollam Sai...","{'id': 506, 'ground': 'Greenfield Internationa...",2733.0,1755648000000,1757203200000,True,KBT Won,19.6,16.3
28,130795,10620,Kerala Cricket League 2025,Semi Final 2 (1st v 4th),T20,1757078100000,1757090700000,Complete,Kochi Blue Tigers won by 15 runs,"{'teamId': 2733, 'teamName': 'Kochi Blue Tiger...","{'teamId': 2741, 'teamName': 'Calicut Globstar...","{'id': 506, 'ground': 'Greenfield Internationa...",2733.0,1755648000000,1757203200000,True,KBT Won,19.6,19.6
29,130784,10620,Kerala Cricket League 2025,Semi Final 1 (2nd v 3rd),T20,1757062800000,1757075400000,Complete,Aries Kollam Sailors won by 10 wkts,"{'teamId': 2752, 'teamName': 'Thrissur Titans'...","{'teamId': 2778, 'teamName': 'Aries Kollam Sai...","{'id': 506, 'ground': 'Greenfield Internationa...",2778.0,1755648000000,1757203200000,True,AKS Won,17.1,9.5
30,130778,10620,Kerala Cricket League 2025,30th Match,T20,1756991700000,1757004300000,Complete,Thrissur Titans won by 4 wkts,"{'teamId': 2741, 'teamName': 'Calicut Globstar...","{'teamId': 2752, 'teamName': 'Thrissur Titans'...","{'id': 506, 'ground': 'Greenfield Internationa...",2752.0,1755648000000,1757203200000,True,TST Won,19.6,18.1
31,123677,10311,Duleep Trophy 2025,2nd Semi-Final,TEST,1756958400000,1757242800000,Complete,Match drawn,"{'teamId': 234, 'teamName': 'West Zone', 'team...","{'teamId': 237, 'teamName': 'Central Zone', 't...","{'id': 1438102, 'ground': 'BCCI Centre of Exce...",NaN,1756252800000,1757980800000,True,Complete,107.6,164.3
32,123672,10311,Duleep Trophy 2025,1st Semi-Final,TEST,1756958400000,1757242800000,Complete,Match drawn,"{'teamId': 236, 'teamName': 'South Zone', 'tea...","{'teamId': 233, 'teamName': 'North Zone', 'tea...","{'id': 1438087, 'ground': 'BCCI Centre of Exce...",NaN,1756252800000,1757980800000,True,Complete,169.2,100.1
33,113217,9360,County Championship Division One 2025,60th Match,TEST,1757323800000,1757608200000,Complete,Nottinghamshire won by 3 wkts,"{'teamId': 147, 'teamName': 'Worcestershire', ...","{'teamId': 139, 'teamName': 'Nottinghamshire',...","{'id': 225, 'ground': 'New Road', 'city': 'Wor...",139.0,1743638400000,1759017600000,True,Complete,52.5,70.2
34,116495,9557,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,1757232000000,1757516400000,Complete,New Zealand A won by 185 runs,"{'teamId': 80, 'teamName': 'New Zealand A', 't...","{'teamId': 268, 'teamName': 'South Africa A', ...","{'id': 102, 'ground': 'Senwes Park', 'city': '...",80.0,1756425600000,1758153600000,True,NZA Won,128.5,56.1
35,133055,10785,Czech Republic Women tour Estonia 2025,1st T20I,T20,1757145600000,1757158200000,Complete,Estonia Women won by 1 wkt,"{'teamId': 1987, 'teamName': 'Czech Republic W...","{'teamId': 1521, 'teamName': 'Estonia Women', ...","{'id': 1552, 'ground': 'Estonian National Cric...",1521.0,1757030400000,1757289600000,True,ESTW Won,20.0,19.4
36,133066,10785,Czech Republic Women tour Estonia 2025,3rd T20I,T20,1757228400000,1757241000000,Complete,Estonia Women won by 7 wkts,"{'teamId': 1987, 'teamName': 'Czech Republic W...","{'teamId': 1521, 'teamName': 'Estonia Women', ...","{'id': 1552, 'ground': 'Estonian National Cric...",1521.0,1757030400000,1757289600000,True,ESTW Won,19.5,9.6
37,133061,10785,Czech Republic Women tour Estonia 2025,2nd T20I,T20,1757161800000,1757174400000,Complete,Estonia Women won by 115 runs,"{'teamId': 1521, 'teamName': 'Estonia Women', ...","{'teamId': 1987, 'teamName': 'Czech Republic W...","{'id': 1552, 'ground': 'Estonian National Cric...",1521.0,1757030400000,1757289600000,True,ESTW Won,20.0,12.1
38,133798,10856,Japan Women tour of Fiji 2025,1st T20I,T20,1757037600000,1757050200000,Complete,Japan Women won by 23 runs,"{'teamId': 487, 'teamName': 'Japan Women', 'te...","{'teamId': 1181, 'teamName': 'Fiji Women', 'te...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",487.0,1756944000000,1757203200000,True,JPNW Won,19.6,19.6
39,133809,10856,Japan Women tour of Fiji 2025,2nd T20I,T20,1757109600000,1757122200000,Complete,Japan Women won by 104 runs,"{'teamId': 487, 'teamName': 'Japan Women', 'te...","{'teamId': 1181, 'teamName': 'Fiji Women', 'te...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",487.0,1756944000000,1757203200000,True,JPNW Won,19.6,12.3
40,131675,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off,T20,1757159400000,1757172000000,Complete,Rwanda Women won by 6 runs,"{'teamId': 720, 'teamName': 'Rwanda Women', 't...","{'teamId': 501, 'teamName': 'Kenya Women', 'te...","{'id': 1438052, 'ground': 'High Performance Ov...",720.0,1756512000000,1757203200000,True,RWAW Won,19.6,19.6
41,131669,10697,ICC Womens T20 World Cup Africa Region Divisio...,7th Place Play-off,T20,1757143800000,1757156400000,Complete,Nigeria Women won by 85 runs,"{'teamId': 1482, 'teamName': 'Nigeria Women', ...","{'teamId': 490, 'teamName': 'Sierra Leone Wome...","{'id': 1438052, 'ground': 'High Performance Ov...",1482.0,1756512000000,1757203200000,True,NGAW Won,19.6,19.6
42,131647,10697,ICC Womens T20 World Cup Africa Region Divisio...,2nd semi-final,T20,1756986600000,1756999200000,Complete,Namibia Women won by 8 wkts,"{'teamId': 483, 'teamName': 'Tanzania Women', ...","{'teamId': 503, 'teamName': 'Namibia Women', '...","{'id': 1438021, 'ground': 'Namibia Cricket Gro...",503.0,1756512000000,1757203200000,True,NAMW Won,19.6,13.5
43,131653,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off 2nd Semi-Final,T20,1756986600000,1756999200000,Complete,Rwanda Women won by 50 runs,"{'teamId': 720, 'teamName': 'Rwanda Women', 't...","{'teamId': 490, 'teamName': 'Sierra Leone Wome...","{'id': 1438052, 'ground': 'High Performance Ov...",720.0,1756512000000,1757203200000,True,RWAW Won,19.6,19.6
44,131686,10697,ICC Womens T20 World Cup Africa Region Divisio...,Final,T20,1757159400000,1757172000000,Complete,Zimbabwe Women won by 9 wkts,"{'teamId': 503, 'teamName': 'Namibia Women', '...","{'teamId': 388, 'teamName': 'Zimbabwe Women', ...","{'id': 1438021, 'ground': 'Namibia Cricket Gro...",388.0,1756512000000,1757203200000,True,ZIMW Won,19.6,16.3
45,131664,10697,ICC Womens T20 World Cup Africa Region Divisio...,3rd place play-off,T20,1757143800000,1757156400000,Complete,Tanzania Women won by 6 runs,"{'teamId': 483, 'teamName': 'Tanzania Women', ...","{'teamId': 448, 'teamName': 'Uganda Women', 't...","{'id': 1438021, 'ground': 'Namibia Cricket Gro...",483.0,1756512000000,1757203200000,True,TANW Won,19.6,19.4
46,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,1757381400000,1757394000000,Complete,Vanuatu Women won by 10 runs,"{'teamId': 506, 'teamName': 'Vanuatu Women', '...","{'teamId': 484, 'teamName': 'Indonesia Women',...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",506.0,1757289600000,1757980800000,True,VANW Won,19.6,19.6
47,131774,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,1757467800000,1757480400000,Complete,Papua New Guinea Women won by 168 runs,"{'teamId': 390, 'teamName': 'Papua New Guinea ...","{'teamId': 1514, 'teamName': 'Philippines Wome...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",390.0,1757289600000,1757980800000,True,PNGW Won,19.6,19.4
48,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,1757367000000,1757379600000,Complete,Fiji Women won by 9 wkts,"{'teamId': 1754, 'teamName': 'Cook Islands Wom...","{'teamId': 1181, 'teamName': 'Fiji Women', 'te...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",1181.0,1757289600000,1757980800000,True,FIJIW Won,19.6,17.2
49,131757,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"5th Match, Group B",T20,1757453400000,1757466000000,Complete,Japan Women won by 71 runs,"{'teamId': 487, 'teamName': 'Japan Women', 'te...","{'teamId': 482, 'teamName': 'Samoa Women', 'te...","{'id': 1438120, 'ground': 'Albert Park 1', 'ci...",487.0,1757289600000,1757980800000,True,JPNW Won,19.6,13.5
50,131779,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,1757467800000,1757480400000,Complete,Vanuatu Women won by 7 wkts,"{'teamId': 1754, 'teamName': 'Cook Islands Wom...","{'teamId': 506, 'teamName': 'Vanuatu Women', '...","{'id': 1438123, 'ground': 'Albert Park 2', 'ci...",506.0,1757289600000,1757980800000,True,VANW Won,19.6,15.1
51,131741,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"2nd Match, Group B",T20,1757367000000,1757379600000,Complete,Papua New Guinea Women won by 45 runs,"{'teamId': 390, 'teamName': 'Papua New Guinea ...","{'teamId': 487, 'teamName': 'Japan Women', 'te...","{'id': 1438123, 'ground': 'Albert Park 2', 'ci...",390.0,1757289600000,1757980800000,True,PNGW Won,19.6,19.5
52,131763,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"6th Match, Group A",T20,1757453400000,1757466000000,Complete,Indonesia Women won by 42 runs,"{'teamId': 484, 'teamName': 'Indonesia Women',...","{'teamId': 1181, 'teamName': 'Fiji Women', 'te...","{'id': 1438123, 'ground': 'Albert Park 2', 'ci...",484.0,1757289600000,1757980800000,True,IDNW Won,19.6,19.3
53,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,1757381400000,1757394000000,Complete,Samoa Women won by 9 wkts,"{'teamId': 1514, 'teamName': 'Philippines Wome...","{'teamId': 482, 'teamName': 'Samoa Women', 'te...","{'id': 1438123, 'ground': 'Albert Park 2', 'ci...",482.0,1757289600000,1757980800000,True,WSMW Won,17.3,6.2
54,122104,10141,Womens Caribbean Premier League 2025,3rd Match,T20,1757527200000,1757539800000,Complete,Barbados Royals Women won by 59 runs,"{'teamId': 1137, 'teamName': 'Barbados Royals ...","{'teamId': 1139, 'teamName': 'Trinbago Knight ...","{'id': 110, 'ground': 'Providence Stadium', 'c...",1137.0,1757030400000,1758153600000,True,BRW Won,19.6,15.3
55,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,1757271600000,1757284200000,Complete,Barbados Royals Women won by 7 wkts (DLS method),"{'teamId': 1144, 'teamName': 'Guyana Amazon Wa...","{'teamId': 1137, 'teamName': 'Barbados Royals ...","{'id': 110, 'ground': 'Providence Stadium', 'c...",1137.0,1757030400000,1758153600000,True,BRW Won,19.6,17.2

In [ ]:
# Extract details from 'team1' and 'team2' columns
df_match_list['team1_id'] = df_match_list['team1'].apply(lambda x: x.get('teamId') if isinstance(x, dict) else None)
df_match_list['team1_name'] = df_match_list['team1'].apply(lambda x: x.get('teamName') if isinstance(x, dict) else None)
df_match_list['team1_sname'] = df_match_list['team1'].apply(lambda x: x.get('teamSName') if isinstance(x, dict) else None)
df_match_list['team1_image_id'] = df_match_list['team1'].apply(lambda x: x.get('imageId') if isinstance(x, dict) else None)

df_match_list['team2_id'] = df_match_list['team2'].apply(lambda x: x.get('teamId') if isinstance(x, dict) else None)
df_match_list['team2_name'] = df_match_list['team2'].apply(lambda x: x.get('teamName') if isinstance(x, dict) else None)
df_match_list['team2_sname'] = df_match_list['team2'].apply(lambda x: x.get('teamSName') if isinstance(x, dict) else None)
df_match_list['team2_image_id'] = df_match_list['team2'].apply(lambda x: x.get('imageId') if isinstance(x, dict) else None)

# Extract venue details
df_match_list['venue_id'] = df_match_list['venueInfo'].apply(lambda x: x.get('id') if isinstance(x, dict) else None)
df_match_list['ground'] = df_match_list['venueInfo'].apply(lambda x: x.get('ground') if isinstance(x, dict) else None)
df_match_list['city'] = df_match_list['venueInfo'].apply(lambda x: x.get('city') if isinstance(x, dict) else None)
df_match_list['timezone'] = df_match_list['venueInfo'].apply(lambda x: x.get('timezone') if isinstance(x, dict) else None)
df_match_list['latitude'] = df_match_list['venueInfo'].apply(lambda x: x.get('latitude') if isinstance(x, dict) else None)
df_match_list['longitude'] = df_match_list['venueInfo'].apply(lambda x: x.get('longitude') if isinstance(x, dict) else None)


# Display the updated DataFrame info to verify the new columns
df_match_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          57 non-null     int64
 1   seriesId         57 non-null     int64
 2   seriesName       57 non-null     object
 3   matchDesc        57 non-null     object
 4   matchFormat      57 non-null     object
 5   startDate        57 non-null     object
 6   endDate          57 non-null     object
 7   state            57 non-null     object
 8   status           57 non-null     object
 9   team1            57 non-null     object
 10  team2            57 non-null     object
 11  venueInfo        57 non-null     object
 12  currBatTeamId    52 non-null     float64
 13  seriesStartDt    57 non-null     object
 14  seriesEndDt      57 non-null     object
 15  isTimeAnnounced  57 non-null     bool
 16  stateTitle       57 non-null     object
 17  team1_overs      54 non-null     float64
 18  team2_overs      54 non-null     float64
 19  team1_id         57 non-null     int64
 20  team1_name       57 non-null     object
 21  team1_sname      57 non-null     object
 22  team1_image_id   57 non-null     int64
 23  team2_id         57 non-null     int64
 24  team2_name       57 non-null     object
 25  team2_sname      57 non-null     object
 26  team2_image_id   57 non-null     int64
 27  venue_id         57 non-null     int64
 28  ground           57 non-null     object
 29  city             57 non-null     object
 30  timezone         57 non-null     object
 31  latitude         57 non-null     object
 32  longitude        57 non-null     object
dtypes: bool(1), float64(3), int64(7), object(22)
memory usage: 14.4+ KB

In [ ]:
# show nan value
df_match_list.isna().sum()

matchId            0
seriesId           0
seriesName         0
matchDesc          0
matchFormat        0
startDate          0
endDate            0
state              0
status             0
currBatTeamId      0
seriesStartDt      0
seriesEndDt        0
isTimeAnnounced    0
stateTitle         0
team1_overs        0
team2_overs        0
team1_id           0
team1_name         0
team1_sname        0
team1_image_id     0
team2_id           0
team2_name         0
team2_sname        0
team2_image_id     0
venue_id           0
ground             0
city               0
timezone           0
latitude           0
longitude          0
dtype: int64

In [ ]:
# fill nan value using mode
df_match_list['team1_overs'].fillna(df_match_list['team1_overs'].mode()[0], inplace=True)
df_match_list['team2_overs'].fillna(df_match_list['team2_overs'].mode()[0], inplace=True)
df_match_list['currBatTeamId'].fillna(df_match_list['currBatTeamId'].mode()[0], inplace=True)

In [ ]:
# drop team1 team 2 and valueinfo
df_match_list.drop(['team1', 'team2', 'venueInfo'], axis=1, inplace=True)

In [ ]:
df_match_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   matchId          57 non-null     int64
 1   seriesId         57 non-null     int64
 2   seriesName       57 non-null     object
 3   matchDesc        57 non-null     object
 4   matchFormat      57 non-null     object
 5   startDate        57 non-null     datetime64[ns]
 6   endDate          57 non-null     datetime64[ns]
 7   state            57 non-null     object
 8   status           57 non-null     object
 9   currBatTeamId    57 non-null     float64
 10  seriesStartDt    57 non-null     datetime64[ns]
 11  seriesEndDt      57 non-null     datetime64[ns]
 12  isTimeAnnounced  57 non-null     bool
 13  stateTitle       57 non-null     object
 14  team1_overs      57 non-null     float64
 15  team2_overs      57 non-null     float64
 16  team1_id         57 non-null     int64
 17  team1_name       57 non-null     object
 18  team1_sname      57 non-null     object
 19  team1_image_id   57 non-null     int64
 20  team2_id         57 non-null     int64
 21  team2_name       57 non-null     object
 22  team2_sname      57 non-null     object
 23  team2_image_id   57 non-null     int64
 24  venue_id         57 non-null     int64
 25  ground           57 non-null     object
 26  city             57 non-null     object
 27  timezone         57 non-null     object
 28  latitude         57 non-null     object
 29  longitude        57 non-null     object
dtypes: bool(1), datetime64[ns](4), float64(3), int64(7), object(15)
memory usage: 13.1+ KB

In [ ]:
#set all column view
pd.set_option('display.max_columns', None)

In [ ]:
df_match_list.head()

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,2025-09-08,2025-09-29,True,IND Won,13.1,4.3,7,United Arab Emirates,UAE,172121,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08,2025-09-29,True,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,2025-09-01,2025-09-15,True,Complete,7.5,4.6,11,South Africa,RSA,172126,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01,2025-09-15,True,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01,2025-09-15,True,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926

In [ ]:
# convert all datetime all startdate,enddate,serisstartdated and enddate
df_match_list['startDate'] = pd.to_datetime(df_match_list['startDate'], unit='ms', errors='coerce')
df_match_list['endDate'] = pd.to_datetime(df_match_list['endDate'], unit='ms', errors='coerce')
df_match_list['seriesStartDt'] = pd.to_datetime(df_match_list['seriesStartDt'], unit='ms', errors='coerce')
df_match_list['seriesEndDt'] = pd.to_datetime(df_match_list['seriesEndDt'], unit='ms', errors='coerce')

In [ ]:
import sqlite3 as sql

# create a new database and connect to it
conn_crickbuzz = sql.connect('crickbuzz.db')

In [ ]:
# save the DataFrame to the new database
df_match_list.to_sql('match_list', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM match_list', conn_crickbuzz)

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,IND Won,13.1,4.3,7,United Arab Emirates,UAE,172121,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,Complete,7.5,4.6,11,South Africa,RSA,172126,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
5,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
6,131092,10642,United Arab Emirates T20I Tri-Series 2025,Final,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Pakistan won by 75 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,15.5,3,Pakistan,PAK,591986,96,Afghanistan,AFG,172188,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
7,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,96.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
8,128919,7572,ICC Cricket World Cup League Two 2023-27,85th Match,ODI,2025-09-06 14:30:00,2025-09-06 22:30:00,Abandon,Match abandoned due to wet outfield (no toss),487.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,Abandon,19.6,19.6,26,Canada,CAN,172140,23,Scotland,SCO,172137,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
9,128908,7572,ICC Cricket World Cup League Two 2023-27,84th Match,ODI,2025-09-04 14:30:00,2025-09-04 22:30:00,Complete,Scotland won by 55 runs (24 overs game due to ...,23.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,SCO Won,23.6,21.2,23,Scotland,SCO,172137,161,Namibia,NAM,172229,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
10,122973,10267,"Sri Lanka tour of Zimbabwe, 2025",3rd T20I,T20,2025-09-07 11:30:00,2025-09-07 15:00:00,Complete,Sri Lanka won by 8 wkts,5.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,SL Won,19.6,17.4,12,Zimbabwe,ZIM,172127,5,Sri Lanka,SL,172119,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
11,122968,10267,"Sri Lanka tour of Zimbabwe, 2025",2nd T20I,T20,2025-09-06 11:30:00,2025-09-06 15:00:00,Complete,Zimbabwe won by 5 wkts,12.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,ZIM Won,17.4,14.2,5,Sri Lanka,SL,172119,12,Zimbabwe,ZIM,172127,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
12,133187,10812,Sweden tour of Isle Of Man 2025,4th Match,T20,2025-09-07 14:30:00,2025-09-07 18:00:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
13,133176,10812,Sweden tour of Isle Of Man 2025,3rd T20I,T20,2025-09-07 10:00:00,2025-09-07 13:30:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
14,133171,10812,Sweden tour of Isle Of Man 2025,2nd T20I,T20,2025-09-06 14:30:00,2025-09-06 18:00:00,Complete,Sweden won by 3 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,19.5,14.3,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
15,133160,10812,Sweden tour of Isle Of Man 2025,1st T20I,T20,2025-09-06 10:00:00,2025-09-06 13:30:00,Complete,Sweden won by 10 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,16.1,10.5,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
16,116765,9575,Caribbean Premier League 2025,24th Match,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Barbados Royals won by 27 runs,262.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,BR Won,19.6,19.6,262,Barbados Royals,BR,210485,263,Saint Lucia Kings,SLK,172316,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
17,116774,9575,Caribbean Premier League 2025,25th Match,T20,2025-09-08 00:00:00,2025-09-08 03:30:00,Complete,St Kitts and Nevis Patriots won by 5 runs,302.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,SNP Won,19.6,19.6,302,St Kitts and Nevis Patriots,SNP,172351,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
18,116759,9575,Caribbean Premier League 2025,23rd Match,T20,2025-09-06 23:00:00,2025-09-07 02:30:00,Complete,Guyana Amazon Warriors won by 3 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.5,271,Trinbago Knight Riders,TKR,172325,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
19,116750,9575,Caribbean Premier League 2025,22nd Match,T20,2025-09-05 23:00:00,2025-09-06 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,19.6,19.6,262,Barbados Royals,BR,210485,1978,Antigua and Barbuda Falcons,ABF,507236,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
20,116741,9575,Caribbean Premier League 2025,21st Match,T20,2025-09-04 23:00:00,2025-09-05 02:30:00,Complete,Guyana Amazon Warriors won by 4 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.4,262,Barbados Royals,BR,210485,159,Guyana Amazon Warriors,GAW,172227,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
21,116783,9575,Caribbean Premier League 2025,26th Match,T20,2025-09-10 23:00:00,2025-09-11 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,18.1,19.1,159,Guyana Amazon Warriors,GAW,172227,1978,Antigua and Barbuda Falcons,ABF,507236,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
22,111073,9257,T20 Blast 2025,Quarter Final 3,T20,2025-09-06 13:30:00,2025-09-06 17:00:00,Complete,Lancashire won by 3 wkts,143.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,LANCS Won,19.6,18.3,150,Kent,KENT,172217,143,Lancashire,LANCS,172210,65,Emirates Old Trafford,Manchester,+01:00,53.463066,-2.291301
23,111069,9257,T20 Blast 2025,Quarter Final 2,T20,2025-09-05 17:30:00,2025-09-05 21:00:00,Complete,Hampshire won by 26 runs,153.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,HAM Won,19.6,19.6,153,Hampshire,HAM,172220,141,Durham,DUR,172208,60,Riverside Ground,Chester-le-Street,+01:00,54.849531,-1.56103
24,111081,9257,T20 Blast 2025,Quarter Final 4,T20,2025-09-06 17:30:00,2025-09-06 21:00:00,Complete,Somerset won by 4 wkts,119.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,SOM Won,19.6,19.5,140,Warwickshire,WARKS,172207,119,Somerset,SOM,172199,223,The Cooper Associates County Ground,Taunton,+01:00,51.018913,3.100894
25,132637,10735,Uttar Pradesh Premier League 2025,Qualifier 2,T20,2025-09-04 14:00:00,2025-09-04 17:30:00,Complete,Meerut Mavericks won by 19 runs,2833.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,MRM Won,19.6,19.6,2833,Meerut Mavericks,MRM,738654,2844,Lucknow Falcons,LFC,738651,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
26,132648,10735,Uttar Pradesh Premier League 2025,Final,T20,2025-09-06 14:00:00,2025-09-06 17:30:00,Complete,Kashi Rudras won by 8 wkts,2800.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,KRD Won,19.6,15.4,2833,Meerut Mavericks,MRM,738654,2800,Kashi Rudras,KRD,738657,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
27,130806,10620,Kerala Cricket League 2025,Final,T20,2025-09-07 13:15:00,2025-09-07 16:45:00,Complete,Kochi Blue Tigers won by 75 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,16.3,2733,Kochi Blue Tigers,KBT,731734,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
28,130795,10620,Kerala Cricket League 2025,Semi Final 2 (1st v 4th),T20,2025-09-05 13:15:00,2025-09-05 16:45:00,Complete,Kochi Blue Tigers won by 15 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,19.6,2733,Kochi Blue Tigers,KBT,731734,2741,Calicut Globstars,CGS,731732,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
29,130784,10620,Kerala Cricket League 2025,Semi Final 1 (2nd v 3rd),T20,2025-09-05 09:00:00,2025-09-05 12:30:00,Complete,Aries Kollam Sailors won by 10 wkts,2778.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,AKS Won,17.1,9.5,2752,Thrissur Titans,TST,731736,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
30,130778,10620,Kerala Cricket League 2025,30th Match,T20,2025-09-04 13:15:00,2025-09-04 16:45:00,Complete,Thrissur Titans won by 4 wkts,2752.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,TST Won,19.6,18.1,2741,Calicut Globstars,CGS,731732,2752,Thrissur Titans,TST,731736,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
31,123677,10311,Duleep Trophy 2025,2nd Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,107.6,164.3,234,West Zone,WZONE,172287,237,Central Zone,CZONE,172290,1438102,BCCI Centre of Excellence Ground B,Bengaluru,+05:30,13.174092,77.706999
32,123672,10311,Duleep Trophy 2025,1st Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,169.2,100.1,236,South Zone,SZONE,172289,233,North Zone,NZONE,172286,1438087,BCCI Centre of Excellence Ground,Bengaluru,+05:30,12.978853,77.599533
33,113217,9360,County Championship Division One 2025,60th Match,TEST,2025-09-08 09:30:00,2025-09-11 16:30:00,Complete,Nottinghamshire won by 3 wkts,139.0,2025-04-03 00:00:00,2025-09-28 00:00:00,1,Complete,52.5,70.2,147,Worcestershire,WORCS,172214,139,Nottinghamshire,NOTTS,172206,225,New Road,Worcester,+01:00,52.189294,-2.2268
34,116495,9557,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,2025-09-07 08:00:00,2025-09-10 15:00:00,Complete,New Zealand A won by 185 runs,80.0,2025-08-29 00:00:00,2025-09-18 00:00:00,1,NZA Won,128.5,56.1,80,New Zealand A,NZA,172174,268,South Africa A,RSAA,172321,102,Senwes Park,Potchefstroom,+02:00,-26.695565,27.100691
35,133055,10785,Czech Republic Women tour Estonia 2025,1st T20I,T20,2025-09-06 08:00:00,2025-09-06 11:30:00,Complete,Estonia Women won by 1 wkt,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,19.4,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
36,133066,10785,Czech Republic Women tour Estonia 2025,3rd T20I,T20,2025-09-07 07:00:00,2025-09-07 10:30:00,Complete,Estonia Women won by 7 wkts,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,19.5,9.6,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
37,133061,10785,Czech Republic Women tour Estonia 2025,2nd T20I,T20,2025-09-06 12:30:00,2025-09-06 16:00:00,Complete,Estonia Women won by 115 runs,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,12.1,1521,Estonia Women,ESTW,315349,1987,Czech Republic Women,CZEW,501075,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
38,133798,10856,Japan Women tour of Fiji 2025,1st T20I,T20,2025-09-05 02:00:00,2025-09-05 05:30:00,Complete,Japan Women won by 23 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,19.6,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
39,133809,10856,Japan Women tour of Fiji 2025,2nd T20I,T20,2025-09-05 22:00:00,2025-09-06 01:30:00,Complete,Japan Women won by 104 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,12.3,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
40,131675,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Rwanda Women won by 6 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,501,Kenya Women,KENW,172550,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
41,131669,10697,ICC Womens T20 World Cup Africa Region Divisio...,7th Place Play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Nigeria Women won by 85 runs,1482.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NGAW Won,19.6,19.6,1482,Nigeria Women,NGAW,273957,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
42,131647,10697,ICC Womens T20 World Cup Africa Region Divisio...,2nd semi-final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Namibia Women won by 8 wkts,503.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NAMW Won,19.6,13.5,483,Tanzania Women,TANW,172531,503,Namibia Women,NAMW,172552,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
43,131653,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off 2nd Semi-Final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Rwanda Women won by 50 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
44,131686,10697,ICC Womens T20 World Cup Africa Region Divisio...,Final,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Zimbabwe Women won by 9 wkts,388.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,ZIMW Won,19.6,16.3,503,Namibia Women,NAMW,172552,388,Zimbabwe Women,ZIMW,172441,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
45,131664,10697,ICC Womens T20 World Cup Africa Region Divisio...,3rd place play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Tanzania Women won by 6 runs,483.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,TANW Won,19.6,19.4,483,Tanzania Women,TANW,172531,448,Uganda Women,UGAW,172496,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
46,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,19.6,506,Vanuatu Women,VANW,172555,484,Indonesia Women,IDNW,172532,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
47,131774,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Papua New Guinea Women won by 168 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.4,390,Papua New Guinea Women,PNGW,172443,1514,Philippines Women,PHIW,307469,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
48,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,1181.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,FIJIW Won,19.6,17.2,1754,Cook Islands Women,CISW,341074,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
49,131757,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"5th Match, Group B",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Japan Women won by 71 runs,487.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,JPNW Won,19.6,13.5,487,Japan Women,JPNW,248419,482,Samoa Women,WSMW,172530,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
50,131779,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Vanuatu Women won by 7 wkts,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,15.1,1754,Cook Islands Women,CISW,341074,506,Vanuatu Women,VANW,172555,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
51,131741,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"2nd Match, Group B",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Papua New Guinea Women won by 45 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.5,390,Papua New Guinea Women,PNGW,172443,487,Japan Women,JPNW,248419,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
52,131763,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"6th Match, Group A",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Indonesia Women won by 42 runs,484.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,IDNW Won,19.6,19.3,484,Indonesia Women,IDNW,172532,1181,Fiji Women,FIJIW,248411,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
53,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,482.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,WSMW Won,17.3,6.2,1514,Philippines Women,PHIW,307469,482,Samoa Women,WSMW,172530,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
54,122104,10141,Womens Caribbean Premier League 2025,3rd Match,T20,2025-09-10 18:00:00,2025-09-10 21:30:00,Complete,Barbados Royals Women won by 59 runs,1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,15.3,1137,Barbados Royals Women,BRW,241608,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
55,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,17.2,1144,Guyana Amazon Warriors Women,GAWW,241607,1137,Barbados Royals Women,BRW,241608,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
56,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,1144.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,GAWW Won,19.6,19.6,1144,Guyana Amazon Warriors Women,GAWW,241607,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987

In [ ]:
# matchId unique
df_match_list['matchId'].unique()

array([130019, 130008, 105802, 105794, 105788, 131075, 131092, 131086,
       128919, 128908, 122973, 122968, 133187, 133176, 133171, 133160,
       116765, 116774, 116759, 116750, 116741, 116783, 111073, 111069,
       111081, 132637, 132648, 130806, 130795, 130784, 130778, 123677,
       123672, 113217, 116495, 133055, 133066, 133061, 133798, 133809,
       131675, 131669, 131647, 131653, 131686, 131664, 131746, 131774,
       131735, 131757, 131779, 131741, 131763, 131752, 122104, 122093,
       122082])

In [ ]:
# team1id and team2id unique
print(df_match_list['team1_id'].unique())
print(df_match_list['team2_id'].unique())

[   7   96   11    9    3   26   23   12    5  557  262  302  271  159
  150  153  140 2833 2733 2752 2741  234  236  147   80 1987 1521  487
  720 1482  483  503  506  390 1754  484 1514 1137 1144]
[   2    8    9   11    7   96   23  161    5   12  534  263  159 1978
  143  141  119 2844 2800 2778 2741 2752  237  233  139  268 1521 1987
 1181  501  490  503  388  448  484 1514  482  506  487 1139 1137]

In [ ]:
# match_info data fetch and exmine
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/35878"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
response = requests.get(url, headers=headers)
data = response.json()
print(data.keys())

{'matchid': 35878, 'seriesid': 3482, 'seriesname': 'England tour of West Indies, 2022', 'matchdesc': '2nd Test', 'matchformat': 'TEST', 'startdate': 1647439200000, 'enddate': 1647810000000, 'state': 'Complete', 'status': 'Match drawn', 'team1': {'teamid': 10, 'teamname': 'West Indies', 'teamsname': 'WI', 'isfullmember': False, 'isassociated': False, 'isleagueteam': False, 'iswomenteam': False, 'isheader': False, 'isactive': False, 'teampriority': '', 'isvideopresent': False, 'imageid': 0, 'countryname': '', 'belongsto': ''}, 'team2': {'teamid': 9, 'teamname': 'England', 'teamsname': 'ENG', 'isfullmember': False, 'isassociated': False, 'isleagueteam': False, 'iswomenteam': False, 'isheader': False, 'isactive': False, 'teampriority': '', 'isvideopresent': False, 'imageid': 0, 'countryname': '', 'belongsto': ''}, 'umpire1': {'id': 7931, 'name': 'Joel Wilson', 'country': 'WI'}, 'umpire2': {'id': 8275, 'name': 'Nigel Duguid', 'country': 'WI'}, 'umpire3': {'id': 9515, 'name': 'Leslie Reifer', 'country': 'WI'}, 'referee': {'id': 4190, 'name': 'Richie Richardson', 'country': 'WI'}, 'venueinfo': {'id': 55, 'ground': 'Kensington Oval', 'city': 'Bridgetown, Barbados', 'country': 'West Indies', 'timezone': '', 'established': 1871, 'capacity': '28,000', 'knownas': '', 'ends': 'Malcolm Marshall End, Joel Garner End', 'hometeam': 'Barbados', 'floodlights': False, 'curator': '', 'profile': '', 'imageurl': '', 'groundlength': 0.0, 'groundwidth': 0.0, 'othersports': '', 'imageid': '', 'latitude': '', 'longitude': ''}, 'currbatteamid': 0, 'ismatchnotcovered': False, 'appindex': {'seotitle': 'Cricket match facts WI vs ENG 2nd Test,England tour of West Indies, 2022 | Cricbuzz.com', 'weburl': 'http://www.cricbuzz.com/cricket-match-facts/35878/wi-vs-eng-2nd-test-england-tour-of-west-indies-2022'}, 'istournament': False, 'tossstatus': '', 'seriesstartdt': 1647439200000, 'seriesenddt': 1647810000000, 'istimeannounced': False, 'statetitle': '', 'replacematchid': 0, 'livestreamenabled': False, 'isfantasyenabled': False, 'broadcastinfo': [], 'daynight': False, 'matchtype': 'International', 'seriestype': '', 'shortstatus': '', 'boundarytrackervalues': {'boundarytrackervalue': []}, 'matchimageid': 379130, 'islivestreamenabled': False, 'isfantasyhandbookenabled': False}
dict_keys(['matchid', 'seriesid', 'seriesname', 'matchdesc', 'matchformat', 'startdate', 'enddate', 'state', 'status', 'team1', 'team2', 'umpire1', 'umpire2', 'umpire3', 'referee', 'venueinfo', 'currbatteamid', 'ismatchnotcovered', 'appindex', 'istournament', 'tossstatus', 'seriesstartdt', 'seriesenddt', 'istimeannounced', 'statetitle', 'replacematchid', 'livestreamenabled', 'isfantasyenabled', 'broadcastinfo', 'daynight', 'matchtype', 'seriestype', 'shortstatus', 'boundarytrackervalues', 'matchimageid', 'islivestreamenabled', 'isfantasyhandbookenabled'])

In [ ]:
# Extract match info data
match_info_data = {
    'matchid': data.get('matchid'),
    'seriesid': data.get('seriesid'),
    'seriesname': data.get('seriesname'),
    'matchdesc': data.get('matchdesc'),
    'matchformat': data.get('matchformat'),
    'startdate': data.get('startdate'),
    'enddate': data.get('enddate'),
    'state': data.get('state'),
    'status': data.get('status'),
    'team1_id': data.get('team1', {}).get('teamid'),
    'team1_name': data.get('team1', {}).get('teamname'),
    'team2_id': data.get('team2', {}).get('teamid'),
    'team2_name': data.get('team2', {}).get('teamname'),
    'venue_id': data.get('venueinfo', {}).get('id'),
    'ground': data.get('venueinfo', {}).get('ground'),
    'city': data.get('venueinfo', {}).get('city'),
    'timezone': data.get('venueinfo', {}).get('timezone'),
    'latitude': data.get('venueinfo', {}).get('latitude'),
    'longitude': data.get('venueinfo', {}).get('longitude'),
    'currbatteamid': data.get('currbatteamid'),
    'seriesstartdt': data.get('seriesstartdt'),
    'seriesenddt': data.get('seriesenddt'),
    'istimeannounced': data.get('istimeannounced'),
    'statetitle': data.get('statetitle'),
    'shortstatus': data.get('shortstatus')

}

df_match_info_data = pd.DataFrame([match_info_data])
display(df_match_info_data)

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,35878,3482,"England tour of West Indies, 2022",2nd Test,TEST,1647439200000,1647810000000,Complete,Match drawn,10,West Indies,9,England,55,Kensington Oval,"Bridgetown, Barbados",,,,0,1647439200000,1647810000000,False,,

In [ ]:
# convert all date to datetimes column
df_match_info_data['startdate'] = pd.to_datetime(df_match_info_data['startdate'], unit='ms', errors='coerce')

In [ ]:
df_match_info_data

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,35878,3482,"England tour of West Indies, 2022",2nd Test,TEST,2022-03-16 14:00:00,1647810000000,Complete,Match drawn,10,West Indies,9,England,55,Kensington Oval,"Bridgetown, Barbados",,,,0,1647439200000,1647810000000,False,,

In [ ]:
# save this into db deffernt table match info
df_match_info_data.to_sql('match_info', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM match_info', conn_crickbuzz)

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,35878,3482,"England tour of West Indies, 2022",2nd Test,TEST,1647439200000,1647810000000,Complete,Match drawn,10,West Indies,9,England,55,Kensington Oval,"Bridgetown, Barbados",,,,0,1647439200000,1647810000000,0,,

In [ ]:
# save this into db deffernt table match info
df_match_info_data.to_sql('match_info', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM match_info', conn_crickbuzz)

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,1757514600000,1757521480028,Complete,India opt to bowl,2,India,7,United Arab Emirates,153,Dubai International Cricket Stadium,Dubai,+04:00,,,0,1757289600000,1759104000000,0,,IND won

In [ ]:
# show matvh_info table
query = "SELECT * FROM match_info"
df_match_info = pd.read_sql(query, conn_crickbuzz)
df_match_info

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,35878,3482,"England tour of West Indies, 2022",2nd Test,TEST,1647439200000,1647810000000,Complete,Match drawn,10,West Indies,9,England,55,Kensington Oval,"Bridgetown, Barbados",,,,0,1647439200000,1647810000000,0,,

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/35878/team/9"

headers = {
        "x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
data = response.json()
print(data.keys())

{'players': {'playing XI': [{'id': 8345, 'name': 'Alex Lees', 'fullName': 'Alex Lees', 'nickName': 'Lees', 'captain': False, 'role': 'Batsman', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm legbreak', 'teamName': 'England', 'faceImageId': 239485}, {'id': 12770, 'name': 'Zak Crawley', 'fullName': 'Zak Crawley', 'nickName': 'Crawley', 'captain': False, 'role': 'Batsman', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium', 'teamName': 'England', 'faceImageId': 180932}, {'id': 8019, 'name': 'Root', 'fullName': 'Joe Root', 'nickName': 'Root', 'captain': True, 'role': 'Batsman', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak', 'teamName': 'England', 'faceImageId': 170942}, {'id': 10385, 'name': 'Lawrence', 'fullName': 'Daniel Lawrence', 'nickName': 'Lawrence', 'captain': False, 'role': 'Batsman', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak', 'teamName': 'England', 'faceImageId': 158065}, {'id': 6557, 'name': 'Stokes', 'fullName': 'Ben Stokes', 'nickName': 'Stokes', 'captain': False, 'role': 'Batting Allrounder', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 170950}, {'id': 6507, 'name': 'Bairstow', 'fullName': 'Jonny Bairstow', 'nickName': 'Bairstow', 'captain': False, 'role': 'WK-Batsman', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium', 'teamName': 'England', 'faceImageId': 170976}, {'id': 7859, 'name': 'Foakes', 'fullName': 'Ben Foakes', 'nickName': 'Foakes', 'captain': False, 'role': 'WK-Batsman', 'keeper': True, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': '', 'teamName': 'England', 'faceImageId': 239479}, {'id': 6670, 'name': 'Chris Woakes', 'fullName': 'Chris Woakes', 'nickName': 'Woakes', 'captain': False, 'role': 'Bowling Allrounder', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 170964}, {'id': 9392, 'name': 'Fisher', 'fullName': 'Matthew Fisher', 'nickName': 'Fisher', 'captain': False, 'role': 'Bowler', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 182026}, {'id': 8578, 'name': 'Jack Leach', 'fullName': 'Jack Leach', 'nickName': 'Jack Leach', 'captain': False, 'role': 'Bowler', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox', 'teamName': 'England', 'faceImageId': 178391}, {'id': 10394, 'name': 'Saqib Mahmood', 'fullName': 'Saqib Mahmood', 'nickName': 'Saqib Mahmood', 'captain': False, 'role': 'Bowler', 'keeper': False, 'substitute': False, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 156545}], 'bench': [{'id': 11691, 'name': 'Ollie Pope', 'fullName': 'Ollie Pope', 'nickName': 'Ollie Pope', 'captain': False, 'role': 'WK-Batsman', 'keeper': False, 'substitute': True, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': '', 'teamName': 'England', 'faceImageId': 180934}, {'id': 9531, 'name': 'Robinson', 'fullName': 'Ollie Robinson', 'nickName': 'Robinson', 'captain': False, 'role': 'Bowler', 'keeper': False, 'substitute': True, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 240049}, {'id': 10395, 'name': 'Matthew Parkinson', 'fullName': 'Matthew Parkinson', 'nickName': 'Parkinson', 'captain': False, 'role': 'Bowler', 'keeper': False, 'substitute': True, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak', 'teamName': 'England', 'faceImageId': 180930}, {'id': 8511, 'name': 'Craig Overton', 'fullName': 'Craig Overton', 'nickName': 'Craig Overton', 'captain': False, 'role': 'Bowling Allrounder', 'keeper': False, 'substitute': True, 'teamId': 9, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium', 'teamName': 'England', 'faceImageId': 156179}]}}
dict_keys(['players'])

In [ ]:
# Extract player data
player_data = []

if 'players' in data:
    if 'playing XI' in data['players']:
        for player in data['players']['playing XI']:
            player_details = player.copy()
            player_details['squad_type'] = 'Playing XI'
            player_data.append(player_details)

    if 'bench' in data['players']:
        for player in data['players']['bench']:
            player_details = player.copy()
            player_details['squad_type'] = 'Bench'
            player_data.append(player_details)

df_players = pd.DataFrame(player_data)
display(df_players.head())

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type
0,8345,Alex Lees,Alex Lees,Lees,False,Batsman,False,False,9,Left-hand bat,Right-arm legbreak,England,239485,Playing XI
1,12770,Zak Crawley,Zak Crawley,Crawley,False,Batsman,False,False,9,Right-hand bat,Right-arm medium,England,180932,Playing XI
2,8019,Root,Joe Root,Root,True,Batsman,False,False,9,Right-hand bat,Right-arm offbreak,England,170942,Playing XI
3,10385,Lawrence,Daniel Lawrence,Lawrence,False,Batsman,False,False,9,Right-hand bat,Right-arm offbreak,England,158065,Playing XI
4,6557,Stokes,Ben Stokes,Stokes,False,Batting Allrounder,False,False,9,Left-hand bat,Right-arm fast-medium,England,170950,Playing XI

In [ ]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            15 non-null     int64
 1   name          15 non-null     object
 2   fullName      15 non-null     object
 3   nickName      15 non-null     object
 4   captain       15 non-null     bool
 5   role          15 non-null     object
 6   keeper        15 non-null     bool
 7   substitute    15 non-null     bool
 8   teamId        15 non-null     int64
 9   battingStyle  15 non-null     object
 10  bowlingStyle  15 non-null     object
 11  teamName      15 non-null     object
 12  faceImageId   15 non-null     int64
 13  squad_type    15 non-null     object
dtypes: bool(3), int64(3), object(8)
memory usage: 1.5+ KB

In [ ]:
df_players

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type
0,8345,Alex Lees,Alex Lees,Lees,False,Batsman,False,False,9,Left-hand bat,Right-arm legbreak,England,239485,Playing XI
1,12770,Zak Crawley,Zak Crawley,Crawley,False,Batsman,False,False,9,Right-hand bat,Right-arm medium,England,180932,Playing XI
2,8019,Root,Joe Root,Root,True,Batsman,False,False,9,Right-hand bat,Right-arm offbreak,England,170942,Playing XI
3,10385,Lawrence,Daniel Lawrence,Lawrence,False,Batsman,False,False,9,Right-hand bat,Right-arm offbreak,England,158065,Playing XI
4,6557,Stokes,Ben Stokes,Stokes,False,Batting Allrounder,False,False,9,Left-hand bat,Right-arm fast-medium,England,170950,Playing XI
5,6507,Bairstow,Jonny Bairstow,Bairstow,False,WK-Batsman,False,False,9,Right-hand bat,Right-arm medium,England,170976,Playing XI
6,7859,Foakes,Ben Foakes,Foakes,False,WK-Batsman,True,False,9,Right-hand bat,,England,239479,Playing XI
7,6670,Chris Woakes,Chris Woakes,Woakes,False,Bowling Allrounder,False,False,9,Right-hand bat,Right-arm fast-medium,England,170964,Playing XI
8,9392,Fisher,Matthew Fisher,Fisher,False,Bowler,False,False,9,Right-hand bat,Right-arm fast-medium,England,182026,Playing XI
9,8578,Jack Leach,Jack Leach,Jack Leach,False,Bowler,False,False,9,Left-hand bat,Left-arm orthodox,England,178391,Playing XI
10,10394,Saqib Mahmood,Saqib Mahmood,Saqib Mahmood,False,Bowler,False,False,9,Right-hand bat,Right-arm fast-medium,England,156545,Playing XI
11,11691,Ollie Pope,Ollie Pope,Ollie Pope,False,WK-Batsman,False,True,9,Right-hand bat,,England,180934,Bench
12,9531,Robinson,Ollie Robinson,Robinson,False,Bowler,False,True,9,Right-hand bat,Right-arm fast-medium,England,240049,Bench
13,10395,Matthew Parkinson,Matthew Parkinson,Parkinson,False,Bowler,False,True,9,Right-hand bat,Right-arm legbreak,England,180930,Bench
14,8511,Craig Overton,Craig Overton,Craig Overton,False,Bowling Allrounder,False,True,9,Right-hand bat,Right-arm fast-medium,England,156179,Bench

In [ ]:
# save in to players data table
df_players.to_sql('players', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM players', conn_crickbuzz)

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type
0,8345,Alex Lees,Alex Lees,Lees,0,Batsman,0,0,9,Left-hand bat,Right-arm legbreak,England,239485,Playing XI
1,12770,Zak Crawley,Zak Crawley,Crawley,0,Batsman,0,0,9,Right-hand bat,Right-arm medium,England,180932,Playing XI
2,8019,Root,Joe Root,Root,1,Batsman,0,0,9,Right-hand bat,Right-arm offbreak,England,170942,Playing XI
3,10385,Lawrence,Daniel Lawrence,Lawrence,0,Batsman,0,0,9,Right-hand bat,Right-arm offbreak,England,158065,Playing XI
4,6557,Stokes,Ben Stokes,Stokes,0,Batting Allrounder,0,0,9,Left-hand bat,Right-arm fast-medium,England,170950,Playing XI
5,6507,Bairstow,Jonny Bairstow,Bairstow,0,WK-Batsman,0,0,9,Right-hand bat,Right-arm medium,England,170976,Playing XI
6,7859,Foakes,Ben Foakes,Foakes,0,WK-Batsman,1,0,9,Right-hand bat,,England,239479,Playing XI
7,6670,Chris Woakes,Chris Woakes,Woakes,0,Bowling Allrounder,0,0,9,Right-hand bat,Right-arm fast-medium,England,170964,Playing XI
8,9392,Fisher,Matthew Fisher,Fisher,0,Bowler,0,0,9,Right-hand bat,Right-arm fast-medium,England,182026,Playing XI
9,8578,Jack Leach,Jack Leach,Jack Leach,0,Bowler,0,0,9,Left-hand bat,Left-arm orthodox,England,178391,Playing XI
10,10394,Saqib Mahmood,Saqib Mahmood,Saqib Mahmood,0,Bowler,0,0,9,Right-hand bat,Right-arm fast-medium,England,156545,Playing XI
11,11691,Ollie Pope,Ollie Pope,Ollie Pope,0,WK-Batsman,0,1,9,Right-hand bat,,England,180934,Bench
12,9531,Robinson,Ollie Robinson,Robinson,0,Bowler,0,1,9,Right-hand bat,Right-arm fast-medium,England,240049,Bench
13,10395,Matthew Parkinson,Matthew Parkinson,Parkinson,0,Bowler,0,1,9,Right-hand bat,Right-arm legbreak,England,180930,Bench
14,8511,Craig Overton,Craig Overton,Craig Overton,0,Bowling Allrounder,0,1,9,Right-hand bat,Right-arm fast-medium,England,156179,Bench

In [ ]:
# Define the list of match IDs you want to fetch data for
match_ids_to_fetch = [130019, 130008, 105802, 105794, 105788, 131075, 131092, 131086,
       128919, 128908, 122973, 122968, 133187, 133176, 133171, 133160,
       116765, 116774, 116759, 116750, 116741, 116783, 111073, 111069,
       111081, 132637, 132648, 130806, 130795, 130784, 130778, 123677,
       123672, 113217, 116495, 133055, 133066, 133061, 133798, 133809,
       131675, 131669, 131647, 131653, 131686, 131664, 131746, 131774,
       131735, 131757, 131779, 131741, 131763, 131752, 122104, 122093,
       122082]


team_id_fetch = [2,3,5,8,9,11,12,7,26,23,80,96,161,159,151,153,140,141,143,147,119,
                 557,534,262,263,271,302,390,1978,1987,2733,2833,2752, 2844,2800,2778,
                 2741,237,233,234,236,139,268,1521,1181,501,490,503,388,448,483,
                 484,1514,482,506,487,1139,1137,1144,1754,1482,720]

In [ ]:
all_players_data = []

# Iterate through each match in the df_match_list DataFrame
for index, match_row in df_match_list.iterrows():
    match_id = match_row['matchId']
    team1_id = match_row['team1_id']
    team2_id = match_row['team2_id']

    # Skip if team IDs are missing
    if pd.isna(team1_id) or pd.isna(team2_id):
        print(f"Skipping match ID {match_id} due to missing team IDs.")
        continue

    # Convert team IDs to integers if they are not None
    team1_id = int(team1_id)
    team2_id = int(team2_id)


    # Fetch and process player data for team 1
    url_team1 = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id}/team/{team1_id}"
    headers = {
            "x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
            "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    try:
        response1 = requests.get(url_team1, headers=headers)
        response1.raise_for_status()
        data1 = response1.json()

        if 'players' in data1:
            if 'playing XI' in data1['players']:
                for player in data1['players']['playing XI']:
                    player_details = player.copy()
                    player_details['squad_type'] = 'Playing XI'
                    player_details['match_id'] = match_id # Add match_id
                    player_details['team_id'] = team1_id # Add team_id
                    all_players_data.append(player_details)

            if 'bench' in data1['players']:
                for player in data1['players']['bench']:
                    player_details = player.copy()
                    player_details['squad_type'] = 'Bench'
                    player_details['match_id'] = match_id # Add match_id
                    player_details['team_id'] = team1_id # Add team_id
                    all_players_data.append(player_details)

    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for match ID {match_id}, team ID {team1_id}: {e}")


    # Fetch and process player data for team 2
    url_team2 = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id}/team/{team2_id}"


    try:
        response2 = requests.get(url_team2, headers=headers)
        response2.raise_for_status()
        data2 = response2.json()

        if 'players' in data2:
            if 'playing XI' in data2['players']:
                for player in data2['players']['playing XI']:
                    player_details = player.copy()
                    player_details['squad_type'] = 'Playing XI'
                    player_details['match_id'] = match_id # Add match_id
                    player_details['team_id'] = team2_id # Add team_id
                    all_players_data.append(player_details)

            if 'bench' in data2['players']:
                for player in data2['players']['bench']:
                    player_details = player.copy()
                    player_details['squad_type'] = 'Bench'
                    player_details['match_id'] = match_id # Add match_id
                    player_details['team_id'] = team2_id # Add team_id
                    all_players_data.append(player_details)

    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for match ID {match_id}, team ID {team2_id}: {e}")


df_all_players = pd.DataFrame(all_players_data)
display(df_all_players.head())

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,True,Batsman,False,False,7,RIGHT,Right Arm medium,UAE,244736,Playing XI,130019,7,NaN,NaN,NaN,NaN,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,False,Batting Allrounder,False,False,7,RIGHT,Right Arm medium,UAE,244727,Playing XI,130019,7,NaN,NaN,NaN,NaN,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,False,Batsman,False,False,7,LEFT,Left arm orthodox,UAE,182026,Playing XI,130019,7,NaN,NaN,NaN,NaN,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,False,WK-Batsman,True,False,7,RIGHT,,UAE,182026,Playing XI,130019,7,NaN,NaN,NaN,NaN,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,False,Batsman,False,False,7,RIGHT,Right Arm off break,UAE,182026,Playing XI,130019,7,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_all_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1799 entries, 0 to 1798
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1799 non-null   int64
 1   name             1799 non-null   object
 2   fullName         1799 non-null   object
 3   nickName         1799 non-null   object
 4   captain          1720 non-null   object
 5   role             1799 non-null   object
 6   keeper           1720 non-null   object
 7   substitute       1720 non-null   object
 8   teamId           1799 non-null   int64
 9   battingStyle     1720 non-null   object
 10  bowlingStyle     1720 non-null   object
 11  teamName         1196 non-null   object
 12  faceImageId      1799 non-null   int64
 13  squad_type       1799 non-null   object
 14  match_id         1799 non-null   int64
 15  team_id          1799 non-null   int64
 16  isSupportStaff   79 non-null     object
 17  playingXIChange  184 non-null    object
 18  isOverseas       47 non-null     object
 19  inMatchChange    20 non-null     object
 20  splSubstitute    42 non-null     object
dtypes: int64(5), object(16)
memory usage: 295.3+ KB

In [ ]:
df_all_players['isOverseas'].unique()

array([nan, True, False], dtype=object)

In [ ]:
# save this data to cricket db as player data new table
df_all_players.to_sql('players', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM players', conn_crickbuzz)

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,1.0,Batsman,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244736,Playing XI,130019,7,NaN,None,NaN,None,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,0.0,Batting Allrounder,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244727,Playing XI,130019,7,NaN,None,NaN,None,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,0.0,Batsman,0.0,0.0,7,LEFT,Left arm orthodox,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,0.0,WK-Batsman,1.0,0.0,7,RIGHT,,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,0.0,Batsman,0.0,0.0,7,RIGHT,Right Arm off break,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,23956,Jannillea Glasgow,Jannillea Glasgow,Jannillea Glasgow,0.0,Bowling Allrounder,0.0,0.0,1139,LEFT,Right Arm fast medium,None,227429,Playing XI,122082,1139,NaN,None,NaN,None,NaN
1795,1449536,Abigail Bryce,Abigail Bryce,Abigail Bryce,0.0,Batsman,0.0,1.0,1139,RIGHT,Right Arm off break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1796,28731,Keila Elliott,Keila Elliott,Keila Elliott,0.0,Bowling Allrounder,0.0,1.0,1139,RIGHT,Right Arm leg break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1797,1430401,Nerissa Crafton,Nerissa Crafton,Nerissa Crafton,0.0,Batsman,0.0,1.0,1139,LEFT,,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1798,15702,Shawnisha Hector,Shawnisha Hector,Shawnisha Hector,0.0,Bowler,0.0,1.0,1139,RIGHT,Right Arm medium,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN

In [ ]:
# show table name
tables = cursor.fetchall()
for table in tables:
    print(table[0])

match_list
players
venue_stats

In [ ]:
query = "SELECT * FROM venue_stats"
df_venue_s = pd.read_sql(query, conn_crickbuzz)
df_venue_s

,ground,city,country,timezone,capacity,knownAs,ends,homeTeam,floodlights,curator,imageUrl,imageId,established
0,Dubai International Cricket Stadium,Dubai,United Arab Emirates,+04:00,25000,Dubai Sports City Cricket Stadium,"Emirates Road End, Dubai Sports City End",United Arab Emirates,1.0,Tony Hemming,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731713,NaN
1,Sheikh Zayed Stadium,Abu Dhabi,United Arab Emirates,+04:00,20000,President His Highness Sheikh Zayed bin Sulta...,"North End, Pavilion End",United Arab Emirates,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731716,2004.0
2,Sophia Gardens,Cardiff,Wales,+01:00,20500,The SWALEC Stadium,"River Taff End, Cathedral Road End",Glamorgan,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
3,The Rose Bowl,Southampton,England,+01:00,26500,"The Ageas Bowl, West End","Pavilion End, Northern End","Hampshire, Hampshire 2nd XI",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2001.0
4,Lord's,London,England,+01:00,30000,Lord's Cricket Ground,"Pavilion End, Nursery End","Marylebone Cricket Club, Middlesex",1.0,Mick Hunt,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717711,1814.0
5,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,+04:00,16000,None,"Pavilion End, Sharjah Club End",United Arab Emirates,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731715,1982.0
6,Maple Leaf North-West Ground,King City,Canada,-04:00,55000,"Maple Leaf 1A, Ground 1","Northern End, Southern End",Canada,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
7,Harare Sports Club,Harare,Zimbabwe,+02:00,10000,Salisbury Sports Club,"City End, Club House End","Rhodesia, Zimbabwe, Mashonaland",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
8,Cronkbourne Sports and Social Club Ground,Tromode,Isle of Man,+01:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
9,Kensington Oval,"Bridgetown, Barbados",West Indies,-04:00,28000,Pickwick Cricket Club,"Malcolm Marshall End, Joel Garner End",Barbados,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717738,1871.0
10,Providence Stadium,Guyana,West Indies,-04:00,15000,Guyana National Stadium,"Media Centre End, Pavillion End",None,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2006.0
11,Emirates Old Trafford,Manchester,England,+01:00,19000,None,"Stretford End, Brian Statham End",Lancashire,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717716,1857.0
12,Riverside Ground,Chester-le-Street,England,+01:00,22000,None,"Finchale End, Lumley End",Durham,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1995.0
13,The Cooper Associates County Ground,Taunton,England,+01:00,6500,Athletic Ground,"River End, Old Pavilion End",Somerset,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1882.0
14,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India,+05:30,50000,Ekana International Cricket Stadium,None,"Uttar Pradesh, Lucknow Super Giants",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2017.0
15,Greenfield International Stadium,Thiruvananthapuram,India,+05:30,50000,Trivandrum International Stadium,None,None,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
16,BCCI Centre of Excellence Ground B,Bengaluru,India,+05:30,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
17,BCCI Centre of Excellence Ground,Bengaluru,India,+05:30,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
18,New Road,Worcester,England,+01:00,4500,None,"New Road End, Diglis End",Worcestershire,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1899.0
19,Senwes Park,Potchefstroom,South Africa,+02:00,55000,"North West Cricket Stadium Sedgars Park, Potch...","Cargo Motors End, University End","South Africa, North West",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
20,Albert Park 1,Suva,Fiji,+12:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
21,High Performance Oval,Windhoek,Namibia,+02:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
22,Namibia Cricket Ground,Windhoek,Namibia,+02:00,55000,None,None,Namibia,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
23,Albert Park 2,Suva,Fiji,+12:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN

In [ ]:
# show match list table
query = "SELECT * FROM match_list"
df_match_list = pd.read_sql(query, conn_crickbuzz)
df_match_list

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,IND Won,13.1,4.3,7,United Arab Emirates,UAE,172121,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,Complete,7.5,4.6,11,South Africa,RSA,172126,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
5,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
6,131092,10642,United Arab Emirates T20I Tri-Series 2025,Final,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Pakistan won by 75 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,15.5,3,Pakistan,PAK,591986,96,Afghanistan,AFG,172188,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
7,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,96.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
8,128919,7572,ICC Cricket World Cup League Two 2023-27,85th Match,ODI,2025-09-06 14:30:00,2025-09-06 22:30:00,Abandon,Match abandoned due to wet outfield (no toss),487.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,Abandon,19.6,19.6,26,Canada,CAN,172140,23,Scotland,SCO,172137,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
9,128908,7572,ICC Cricket World Cup League Two 2023-27,84th Match,ODI,2025-09-04 14:30:00,2025-09-04 22:30:00,Complete,Scotland won by 55 runs (24 overs game due to ...,23.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,SCO Won,23.6,21.2,23,Scotland,SCO,172137,161,Namibia,NAM,172229,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
10,122973,10267,"Sri Lanka tour of Zimbabwe, 2025",3rd T20I,T20,2025-09-07 11:30:00,2025-09-07 15:00:00,Complete,Sri Lanka won by 8 wkts,5.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,SL Won,19.6,17.4,12,Zimbabwe,ZIM,172127,5,Sri Lanka,SL,172119,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
11,122968,10267,"Sri Lanka tour of Zimbabwe, 2025",2nd T20I,T20,2025-09-06 11:30:00,2025-09-06 15:00:00,Complete,Zimbabwe won by 5 wkts,12.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,ZIM Won,17.4,14.2,5,Sri Lanka,SL,172119,12,Zimbabwe,ZIM,172127,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
12,133187,10812,Sweden tour of Isle Of Man 2025,4th Match,T20,2025-09-07 14:30:00,2025-09-07 18:00:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
13,133176,10812,Sweden tour of Isle Of Man 2025,3rd T20I,T20,2025-09-07 10:00:00,2025-09-07 13:30:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
14,133171,10812,Sweden tour of Isle Of Man 2025,2nd T20I,T20,2025-09-06 14:30:00,2025-09-06 18:00:00,Complete,Sweden won by 3 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,19.5,14.3,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
15,133160,10812,Sweden tour of Isle Of Man 2025,1st T20I,T20,2025-09-06 10:00:00,2025-09-06 13:30:00,Complete,Sweden won by 10 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,16.1,10.5,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
16,116765,9575,Caribbean Premier League 2025,24th Match,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Barbados Royals won by 27 runs,262.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,BR Won,19.6,19.6,262,Barbados Royals,BR,210485,263,Saint Lucia Kings,SLK,172316,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
17,116774,9575,Caribbean Premier League 2025,25th Match,T20,2025-09-08 00:00:00,2025-09-08 03:30:00,Complete,St Kitts and Nevis Patriots won by 5 runs,302.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,SNP Won,19.6,19.6,302,St Kitts and Nevis Patriots,SNP,172351,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
18,116759,9575,Caribbean Premier League 2025,23rd Match,T20,2025-09-06 23:00:00,2025-09-07 02:30:00,Complete,Guyana Amazon Warriors won by 3 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.5,271,Trinbago Knight Riders,TKR,172325,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
19,116750,9575,Caribbean Premier League 2025,22nd Match,T20,2025-09-05 23:00:00,2025-09-06 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,19.6,19.6,262,Barbados Royals,BR,210485,1978,Antigua and Barbuda Falcons,ABF,507236,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
20,116741,9575,Caribbean Premier League 2025,21st Match,T20,2025-09-04 23:00:00,2025-09-05 02:30:00,Complete,Guyana Amazon Warriors won by 4 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.4,262,Barbados Royals,BR,210485,159,Guyana Amazon Warriors,GAW,172227,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
21,116783,9575,Caribbean Premier League 2025,26th Match,T20,2025-09-10 23:00:00,2025-09-11 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,18.1,19.1,159,Guyana Amazon Warriors,GAW,172227,1978,Antigua and Barbuda Falcons,ABF,507236,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
22,111073,9257,T20 Blast 2025,Quarter Final 3,T20,2025-09-06 13:30:00,2025-09-06 17:00:00,Complete,Lancashire won by 3 wkts,143.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,LANCS Won,19.6,18.3,150,Kent,KENT,172217,143,Lancashire,LANCS,172210,65,Emirates Old Trafford,Manchester,+01:00,53.463066,-2.291301
23,111069,9257,T20 Blast 2025,Quarter Final 2,T20,2025-09-05 17:30:00,2025-09-05 21:00:00,Complete,Hampshire won by 26 runs,153.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,HAM Won,19.6,19.6,153,Hampshire,HAM,172220,141,Durham,DUR,172208,60,Riverside Ground,Chester-le-Street,+01:00,54.849531,-1.56103
24,111081,9257,T20 Blast 2025,Quarter Final 4,T20,2025-09-06 17:30:00,2025-09-06 21:00:00,Complete,Somerset won by 4 wkts,119.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,SOM Won,19.6,19.5,140,Warwickshire,WARKS,172207,119,Somerset,SOM,172199,223,The Cooper Associates County Ground,Taunton,+01:00,51.018913,3.100894
25,132637,10735,Uttar Pradesh Premier League 2025,Qualifier 2,T20,2025-09-04 14:00:00,2025-09-04 17:30:00,Complete,Meerut Mavericks won by 19 runs,2833.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,MRM Won,19.6,19.6,2833,Meerut Mavericks,MRM,738654,2844,Lucknow Falcons,LFC,738651,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
26,132648,10735,Uttar Pradesh Premier League 2025,Final,T20,2025-09-06 14:00:00,2025-09-06 17:30:00,Complete,Kashi Rudras won by 8 wkts,2800.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,KRD Won,19.6,15.4,2833,Meerut Mavericks,MRM,738654,2800,Kashi Rudras,KRD,738657,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
27,130806,10620,Kerala Cricket League 2025,Final,T20,2025-09-07 13:15:00,2025-09-07 16:45:00,Complete,Kochi Blue Tigers won by 75 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,16.3,2733,Kochi Blue Tigers,KBT,731734,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
28,130795,10620,Kerala Cricket League 2025,Semi Final 2 (1st v 4th),T20,2025-09-05 13:15:00,2025-09-05 16:45:00,Complete,Kochi Blue Tigers won by 15 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,19.6,2733,Kochi Blue Tigers,KBT,731734,2741,Calicut Globstars,CGS,731732,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
29,130784,10620,Kerala Cricket League 2025,Semi Final 1 (2nd v 3rd),T20,2025-09-05 09:00:00,2025-09-05 12:30:00,Complete,Aries Kollam Sailors won by 10 wkts,2778.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,AKS Won,17.1,9.5,2752,Thrissur Titans,TST,731736,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
30,130778,10620,Kerala Cricket League 2025,30th Match,T20,2025-09-04 13:15:00,2025-09-04 16:45:00,Complete,Thrissur Titans won by 4 wkts,2752.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,TST Won,19.6,18.1,2741,Calicut Globstars,CGS,731732,2752,Thrissur Titans,TST,731736,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
31,123677,10311,Duleep Trophy 2025,2nd Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,107.6,164.3,234,West Zone,WZONE,172287,237,Central Zone,CZONE,172290,1438102,BCCI Centre of Excellence Ground B,Bengaluru,+05:30,13.174092,77.706999
32,123672,10311,Duleep Trophy 2025,1st Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,169.2,100.1,236,South Zone,SZONE,172289,233,North Zone,NZONE,172286,1438087,BCCI Centre of Excellence Ground,Bengaluru,+05:30,12.978853,77.599533
33,113217,9360,County Championship Division One 2025,60th Match,TEST,2025-09-08 09:30:00,2025-09-11 16:30:00,Complete,Nottinghamshire won by 3 wkts,139.0,2025-04-03 00:00:00,2025-09-28 00:00:00,1,Complete,52.5,70.2,147,Worcestershire,WORCS,172214,139,Nottinghamshire,NOTTS,172206,225,New Road,Worcester,+01:00,52.189294,-2.2268
34,116495,9557,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,2025-09-07 08:00:00,2025-09-10 15:00:00,Complete,New Zealand A won by 185 runs,80.0,2025-08-29 00:00:00,2025-09-18 00:00:00,1,NZA Won,128.5,56.1,80,New Zealand A,NZA,172174,268,South Africa A,RSAA,172321,102,Senwes Park,Potchefstroom,+02:00,-26.695565,27.100691
35,133055,10785,Czech Republic Women tour Estonia 2025,1st T20I,T20,2025-09-06 08:00:00,2025-09-06 11:30:00,Complete,Estonia Women won by 1 wkt,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,19.4,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
36,133066,10785,Czech Republic Women tour Estonia 2025,3rd T20I,T20,2025-09-07 07:00:00,2025-09-07 10:30:00,Complete,Estonia Women won by 7 wkts,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,19.5,9.6,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
37,133061,10785,Czech Republic Women tour Estonia 2025,2nd T20I,T20,2025-09-06 12:30:00,2025-09-06 16:00:00,Complete,Estonia Women won by 115 runs,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,12.1,1521,Estonia Women,ESTW,315349,1987,Czech Republic Women,CZEW,501075,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
38,133798,10856,Japan Women tour of Fiji 2025,1st T20I,T20,2025-09-05 02:00:00,2025-09-05 05:30:00,Complete,Japan Women won by 23 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,19.6,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
39,133809,10856,Japan Women tour of Fiji 2025,2nd T20I,T20,2025-09-05 22:00:00,2025-09-06 01:30:00,Complete,Japan Women won by 104 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,12.3,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
40,131675,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Rwanda Women won by 6 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,501,Kenya Women,KENW,172550,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
41,131669,10697,ICC Womens T20 World Cup Africa Region Divisio...,7th Place Play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Nigeria Women won by 85 runs,1482.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NGAW Won,19.6,19.6,1482,Nigeria Women,NGAW,273957,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
42,131647,10697,ICC Womens T20 World Cup Africa Region Divisio...,2nd semi-final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Namibia Women won by 8 wkts,503.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NAMW Won,19.6,13.5,483,Tanzania Women,TANW,172531,503,Namibia Women,NAMW,172552,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
43,131653,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off 2nd Semi-Final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Rwanda Women won by 50 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
44,131686,10697,ICC Womens T20 World Cup Africa Region Divisio...,Final,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Zimbabwe Women won by 9 wkts,388.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,ZIMW Won,19.6,16.3,503,Namibia Women,NAMW,172552,388,Zimbabwe Women,ZIMW,172441,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
45,131664,10697,ICC Womens T20 World Cup Africa Region Divisio...,3rd place play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Tanzania Women won by 6 runs,483.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,TANW Won,19.6,19.4,483,Tanzania Women,TANW,172531,448,Uganda Women,UGAW,172496,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
46,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,19.6,506,Vanuatu Women,VANW,172555,484,Indonesia Women,IDNW,172532,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
47,131774,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Papua New Guinea Women won by 168 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.4,390,Papua New Guinea Women,PNGW,172443,1514,Philippines Women,PHIW,307469,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
48,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,1181.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,FIJIW Won,19.6,17.2,1754,Cook Islands Women,CISW,341074,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
49,131757,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"5th Match, Group B",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Japan Women won by 71 runs,487.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,JPNW Won,19.6,13.5,487,Japan Women,JPNW,248419,482,Samoa Women,WSMW,172530,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
50,131779,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Vanuatu Women won by 7 wkts,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,15.1,1754,Cook Islands Women,CISW,341074,506,Vanuatu Women,VANW,172555,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
51,131741,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"2nd Match, Group B",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Papua New Guinea Women won by 45 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.5,390,Papua New Guinea Women,PNGW,172443,487,Japan Women,JPNW,248419,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
52,131763,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"6th Match, Group A",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Indonesia Women won by 42 runs,484.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,IDNW Won,19.6,19.3,484,Indonesia Women,IDNW,172532,1181,Fiji Women,FIJIW,248411,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
53,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,482.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,WSMW Won,17.3,6.2,1514,Philippines Women,PHIW,307469,482,Samoa Women,WSMW,172530,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
54,122104,10141,Womens Caribbean Premier League 2025,3rd Match,T20,2025-09-10 18:00:00,2025-09-10 21:30:00,Complete,Barbados Royals Women won by 59 runs,1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,15.3,1137,Barbados Royals Women,BRW,241608,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
55,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,17.2,1144,Guyana Amazon Warriors Women,GAWW,241607,1137,Barbados Royals Women,BRW,241608,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
56,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,1144.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,GAWW Won,19.6,19.6,1144,Guyana Amazon Warriors Women,GAWW,241607,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987

In [ ]:
# show match info table
query = "SELECT * FROM match_info"
df_match_info = pd.read_sql(query, conn_crickbuzz)
df_match_info

,matchid,seriesid,seriesname,matchdesc,matchformat,startdate,enddate,state,status,team1_id,team1_name,team2_id,team2_name,venue_id,ground,city,timezone,latitude,longitude,currbatteamid,seriesstartdt,seriesenddt,istimeannounced,statetitle,shortstatus
0,35878,3482,"England tour of West Indies, 2022",2nd Test,TEST,1647439200000,1647810000000,Complete,Match drawn,10,West Indies,9,England,55,Kensington Oval,"Bridgetown, Barbados",,,,0,1647439200000,1647810000000,0,,

In [ ]:
# Drop the 'match_info' table from the database
cursor = conn_crickbuzz.cursor()
cursor.execute("DROP TABLE IF EXISTS match_info;")
conn_crickbuzz.commit()

print("Table 'match_info' dropped successfully.")

# Verify by showing the tables in the database
query = "SELECT name FROM sqlite_master WHERE type='table';"
cursor.execute(query)
tables = cursor.fetchall()
print("\nTables remaining in the database:")
for table in tables:
    print(table[0])

Table 'match_info' dropped successfully.

Tables remaining in the database:
match_list
players

In [ ]:
# show playes table
query = "SELECT * FROM players"
df_players = pd.read_sql(query, conn_crickbuzz)
df_players

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,1.0,Batsman,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244736,Playing XI,130019,7,NaN,None,NaN,None,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,0.0,Batting Allrounder,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244727,Playing XI,130019,7,NaN,None,NaN,None,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,0.0,Batsman,0.0,0.0,7,LEFT,Left arm orthodox,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,0.0,WK-Batsman,1.0,0.0,7,RIGHT,,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,0.0,Batsman,0.0,0.0,7,RIGHT,Right Arm off break,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,23956,Jannillea Glasgow,Jannillea Glasgow,Jannillea Glasgow,0.0,Bowling Allrounder,0.0,0.0,1139,LEFT,Right Arm fast medium,None,227429,Playing XI,122082,1139,NaN,None,NaN,None,NaN
1795,1449536,Abigail Bryce,Abigail Bryce,Abigail Bryce,0.0,Batsman,0.0,1.0,1139,RIGHT,Right Arm off break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1796,28731,Keila Elliott,Keila Elliott,Keila Elliott,0.0,Bowling Allrounder,0.0,1.0,1139,RIGHT,Right Arm leg break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1797,1430401,Nerissa Crafton,Nerissa Crafton,Nerissa Crafton,0.0,Batsman,0.0,1.0,1139,LEFT,,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1798,15702,Shawnisha Hector,Shawnisha Hector,Shawnisha Hector,0.0,Bowler,0.0,1.0,1139,RIGHT,Right Arm medium,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN

In [ ]:
# showplayer details where team id 2
query = "SELECT * FROM players WHERE team_id = 2"
df_players = pd.read_sql(query, conn_crickbuzz)
df_players
#

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,12086,Abhishek Sharma,Abhishek Sharma,Abhishek Sharma,0.0,Batting Allrounder,0.0,0.0,2,LEFT,Left arm orthodox,IND,153963,Playing XI,130019,2,NaN,None,None,None,None
1,11808,Shubman Gill,Shubman Gill,Gill,0.0,Batsman,0.0,0.0,2,RIGHT,Right Arm off break,IND,616515,Playing XI,130019,2,NaN,None,None,None,None
2,7915,Suryakumar Yadav,Suryakumar Yadav,Suryakumar Yadav,1.0,Batsman,0.0,0.0,2,RIGHT,Right Arm off break,IND,352481,Playing XI,130019,2,NaN,None,None,None,None
3,14504,Tilak Varma,Tilak Varma,Tilak Varma,0.0,Batsman,0.0,0.0,2,LEFT,Right Arm off break,IND,226525,Playing XI,130019,2,NaN,None,None,None,None
4,8271,Samson,Sanju Samson,Samson,0.0,WK-Batsman,1.0,0.0,2,RIGHT,,IND,226289,Playing XI,130019,2,NaN,None,None,None,None
5,11195,Shivam Dube,Shivam Dube,Shivam Dube,0.0,Batting Allrounder,0.0,0.0,2,LEFT,Right Arm medium,IND,593805,Playing XI,130019,2,NaN,None,None,None,None
6,9647,Hardik Pandya,Hardik Pandya,Hardik Pandya,0.0,Batting Allrounder,0.0,0.0,2,RIGHT,Right Arm fast medium,IND,616519,Playing XI,130019,2,NaN,None,None,None,None
7,8808,Axar,Axar Patel,Axar,0.0,Bowling Allrounder,0.0,0.0,2,LEFT,Left arm orthodox,IND,616521,Playing XI,130019,2,NaN,None,None,None,None
8,8292,Kuldeep Yadav,Kuldeep Yadav,Kuldeep Yadav,0.0,Bowler,0.0,0.0,2,LEFT,,IND,616525,Playing XI,130019,2,NaN,None,None,None,None
9,9311,Bumrah,Jasprit Bumrah,Bumrah,0.0,Bowler,0.0,0.0,2,RIGHT,Right Arm fast,IND,591949,Playing XI,130019,2,NaN,None,None,None,None
10,12926,Varun Chakaravarthy,Varun Chakaravarthy,Varun Chakaravarthy,0.0,Bowler,0.0,0.0,2,RIGHT,Right Arm leg break,IND,616528,Playing XI,130019,2,NaN,None,None,None,None
11,10214,Jitesh Sharma,Jitesh Sharma,Jitesh Sharma,0.0,WK-Batsman,0.0,1.0,2,RIGHT,,IND,226474,Bench,130019,2,NaN,None,None,None,None
12,24729,Harshit Rana,Harshit Rana,Harshit Rana,0.0,Bowler,0.0,1.0,2,RIGHT,Right Arm fast medium,IND,616529,Bench,130019,2,NaN,None,None,None,None
13,10896,Rinku Singh,Rinku Singh,Rinku Singh,0.0,Batsman,0.0,1.0,2,LEFT,Right Arm off break,IND,279125,Bench,130019,2,NaN,None,None,None,None
14,13217,Arshdeep Singh,Arshdeep Singh,Arshdeep Singh,0.0,Bowler,0.0,1.0,2,LEFT,Left Arm fast medium,IND,616527,Bench,130019,2,NaN,None,None,None,None
15,308,Gautam Gambhir,Gautam Gambhir,Gambhir,NaN,Head Coach,NaN,NaN,2,None,None,IND,154519,Bench,130019,2,1.0,None,None,None,None
16,640,Ryan ten Doeschate,Ryan ten Doeschate,ten Doeschate,NaN,Assistant coach,NaN,NaN,2,None,None,IND,155932,Bench,130019,2,1.0,None,None,None,None
17,45950,T Dilip,T Dilip,T Dilip,NaN,Fielding Coach,NaN,NaN,2,None,None,IND,182026,Bench,130019,2,1.0,None,None,None,None
18,608,Morne Morkel,Morne Morkel,Morne Morkel,NaN,Bowling Coach,NaN,NaN,2,None,None,IND,157278,Bench,130019,2,1.0,None,None,None,None
19,8851,Sitanshu Kotak,Sitanshu Kotak,Kotak,NaN,Batting Coach,NaN,NaN,2,None,None,IND,182026,Bench,130019,2,1.0,None,None,None,None

In [ ]:
# all unique venue id
query = "SELECT DISTINCT venue_id FROM match_list"
df_venue_id = pd.read_sql(query, conn_crickbuzz)
df_venue_id

    venue_id
0        153
1         94
2         62
3         21
4         19
5        140
6        139
7         69
8    1438142
9         55
10       110
11        65
12        60
13       223
14       485
15       506
16   1438102
17   1438087
18       225
19       102
20      1552
21   1438120
22   1438052
23   1438021
24   1438123

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/venues/v1/45"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'ground': 'Basin Reserve', 'city': 'Wellington', 'country': 'New Zealand', 'timezone': '+13:00', 'capacity': '11,600', 'ends': 'Vance Stand End, Scoreboard End', 'homeTeam': 'Wellington', 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/45.jpg', 'imageId': '189174'}

In [ ]:
venue_details_list = []

# Iterate through unique venue IDs
for venue_id in df_venue_id['venue_id']:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{venue_id}"
    headers = {
        "x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        venue_data = response.json()
        venue_details_list.append(venue_data)

    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for venue ID {venue_id}: {e}")
        continue # Continue to the next venue if there's an error

# Create a DataFrame from the fetched venue details
df_all_venues = pd.DataFrame(venue_details_list)
display(df_all_venues.head())

Error fetching data for venue ID 1552: 500 Server Error: Internal Server Error for url: https://cricbuzz-cricket.p.rapidapi.com/venues/v1/1552

,ground,city,country,timezone,capacity,knownAs,ends,homeTeam,floodlights,curator,imageUrl,imageId,established
0,Dubai International Cricket Stadium,Dubai,United Arab Emirates,+04:00,"25,000",Dubai Sports City Cricket Stadium,"Emirates Road End, Dubai Sports City End",United Arab Emirates,True,Tony Hemming,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731713,NaN
1,Sheikh Zayed Stadium,Abu Dhabi,United Arab Emirates,+04:00,"20,000",President His Highness Sheikh Zayed bin Sulta...,"North End, Pavilion End",United Arab Emirates,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731716,2004.0
2,Sophia Gardens,Cardiff,Wales,+01:00,"5500 (15,000 after redevelopment)",The SWALEC Stadium,"River Taff End, Cathedral Road End",Glamorgan,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
3,The Rose Bowl,Southampton,England,+01:00,"6,500 (20,000 with temporary seating)","The Ageas Bowl, West End","Pavilion End, Northern End","Hampshire, Hampshire 2nd XI",True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2001.0
4,Lord's,London,England,+01:00,30000,Lord's Cricket Ground,"Pavilion End, Nursery End","Marylebone Cricket Club, Middlesex",True,Mick Hunt,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717711,1814.0

In [ ]:
df_all_venues.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ground       24 non-null     object
 1   city         24 non-null     object
 2   country      24 non-null     object
 3   timezone     24 non-null     object
 4   capacity     24 non-null     Int64
 5   knownAs      13 non-null     object
 6   ends         15 non-null     object
 7   homeTeam     16 non-null     object
 8   floodlights  13 non-null     object
 9   curator      2 non-null      object
 10  imageUrl     24 non-null     object
 11  imageId      24 non-null     object
 12  established  11 non-null     float64
dtypes: Int64(1), float64(1), object(11)
memory usage: 2.6+ KB

In [ ]:
# capicty uniq
df_all_venues['capacity'].unique()

array(['25,000', '20,000', '20500', '26500', '30000', '16,000', nan,
       '10,000', '28,000', '15,000', '19000', '22000', '6500', '50000',
       '4500'], dtype=object)

In [ ]:
# '5500 (15,000 after redevelopment)' in capacity replace with '20500'
df_all_venues['capacity'] = df_all_venues['capacity'].replace('5500 (15,000 after redevelopment)', '20500')

In [ ]:
# '6,500 (20,000 with temporary seating)' replace with '26500'
df_all_venues['capacity'] = df_all_venues['capacity'].replace('6,500 (20,000 with temporary seating)', '26500')

In [ ]:
# '5000 (17000 for internationals)' replace with '22000'
df_all_venues['capacity'] = df_all_venues['capacity'].replace('5000 (17000 for internationals)', '22000')

In [ ]:
# remove  '' and convert to int in capacity column
df_all_venues['capacity'] = df_all_venues['capacity'].str.replace(',', '',regex=True).astype(float).astype('Int64')

In [ ]:
df_all_venues

,ground,city,country,timezone,capacity,knownAs,ends,homeTeam,floodlights,curator,imageUrl,imageId,established
0,Dubai International Cricket Stadium,Dubai,United Arab Emirates,+04:00,25000,Dubai Sports City Cricket Stadium,"Emirates Road End, Dubai Sports City End",United Arab Emirates,True,Tony Hemming,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731713,NaN
1,Sheikh Zayed Stadium,Abu Dhabi,United Arab Emirates,+04:00,20000,President His Highness Sheikh Zayed bin Sulta...,"North End, Pavilion End",United Arab Emirates,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731716,2004.0
2,Sophia Gardens,Cardiff,Wales,+01:00,20500,The SWALEC Stadium,"River Taff End, Cathedral Road End",Glamorgan,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
3,The Rose Bowl,Southampton,England,+01:00,26500,"The Ageas Bowl, West End","Pavilion End, Northern End","Hampshire, Hampshire 2nd XI",True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2001.0
4,Lord's,London,England,+01:00,30000,Lord's Cricket Ground,"Pavilion End, Nursery End","Marylebone Cricket Club, Middlesex",True,Mick Hunt,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717711,1814.0
5,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,+04:00,16000,NaN,"Pavilion End, Sharjah Club End",United Arab Emirates,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731715,1982.0
6,Maple Leaf North-West Ground,King City,Canada,-04:00,55000,"Maple Leaf 1A, Ground 1","Northern End, Southern End",Canada,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
7,Harare Sports Club,Harare,Zimbabwe,+02:00,10000,Salisbury Sports Club,"City End, Club House End","Rhodesia, Zimbabwe, Mashonaland",True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
8,Cronkbourne Sports and Social Club Ground,Tromode,Isle of Man,+01:00,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
9,Kensington Oval,"Bridgetown, Barbados",West Indies,-04:00,28000,Pickwick Cricket Club,"Malcolm Marshall End, Joel Garner End",Barbados,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717738,1871.0
10,Providence Stadium,Guyana,West Indies,-04:00,15000,Guyana National Stadium,"Media Centre End, Pavillion End",NaN,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2006.0
11,Emirates Old Trafford,Manchester,England,+01:00,19000,NaN,"Stretford End, Brian Statham End",Lancashire,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717716,1857.0
12,Riverside Ground,Chester-le-Street,England,+01:00,22000,NaN,"Finchale End, Lumley End",Durham,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1995.0
13,The Cooper Associates County Ground,Taunton,England,+01:00,6500,Athletic Ground,"River End, Old Pavilion End",Somerset,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1882.0
14,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India,+05:30,50000,Ekana International Cricket Stadium,NaN,"Uttar Pradesh, Lucknow Super Giants",True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2017.0
15,Greenfield International Stadium,Thiruvananthapuram,India,+05:30,50000,Trivandrum International Stadium,NaN,NaN,True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
16,BCCI Centre of Excellence Ground B,Bengaluru,India,+05:30,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
17,BCCI Centre of Excellence Ground,Bengaluru,India,+05:30,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
18,New Road,Worcester,England,+01:00,4500,NaN,"New Road End, Diglis End",Worcestershire,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1899.0
19,Senwes Park,Potchefstroom,South Africa,+02:00,55000,"North West Cricket Stadium Sedgars Park, Potch...","Cargo Motors End, University End","South Africa, North West",True,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
20,Albert Park 1,Suva,Fiji,+12:00,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
21,High Performance Oval,Windhoek,Namibia,+02:00,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
22,Namibia Cricket Ground,Windhoek,Namibia,+02:00,55000,NaN,NaN,Namibia,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
23,Albert Park 2,Suva,Fiji,+12:00,55000,NaN,NaN,NaN,NaN,NaN,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN

In [ ]:
# replace capacity nan value with random value above 50000
df_all_venues['capacity'].fillna(55000,inplace=True)

In [ ]:
# save this data in db diffent table name venue statsts
df_all_venues.to_sql('venue_stats', conn_crickbuzz, if_exists='replace', index=False)

# verify by reading from the database
pd.read_sql('SELECT * FROM venue_stats', conn_crickbuzz)

,ground,city,country,timezone,capacity,knownAs,ends,homeTeam,floodlights,curator,imageUrl,imageId,established
0,Dubai International Cricket Stadium,Dubai,United Arab Emirates,+04:00,25000,Dubai Sports City Cricket Stadium,"Emirates Road End, Dubai Sports City End",United Arab Emirates,1.0,Tony Hemming,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731713,NaN
1,Sheikh Zayed Stadium,Abu Dhabi,United Arab Emirates,+04:00,20000,President His Highness Sheikh Zayed bin Sulta...,"North End, Pavilion End",United Arab Emirates,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731716,2004.0
2,Sophia Gardens,Cardiff,Wales,+01:00,20500,The SWALEC Stadium,"River Taff End, Cathedral Road End",Glamorgan,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
3,The Rose Bowl,Southampton,England,+01:00,26500,"The Ageas Bowl, West End","Pavilion End, Northern End","Hampshire, Hampshire 2nd XI",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2001.0
4,Lord's,London,England,+01:00,30000,Lord's Cricket Ground,"Pavilion End, Nursery End","Marylebone Cricket Club, Middlesex",1.0,Mick Hunt,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717711,1814.0
5,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,+04:00,16000,None,"Pavilion End, Sharjah Club End",United Arab Emirates,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,731715,1982.0
6,Maple Leaf North-West Ground,King City,Canada,-04:00,55000,"Maple Leaf 1A, Ground 1","Northern End, Southern End",Canada,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
7,Harare Sports Club,Harare,Zimbabwe,+02:00,10000,Salisbury Sports Club,"City End, Club House End","Rhodesia, Zimbabwe, Mashonaland",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
8,Cronkbourne Sports and Social Club Ground,Tromode,Isle of Man,+01:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
9,Kensington Oval,"Bridgetown, Barbados",West Indies,-04:00,28000,Pickwick Cricket Club,"Malcolm Marshall End, Joel Garner End",Barbados,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717738,1871.0
10,Providence Stadium,Guyana,West Indies,-04:00,15000,Guyana National Stadium,"Media Centre End, Pavillion End",None,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2006.0
11,Emirates Old Trafford,Manchester,England,+01:00,19000,None,"Stretford End, Brian Statham End",Lancashire,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,717716,1857.0
12,Riverside Ground,Chester-le-Street,England,+01:00,22000,None,"Finchale End, Lumley End",Durham,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1995.0
13,The Cooper Associates County Ground,Taunton,England,+01:00,6500,Athletic Ground,"River End, Old Pavilion End",Somerset,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1882.0
14,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India,+05:30,50000,Ekana International Cricket Stadium,None,"Uttar Pradesh, Lucknow Super Giants",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,2017.0
15,Greenfield International Stadium,Thiruvananthapuram,India,+05:30,50000,Trivandrum International Stadium,None,None,1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
16,BCCI Centre of Excellence Ground B,Bengaluru,India,+05:30,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
17,BCCI Centre of Excellence Ground,Bengaluru,India,+05:30,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
18,New Road,Worcester,England,+01:00,4500,None,"New Road End, Diglis End",Worcestershire,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,1899.0
19,Senwes Park,Potchefstroom,South Africa,+02:00,55000,"North West Cricket Stadium Sedgars Park, Potch...","Cargo Motors End, University End","South Africa, North West",1.0,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
20,Albert Park 1,Suva,Fiji,+12:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
21,High Performance Oval,Windhoek,Namibia,+02:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
22,Namibia Cricket Ground,Windhoek,Namibia,+02:00,55000,None,None,Namibia,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN
23,Albert Park 2,Suva,Fiji,+12:00,55000,None,None,None,NaN,None,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174,NaN

In [ ]:
# exmine data structure
print(response.json().keys())

dict_keys(['ground', 'city', 'country', 'timezone', 'capacity', 'ends', 'homeTeam', 'imageUrl', 'imageId'])

In [ ]:
# extract and save as venue df
venue_df = []
venue_df.append(response.json())
df_venue = pd.DataFrame(venue_df)
df_venue

,ground,city,country,timezone,capacity,ends,homeTeam,imageUrl,imageId
0,Basin Reserve,Wellington,New Zealand,+13:00,"11,600","Vance Stand End, Scoreboard End",Wellington,http://i.cricketcb.com/i/stats/fth/540x303/ven...,189174

In [ ]:
df_venue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ground    1 non-null      object
 1   city      1 non-null      object
 2   country   1 non-null      object
 3   timezone  1 non-null      object
 4   capacity  1 non-null      object
 5   ends      1 non-null      object
 6   homeTeam  1 non-null      object
 7   imageUrl  1 non-null      object
 8   imageId   1 non-null      object
dtypes: object(9)
memory usage: 204.0+ bytes

In [32]:
import sqlite3
# cooonect database crickbuzz.db
conn_crickbuzz = sqlite3.connect('crickbuzz.db')

In [ ]:
# show table

In [33]:
# show crickbuzz.db tables
query = "SELECT name FROM sqlite_master WHERE type='table';"
cursor = conn_crickbuzz.cursor()
cursor.execute(query)
tables = cursor.fetchall()
for table in tables:
    print(table[0])

match_list
players
venue_stats
international_series
innings_stats

In [ ]:
# show match list details
query = """ select * from players"""
players = pd.read_sql(query, conn_crickbuzz)

In [6]:
# fetch international series
query = """ select * from international_series"""
df_series = pd.read_sql(query, conn_crickbuzz)
df_series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   name     20 non-null     object
 2   startDt  20 non-null     object
 3   endDt    20 non-null     object
dtypes: int64(1), object(3)
memory usage: 772.0+ bytes

In [ ]:
players

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,...,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,1.0,Batsman,0.0,0.0,7,RIGHT,...,UAE,244736,Playing XI,130019,7,NaN,None,NaN,None,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,0.0,Batting Allrounder,0.0,0.0,7,RIGHT,...,UAE,244727,Playing XI,130019,7,NaN,None,NaN,None,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,0.0,Batsman,0.0,0.0,7,LEFT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,0.0,WK-Batsman,1.0,0.0,7,RIGHT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,0.0,Batsman,0.0,0.0,7,RIGHT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,23956,Jannillea Glasgow,Jannillea Glasgow,Jannillea Glasgow,0.0,Bowling Allrounder,0.0,0.0,1139,LEFT,...,None,227429,Playing XI,122082,1139,NaN,None,NaN,None,NaN
1795,1449536,Abigail Bryce,Abigail Bryce,Abigail Bryce,0.0,Batsman,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1796,28731,Keila Elliott,Keila Elliott,Keila Elliott,0.0,Bowling Allrounder,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1797,1430401,Nerissa Crafton,Nerissa Crafton,Nerissa Crafton,0.0,Batsman,0.0,1.0,1139,LEFT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1798,15702,Shawnisha Hector,Shawnisha Hector,Shawnisha Hector,0.0,Bowler,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN

In [10]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'message': "Endpoint '/series/v1/archives/international/2024' does not exist"}

In [ ]:
# Examine the structure of the response data
data = response.json()
print(data.keys())
if 'seriesMapProto' in data:
    print("\nStructure of 'seriesMapProto':")
    if data['seriesMapProto']:
        print(data['seriesMapProto'][0].keys())
        if 'series' in data['seriesMapProto'][0] and data['seriesMapProto'][0]['series']:
            print("\nStructure of a series entry:")
            print(data['seriesMapProto'][0]['series'][0].keys())

dict_keys(['seriesMapProto', 'appIndex', 'contentFilters'])

Structure of 'seriesMapProto':
dict_keys(['date', 'series'])

Structure of a series entry:
dict_keys(['id', 'name', 'startDt', 'endDt'])

In [ ]:
# Save the DataFrame to the database
df_series.to_sql('international_series', conn_crickbuzz, if_exists='replace', index=False)

# Verify by reading from the database
pd.read_sql('SELECT * FROM international_series', conn_crickbuzz)

,id,name,startDt,endDt
0,10917,Mozambique tour of Eswatini 2025,1757635200000,1757808000000
1,10587,Asia Cup 2025,1757376000000,1759017600000
2,10812,Sweden tour of Isle Of Man 2025,1757116800000,1757203200000
3,8788,"South Africa tour of England, 2025",1756771200000,1757808000000
4,10801,"Switzerland tour of Guernsey, 2025",1756512000000,1756598400000
5,10647,Netherlands tour of Bangladesh 2025,1756512000000,1756857600000
6,10790,Eastern Europe Cup 2025,1756425600000,1756598400000
7,10642,United Arab Emirates T20I Tri-Series 2025,1756425600000,1757203200000
8,10267,"Sri Lanka tour of Zimbabwe, 2025",1756425600000,1757203200000
9,10746,Belgium tour of Austria 2025,1755907200000,1755993600000
10,10719,Czech Republic tour of Romania 2025,1755734400000,1755820800000
11,10658,Norway T20I Tri-Series 2025,1755388800000,1755388800000
12,9686,"India tour of Bangladesh, 2025 (Called off)",1755388800000,1756598400000
13,10713,Papua New Guinea tour of Guernsey 2025,1755129600000,1755129600000
14,9602,"South Africa tour of Australia, 2025",1754784000000,1755993600000
15,10609,Viking Cup 2025,1754524800000,1754784000000
16,10598,Cyprus tour of Croatia 2025,1754524800000,1754611200000
17,10465,"Switzerland tour of Estonia, 2025",1754092800000,1754179200000
18,9399,"Pakistan tour of West Indies, 2025",1754006400000,1754956800000
19,9584,"New Zealand tour of Zimbabwe, 2025",1753833600000,1754870400000

In [ ]:
series_data = []

if 'seriesMapProto' in data:
    for year_entry in data['seriesMapProto']:
        if 'series' in year_entry:
            for series_entry in year_entry['series']:
                extracted_details = {
                    'id': series_entry.get('id'),
                    'name': series_entry.get('name'),
                    'startDt': series_entry.get('startDt'),
                    'endDt': series_entry.get('endDt')
                }
                series_data.append(extracted_details)

df_series = pd.DataFrame(series_data)
display(df_series.head())

      id                                name        startDt          endDt
0  10917    Mozambique tour of Eswatini 2025  1757635200000  1757808000000
1  10587                       Asia Cup 2025  1757376000000  1759017600000
2  10812     Sweden tour of Isle Of Man 2025  1757116800000  1757203200000
3   8788  South Africa tour of England, 2025  1756771200000  1757808000000
4  10801  Switzerland tour of Guernsey, 2025  1756512000000  1756598400000

In [ ]:
df_series

       id                                         name    startDt      endDt
0   10917             Mozambique tour of Eswatini 2025 2025-09-12 2025-09-14
1   10587                                Asia Cup 2025 2025-09-09 2025-09-28
2   10812              Sweden tour of Isle Of Man 2025 2025-09-06 2025-09-07
3    8788           South Africa tour of England, 2025 2025-09-02 2025-09-14
4   10801           Switzerland tour of Guernsey, 2025 2025-08-30 2025-08-31
5   10647          Netherlands tour of Bangladesh 2025 2025-08-30 2025-09-03
6   10790                      Eastern Europe Cup 2025 2025-08-29 2025-08-31
7   10642    United Arab Emirates T20I Tri-Series 2025 2025-08-29 2025-09-07
8   10267             Sri Lanka tour of Zimbabwe, 2025 2025-08-29 2025-09-07
9   10746                 Belgium tour of Austria 2025 2025-08-23 2025-08-24
10  10719          Czech Republic tour of Romania 2025 2025-08-21 2025-08-22
11  10658                  Norway T20I Tri-Series 2025 2025-08-17 2025-08-17
12   9686  India tour of Bangladesh, 2025 (Called off) 2025-08-17 2025-08-31
13  10713       Papua New Guinea tour of Guernsey 2025 2025-08-14 2025-08-14
14   9602         South Africa tour of Australia, 2025 2025-08-10 2025-08-24
15  10609                              Viking Cup 2025 2025-08-07 2025-08-10
16  10598                  Cyprus tour of Croatia 2025 2025-08-07 2025-08-08
17  10465            Switzerland tour of Estonia, 2025 2025-08-02 2025-08-03
18   9399           Pakistan tour of West Indies, 2025 2025-08-01 2025-08-12
19   9584           New Zealand tour of Zimbabwe, 2025 2025-07-30 2025-08-11

In [ ]:
# convert strt date and end date into datetime column
df_series['startDt'] = pd.to_datetime(df_series['startDt'], unit='ms')
df_series['endDt'] = pd.to_datetime(df_series['endDt'], unit='ms')

In [ ]:
# Save the DataFrame with corrected datetime columns to the database
df_series.to_sql('international_series', conn_crickbuzz, if_exists='replace', index=False)

# Verify by reading from the database
pd.read_sql('SELECT * FROM international_series', conn_crickbuzz)

,id,name,startDt,endDt
0,10917,Mozambique tour of Eswatini 2025,2025-09-12 00:00:00,2025-09-14 00:00:00
1,10587,Asia Cup 2025,2025-09-09 00:00:00,2025-09-28 00:00:00
2,10812,Sweden tour of Isle Of Man 2025,2025-09-06 00:00:00,2025-09-07 00:00:00
3,8788,"South Africa tour of England, 2025",2025-09-02 00:00:00,2025-09-14 00:00:00
4,10801,"Switzerland tour of Guernsey, 2025",2025-08-30 00:00:00,2025-08-31 00:00:00
5,10647,Netherlands tour of Bangladesh 2025,2025-08-30 00:00:00,2025-09-03 00:00:00
6,10790,Eastern Europe Cup 2025,2025-08-29 00:00:00,2025-08-31 00:00:00
7,10642,United Arab Emirates T20I Tri-Series 2025,2025-08-29 00:00:00,2025-09-07 00:00:00
8,10267,"Sri Lanka tour of Zimbabwe, 2025",2025-08-29 00:00:00,2025-09-07 00:00:00
9,10746,Belgium tour of Austria 2025,2025-08-23 00:00:00,2025-08-24 00:00:00
10,10719,Czech Republic tour of Romania 2025,2025-08-21 00:00:00,2025-08-22 00:00:00
11,10658,Norway T20I Tri-Series 2025,2025-08-17 00:00:00,2025-08-17 00:00:00
12,9686,"India tour of Bangladesh, 2025 (Called off)",2025-08-17 00:00:00,2025-08-31 00:00:00
13,10713,Papua New Guinea tour of Guernsey 2025,2025-08-14 00:00:00,2025-08-14 00:00:00
14,9602,"South Africa tour of Australia, 2025",2025-08-10 00:00:00,2025-08-24 00:00:00
15,10609,Viking Cup 2025,2025-08-07 00:00:00,2025-08-10 00:00:00
16,10598,Cyprus tour of Croatia 2025,2025-08-07 00:00:00,2025-08-08 00:00:00
17,10465,"Switzerland tour of Estonia, 2025",2025-08-02 00:00:00,2025-08-03 00:00:00
18,9399,"Pakistan tour of West Indies, 2025",2025-08-01 00:00:00,2025-08-12 00:00:00
19,9584,"New Zealand tour of Zimbabwe, 2025",2025-07-30 00:00:00,2025-08-11 00:00:00

In [37]:
#set full column
pd.set_option('display.max_columns', None)

In [ ]:
match_list

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,seriesStartDt,seriesEndDt,isTimeAnnounced,stateTitle,team1_overs,team2_overs,team1_id,team1_name,team1_sname,team1_image_id,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,IND Won,13.1,4.3,7,United Arab Emirates,UAE,172121,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,2025-09-08 00:00:00,2025-09-29 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,Complete,7.5,4.6,11,South Africa,RSA,172126,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,ENG Won,49.6,20.5,9,England,ENG,172123,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,2025-09-01 00:00:00,2025-09-15 00:00:00,1,RSA Won,49.6,49.6,11,South Africa,RSA,172126,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926
5,131075,10642,United Arab Emirates T20I Tri-Series 2025,5th Match,T20,2025-09-04 15:00:00,2025-09-04 18:30:00,Complete,Pakistan won by 31 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,19.6,3,Pakistan,PAK,591986,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
6,131092,10642,United Arab Emirates T20I Tri-Series 2025,Final,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Pakistan won by 75 runs,3.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,PAK Won,19.6,15.5,3,Pakistan,PAK,591986,96,Afghanistan,AFG,172188,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
7,131086,10642,United Arab Emirates T20I Tri-Series 2025,6th Match,T20,2025-09-05 15:00:00,2025-09-05 18:30:00,Complete,Afghanistan won by 4 runs,96.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,AFG Won,19.6,19.6,96,Afghanistan,AFG,172188,7,United Arab Emirates,UAE,172121,140,Sharjah Cricket Stadium,Sharjah,+04:00,25.33095,55.420902
8,128919,7572,ICC Cricket World Cup League Two 2023-27,85th Match,ODI,2025-09-06 14:30:00,2025-09-06 22:30:00,Abandon,Match abandoned due to wet outfield (no toss),487.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,Abandon,19.6,19.6,26,Canada,CAN,172140,23,Scotland,SCO,172137,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
9,128908,7572,ICC Cricket World Cup League Two 2023-27,84th Match,ODI,2025-09-04 14:30:00,2025-09-04 22:30:00,Complete,Scotland won by 55 runs (24 overs game due to ...,23.0,2024-02-14 00:00:00,2027-03-31 00:00:00,1,SCO Won,23.6,21.2,23,Scotland,SCO,172137,161,Namibia,NAM,172229,139,Maple Leaf North-West Ground,King City,-04:00,36.210861,-121.126602
10,122973,10267,"Sri Lanka tour of Zimbabwe, 2025",3rd T20I,T20,2025-09-07 11:30:00,2025-09-07 15:00:00,Complete,Sri Lanka won by 8 wkts,5.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,SL Won,19.6,17.4,12,Zimbabwe,ZIM,172127,5,Sri Lanka,SL,172119,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
11,122968,10267,"Sri Lanka tour of Zimbabwe, 2025",2nd T20I,T20,2025-09-06 11:30:00,2025-09-06 15:00:00,Complete,Zimbabwe won by 5 wkts,12.0,2025-08-28 00:00:00,2025-09-08 00:00:00,1,ZIM Won,17.4,14.2,5,Sri Lanka,SL,172119,12,Zimbabwe,ZIM,172127,69,Harare Sports Club,Harare,+02:00,-17.814114,31.050962
12,133187,10812,Sweden tour of Isle Of Man 2025,4th Match,T20,2025-09-07 14:30:00,2025-09-07 18:00:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
13,133176,10812,Sweden tour of Isle Of Man 2025,3rd T20I,T20,2025-09-07 10:00:00,2025-09-07 13:30:00,Abandon,Match abandoned without toss,487.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,Abandon,19.6,19.6,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
14,133171,10812,Sweden tour of Isle Of Man 2025,2nd T20I,T20,2025-09-06 14:30:00,2025-09-06 18:00:00,Complete,Sweden won by 3 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,19.5,14.3,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
15,133160,10812,Sweden tour of Isle Of Man 2025,1st T20I,T20,2025-09-06 10:00:00,2025-09-06 13:30:00,Complete,Sweden won by 10 wkts,534.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,SWE Won,16.1,10.5,557,Isle of Man,IOM,172609,534,Sweden,SWE,248454,1438142,Cronkbourne Sports and Social Club Ground,Tromode,+01:00,54.1692678,-4.4754267
16,116765,9575,Caribbean Premier League 2025,24th Match,T20,2025-09-07 15:00:00,2025-09-07 18:30:00,Complete,Barbados Royals won by 27 runs,262.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,BR Won,19.6,19.6,262,Barbados Royals,BR,210485,263,Saint Lucia Kings,SLK,172316,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
17,116774,9575,Caribbean Premier League 2025,25th Match,T20,2025-09-08 00:00:00,2025-09-08 03:30:00,Complete,St Kitts and Nevis Patriots won by 5 runs,302.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,SNP Won,19.6,19.6,302,St Kitts and Nevis Patriots,SNP,172351,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
18,116759,9575,Caribbean Premier League 2025,23rd Match,T20,2025-09-06 23:00:00,2025-09-07 02:30:00,Complete,Guyana Amazon Warriors won by 3 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.5,271,Trinbago Knight Riders,TKR,172325,159,Guyana Amazon Warriors,GAW,172227,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
19,116750,9575,Caribbean Premier League 2025,22nd Match,T20,2025-09-05 23:00:00,2025-09-06 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,19.6,19.6,262,Barbados Royals,BR,210485,1978,Antigua and Barbuda Falcons,ABF,507236,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
20,116741,9575,Caribbean Premier League 2025,21st Match,T20,2025-09-04 23:00:00,2025-09-05 02:30:00,Complete,Guyana Amazon Warriors won by 4 wkts,159.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,GAW Won,19.6,19.4,262,Barbados Royals,BR,210485,159,Guyana Amazon Warriors,GAW,172227,55,Kensington Oval,"Bridgetown, Barbados",-04:00,13.105021,-59.62257
21,116783,9575,Caribbean Premier League 2025,26th Match,T20,2025-09-10 23:00:00,2025-09-11 02:30:00,Complete,Antigua and Barbuda Falcons won by 4 wkts,1978.0,2025-08-13 00:00:00,2025-09-22 00:00:00,1,ABF Won,18.1,19.1,159,Guyana Amazon Warriors,GAW,172227,1978,Antigua and Barbuda Falcons,ABF,507236,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
22,111073,9257,T20 Blast 2025,Quarter Final 3,T20,2025-09-06 13:30:00,2025-09-06 17:00:00,Complete,Lancashire won by 3 wkts,143.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,LANCS Won,19.6,18.3,150,Kent,KENT,172217,143,Lancashire,LANCS,172210,65,Emirates Old Trafford,Manchester,+01:00,53.463066,-2.291301
23,111069,9257,T20 Blast 2025,Quarter Final 2,T20,2025-09-05 17:30:00,2025-09-05 21:00:00,Complete,Hampshire won by 26 runs,153.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,HAM Won,19.6,19.6,153,Hampshire,HAM,172220,141,Durham,DUR,172208,60,Riverside Ground,Chester-le-Street,+01:00,54.849531,-1.56103
24,111081,9257,T20 Blast 2025,Quarter Final 4,T20,2025-09-06 17:30:00,2025-09-06 21:00:00,Complete,Somerset won by 4 wkts,119.0,2025-05-28 00:00:00,2025-09-14 00:00:00,1,SOM Won,19.6,19.5,140,Warwickshire,WARKS,172207,119,Somerset,SOM,172199,223,The Cooper Associates County Ground,Taunton,+01:00,51.018913,3.100894
25,132637,10735,Uttar Pradesh Premier League 2025,Qualifier 2,T20,2025-09-04 14:00:00,2025-09-04 17:30:00,Complete,Meerut Mavericks won by 19 runs,2833.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,MRM Won,19.6,19.6,2833,Meerut Mavericks,MRM,738654,2844,Lucknow Falcons,LFC,738651,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
26,132648,10735,Uttar Pradesh Premier League 2025,Final,T20,2025-09-06 14:00:00,2025-09-06 17:30:00,Complete,Kashi Rudras won by 8 wkts,2800.0,2025-08-16 00:00:00,2025-09-07 00:00:00,1,KRD Won,19.6,15.4,2833,Meerut Mavericks,MRM,738654,2800,Kashi Rudras,KRD,738657,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,+05:30,26.846694,80.946166
27,130806,10620,Kerala Cricket League 2025,Final,T20,2025-09-07 13:15:00,2025-09-07 16:45:00,Complete,Kochi Blue Tigers won by 75 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,16.3,2733,Kochi Blue Tigers,KBT,731734,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
28,130795,10620,Kerala Cricket League 2025,Semi Final 2 (1st v 4th),T20,2025-09-05 13:15:00,2025-09-05 16:45:00,Complete,Kochi Blue Tigers won by 15 runs,2733.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,KBT Won,19.6,19.6,2733,Kochi Blue Tigers,KBT,731734,2741,Calicut Globstars,CGS,731732,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
29,130784,10620,Kerala Cricket League 2025,Semi Final 1 (2nd v 3rd),T20,2025-09-05 09:00:00,2025-09-05 12:30:00,Complete,Aries Kollam Sailors won by 10 wkts,2778.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,AKS Won,17.1,9.5,2752,Thrissur Titans,TST,731736,2778,Aries Kollam Sailors,AKS,731731,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
30,130778,10620,Kerala Cricket League 2025,30th Match,T20,2025-09-04 13:15:00,2025-09-04 16:45:00,Complete,Thrissur Titans won by 4 wkts,2752.0,2025-08-20 00:00:00,2025-09-07 00:00:00,1,TST Won,19.6,18.1,2741,Calicut Globstars,CGS,731732,2752,Thrissur Titans,TST,731736,506,Greenfield International Stadium,Thiruvananthapuram,+05:30,8.570806,76.884328
31,123677,10311,Duleep Trophy 2025,2nd Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,107.6,164.3,234,West Zone,WZONE,172287,237,Central Zone,CZONE,172290,1438102,BCCI Centre of Excellence Ground B,Bengaluru,+05:30,13.174092,77.706999
32,123672,10311,Duleep Trophy 2025,1st Semi-Final,TEST,2025-09-04 04:00:00,2025-09-07 11:00:00,Complete,Match drawn,487.0,2025-08-27 00:00:00,2025-09-16 00:00:00,1,Complete,169.2,100.1,236,South Zone,SZONE,172289,233,North Zone,NZONE,172286,1438087,BCCI Centre of Excellence Ground,Bengaluru,+05:30,12.978853,77.599533
33,113217,9360,County Championship Division One 2025,60th Match,TEST,2025-09-08 09:30:00,2025-09-11 16:30:00,Complete,Nottinghamshire won by 3 wkts,139.0,2025-04-03 00:00:00,2025-09-28 00:00:00,1,Complete,52.5,70.2,147,Worcestershire,WORCS,172214,139,Nottinghamshire,NOTTS,172206,225,New Road,Worcester,+01:00,52.189294,-2.2268
34,116495,9557,"New Zealand A tour of South Africa, 2025",1st Unofficial Test,TEST,2025-09-07 08:00:00,2025-09-10 15:00:00,Complete,New Zealand A won by 185 runs,80.0,2025-08-29 00:00:00,2025-09-18 00:00:00,1,NZA Won,128.5,56.1,80,New Zealand A,NZA,172174,268,South Africa A,RSAA,172321,102,Senwes Park,Potchefstroom,+02:00,-26.695565,27.100691
35,133055,10785,Czech Republic Women tour Estonia 2025,1st T20I,T20,2025-09-06 08:00:00,2025-09-06 11:30:00,Complete,Estonia Women won by 1 wkt,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,19.4,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
36,133066,10785,Czech Republic Women tour Estonia 2025,3rd T20I,T20,2025-09-07 07:00:00,2025-09-07 10:30:00,Complete,Estonia Women won by 7 wkts,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,19.5,9.6,1987,Czech Republic Women,CZEW,501075,1521,Estonia Women,ESTW,315349,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
37,133061,10785,Czech Republic Women tour Estonia 2025,2nd T20I,T20,2025-09-06 12:30:00,2025-09-06 16:00:00,Complete,Estonia Women won by 115 runs,1521.0,2025-09-05 00:00:00,2025-09-08 00:00:00,1,ESTW Won,20.0,12.1,1521,Estonia Women,ESTW,315349,1987,Czech Republic Women,CZEW,501075,1552,Estonian National Cricket and Rugby Field,Tallinn,+03:00,59.43696,24.75353
38,133798,10856,Japan Women tour of Fiji 2025,1st T20I,T20,2025-09-05 02:00:00,2025-09-05 05:30:00,Complete,Japan Women won by 23 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,19.6,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
39,133809,10856,Japan Women tour of Fiji 2025,2nd T20I,T20,2025-09-05 22:00:00,2025-09-06 01:30:00,Complete,Japan Women won by 104 runs,487.0,2025-09-04 00:00:00,2025-09-07 00:00:00,1,JPNW Won,19.6,12.3,487,Japan Women,JPNW,248419,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
40,131675,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Rwanda Women won by 6 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,501,Kenya Women,KENW,172550,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
41,131669,10697,ICC Womens T20 World Cup Africa Region Divisio...,7th Place Play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Nigeria Women won by 85 runs,1482.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NGAW Won,19.6,19.6,1482,Nigeria Women,NGAW,273957,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
42,131647,10697,ICC Womens T20 World Cup Africa Region Divisio...,2nd semi-final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Namibia Women won by 8 wkts,503.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,NAMW Won,19.6,13.5,483,Tanzania Women,TANW,172531,503,Namibia Women,NAMW,172552,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
43,131653,10697,ICC Womens T20 World Cup Africa Region Divisio...,5th Place Play-off 2nd Semi-Final,T20,2025-09-04 11:50:00,2025-09-04 15:20:00,Complete,Rwanda Women won by 50 runs,720.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,RWAW Won,19.6,19.6,720,Rwanda Women,RWAW,248448,490,Sierra Leone Women,SLEW,172538,1438052,High Performance Oval,Windhoek,+02:00,-22.5859618,17.0436255
44,131686,10697,ICC Womens T20 World Cup Africa Region Divisio...,Final,T20,2025-09-06 11:50:00,2025-09-06 15:20:00,Complete,Zimbabwe Women won by 9 wkts,388.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,ZIMW Won,19.6,16.3,503,Namibia Women,NAMW,172552,388,Zimbabwe Women,ZIMW,172441,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
45,131664,10697,ICC Womens T20 World Cup Africa Region Divisio...,3rd place play-off,T20,2025-09-06 07:30:00,2025-09-06 11:00:00,Complete,Tanzania Women won by 6 runs,483.0,2025-08-30 00:00:00,2025-09-07 00:00:00,1,TANW Won,19.6,19.4,483,Tanzania Women,TANW,172531,448,Uganda Women,UGAW,172496,1438021,Namibia Cricket Ground,Windhoek,+02:00,-22.5872377,17.0677249
46,131746,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"3rd Match, Group A",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Vanuatu Women won by 10 runs,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,19.6,506,Vanuatu Women,VANW,172555,484,Indonesia Women,IDNW,172532,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
47,131774,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"7th Match, Group B",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Papua New Guinea Women won by 168 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.4,390,Papua New Guinea Women,PNGW,172443,1514,Philippines Women,PHIW,307469,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
48,131735,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"1st Match, Group A",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Fiji Women won by 9 wkts,1181.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,FIJIW Won,19.6,17.2,1754,Cook Islands Women,CISW,341074,1181,Fiji Women,FIJIW,248411,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
49,131757,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"5th Match, Group B",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Japan Women won by 71 runs,487.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,JPNW Won,19.6,13.5,487,Japan Women,JPNW,248419,482,Samoa Women,WSMW,172530,1438120,Albert Park 1,Suva,+12:00,-18.1472049,178.4223645
50,131779,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"8th Match, Group A",T20,2025-09-10 01:30:00,2025-09-10 05:00:00,Complete,Vanuatu Women won by 7 wkts,506.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,VANW Won,19.6,15.1,1754,Cook Islands Women,CISW,341074,506,Vanuatu Women,VANW,172555,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
51,131741,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"2nd Match, Group B",T20,2025-09-08 21:30:00,2025-09-09 01:00:00,Complete,Papua New Guinea Women won by 45 runs,390.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,PNGW Won,19.6,19.5,390,Papua New Guinea Women,PNGW,172443,487,Japan Women,JPNW,248419,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
52,131763,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"6th Match, Group A",T20,2025-09-09 21:30:00,2025-09-10 01:00:00,Complete,Indonesia Women won by 42 runs,484.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,IDNW Won,19.6,19.3,484,Indonesia Women,IDNW,172532,1181,Fiji Women,FIJIW,248411,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
53,131752,10702,ICC Womens T20 World Cup East Asia Pacific Qua...,"4th Match, Group B",T20,2025-09-09 01:30:00,2025-09-09 05:00:00,Complete,Samoa Women won by 9 wkts,482.0,2025-09-08 00:00:00,2025-09-16 00:00:00,1,WSMW Won,17.3,6.2,1514,Philippines Women,PHIW,307469,482,Samoa Women,WSMW,172530,1438123,Albert Park 2,Suva,+12:00,-18.1471997,178.4200685
54,122104,10141,Womens Caribbean Premier League 2025,3rd Match,T20,2025-09-10 18:00:00,2025-09-10 21:30:00,Complete,Barbados Royals Women won by 59 runs,1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,15.3,1137,Barbados Royals Women,BRW,241608,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
55,122093,10141,Womens Caribbean Premier League 2025,2nd Match,T20,2025-09-07 19:00:00,2025-09-07 22:30:00,Complete,Barbados Royals Women won by 7 wkts (DLS method),1137.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,BRW Won,19.6,17.2,1144,Guyana Amazon Warriors Women,GAWW,241607,1137,Barbados Royals Women,BRW,241608,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987
56,122082,10141,Womens Caribbean Premier League 2025,1st Match,T20,2025-09-06 18:00:00,2025-09-06 21:30:00,Complete,Guyana Amazon Warriors Women won by 6 runs,1144.0,2025-09-05 00:00:00,2025-09-18 00:00:00,1,GAWW Won,19.6,19.6,1144,Guyana Amazon Warriors Women,GAWW,241607,1139,Trinbago Knight Riders Women,TKRW,241610,110,Providence Stadium,Guyana,-04:00,41.823872,-71.411987

In [ ]:
players

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,1.0,Batsman,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244736,Playing XI,130019,7,NaN,None,NaN,None,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,0.0,Batting Allrounder,0.0,0.0,7,RIGHT,Right Arm medium,UAE,244727,Playing XI,130019,7,NaN,None,NaN,None,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,0.0,Batsman,0.0,0.0,7,LEFT,Left arm orthodox,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,0.0,WK-Batsman,1.0,0.0,7,RIGHT,,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,0.0,Batsman,0.0,0.0,7,RIGHT,Right Arm off break,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,23956,Jannillea Glasgow,Jannillea Glasgow,Jannillea Glasgow,0.0,Bowling Allrounder,0.0,0.0,1139,LEFT,Right Arm fast medium,None,227429,Playing XI,122082,1139,NaN,None,NaN,None,NaN
1795,1449536,Abigail Bryce,Abigail Bryce,Abigail Bryce,0.0,Batsman,0.0,1.0,1139,RIGHT,Right Arm off break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1796,28731,Keila Elliott,Keila Elliott,Keila Elliott,0.0,Bowling Allrounder,0.0,1.0,1139,RIGHT,Right Arm leg break,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1797,1430401,Nerissa Crafton,Nerissa Crafton,Nerissa Crafton,0.0,Batsman,0.0,1.0,1139,LEFT,,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1798,15702,Shawnisha Hector,Shawnisha Hector,Shawnisha Hector,0.0,Bowler,0.0,1.0,1139,RIGHT,Right Arm medium,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN

In [ ]:
#filter player with team id 9,2,11
players_filtered = players[(players['team_id'] == 9) | (players['team_id'] == 2) | (players['team_id'] == 11)]
players_filtered

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,bowlingStyle,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
19,12086,Abhishek Sharma,Abhishek Sharma,Abhishek Sharma,0.0,Batting Allrounder,0.0,0.0,2,LEFT,Left arm orthodox,IND,153963,Playing XI,130019,2,NaN,None,NaN,None,NaN
20,11808,Shubman Gill,Shubman Gill,Gill,0.0,Batsman,0.0,0.0,2,RIGHT,Right Arm off break,IND,616515,Playing XI,130019,2,NaN,None,NaN,None,NaN
21,7915,Suryakumar Yadav,Suryakumar Yadav,Suryakumar Yadav,1.0,Batsman,0.0,0.0,2,RIGHT,Right Arm off break,IND,352481,Playing XI,130019,2,NaN,None,NaN,None,NaN
22,14504,Tilak Varma,Tilak Varma,Tilak Varma,0.0,Batsman,0.0,0.0,2,LEFT,Right Arm off break,IND,226525,Playing XI,130019,2,NaN,None,NaN,None,NaN
23,8271,Samson,Sanju Samson,Samson,0.0,WK-Batsman,1.0,0.0,2,RIGHT,,IND,226289,Playing XI,130019,2,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,435,Jeetan Patel,Jeetan Patel,Jeetan Patel,NaN,Spin Bowling Coach,NaN,NaN,9,None,None,ENG,156011,Bench,105788,9,1.0,None,NaN,None,NaN
196,201,Brendon McCullum,Brendon McCullum,Brendon McCullum,NaN,Head Coach,NaN,NaN,9,None,None,ENG,156149,Bench,105788,9,1.0,None,NaN,None,NaN
197,44,Marcus Trescothick,Marcus Trescothick,Trescothick,NaN,Batting Coach,NaN,NaN,9,None,None,ENG,156638,Bench,105788,9,1.0,None,NaN,None,NaN
198,6554,Neil Killeen,Neil Killeen,Killeen,NaN,Pace Bowling Coach,NaN,NaN,9,None,None,ENG,182026,Bench,105788,9,1.0,None,NaN,None,NaN
199,1057,Tim Southee,Tim Southee,Southee,NaN,Pace Bowling Consultant,NaN,NaN,9,None,None,ENG,601546,Bench,105788,9,1.0,None,NaN,None,NaN

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/11808/batting"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '37', '55', '22', '118']}, {'values': ['Innings', '69', '55', '22', '115']}, {'values': ['Runs', '2647', '2775', '598', '3866']}, {'values': ['Balls', '4309', '2787', '424', '2787']}, {'values': ['Highest', '269', '208', '126', '129']}, {'values': ['Average', '41.36', '59.04', '31.47', '39.45']}, {'values': ['SR', '61.43', '99.57', '141.04', '138.72']}, {'values': ['Not Out', '5', '8', '3', '17']}, {'values': ['Fours', '295', '314', '62', '372']}, {'values': ['Sixes', '43', '59', '23', '119']}, {'values': ['Ducks', '5', '1', '1', '4']}, {'values': ['50s', '7', '15', '3', '26']}, {'values': ['100s', '9', '8', '1', '4']}, {'values': ['200s', '1', '1', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Shubman Gill Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/11808/shubman-gill'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 10587, 'seriesName': 'Asia Cup 2025'}]}

In [ ]:
# extrat player batting records
data = response.json()
print(data.keys())

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [ ]:
batting_data = data.get('values', [])
headers = data.get('headers', [])

# Create a dictionary to hold the extracted data
extracted_batting_data = {}

# The first value in each entry of 'values' is the metric name (e.g., 'Matches', 'Innings')
# The subsequent values correspond to the formats in 'headers' (skipping the first header which is 'ROWHEADER')
for entry in batting_data:
    metric_name = entry['values'][0]
    metric_values = entry['values'][1:] # Get values for each format

    # Ensure the number of values matches the number of headers (excluding 'ROWHEADER')
    if len(metric_values) == len(headers) - 1:
        for i, format_name in enumerate(headers[1:]): # Iterate through format headers
            # Create a key like 'Matches - Test', 'Innings - ODI', etc.
            column_name = f"{metric_name} - {format_name}"
            # Store the value, handling potential errors if the value is not a number
            try:
                extracted_batting_data[column_name] = [float(metric_values[i])]
            except (ValueError, TypeError):
                extracted_batting_data[column_name] = [metric_values[i]] # Keep as is if not convertible to float
    else:
        print(f"Warning: Mismatch between number of values and headers for metric '{metric_name}'. Skipping.")


df_batting_stats = pd.DataFrame(extracted_batting_data)
display(df_batting_stats)

Empty DataFrame
Columns: []
Index: []

In [ ]:
print(data.keys())
if 'values' in data:
    print("\nStructure of 'values':")
    print(data['values'])
if 'headers' in data:
    print("\nStructure of 'headers':")
    print(data['headers'])

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

Structure of 'values':
[{'values': ['Matches', '37', '55', '22', '118']}, {'values': ['Innings', '69', '55', '22', '115']}, {'values': ['Runs', '2647', '2775', '598', '3866']}, {'values': ['Balls', '4309', '2787', '424', '2787']}, {'values': ['Highest', '269', '208', '126', '129']}, {'values': ['Average', '41.36', '59.04', '31.47', '39.45']}, {'values': ['SR', '61.43', '99.57', '141.04', '138.72']}, {'values': ['Not Out', '5', '8', '3', '17']}, {'values': ['Fours', '295', '314', '62', '372']}, {'values': ['Sixes', '43', '59', '23', '119']}, {'values': ['Ducks', '5', '1', '1', '4']}, {'values': ['50s', '7', '15', '3', '26']}, {'values': ['100s', '9', '8', '1', '4']}, {'values': ['200s', '1', '1', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}]

Structure of 'headers':
['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [ ]:
batting_data = data.get('values', [])
headers = data.get('headers', [])

# Create a dictionary to hold the extracted data
extracted_batting_data = {}

# The first value in each entry of 'values' is the metric name (e.g., 'Matches', 'Innings')
# The subsequent values correspond to the formats in 'headers' (skipping the first header which is 'ROWHEADER')
for entry in batting_data:
    metric_name = entry['values'][0]
    metric_values = entry['values'][1:] # Get values for each format

    # Ensure the number of values matches the number of headers (excluding 'ROWHEADER')
    if len(metric_values) == len(headers) - 1:
        for i, format_name in enumerate(headers[1:]): # Iterate through format headers
            # Create a key like 'Matches - Test', 'Innings - ODI', etc.
            column_name = f"{metric_name} - {format_name}"
            # Store the value, handling potential errors if the value is not a number
            try:
                extracted_batting_data[column_name] = [float(metric_values[i])]
            except (ValueError, TypeError):
                extracted_batting_data[column_name] = [metric_values[i]] # Keep as is if not convertible to float
    else:
        print(f"Warning: Mismatch between number of values and headers for metric '{metric_name}'. Skipping.")


df_batting_stats = pd.DataFrame(extracted_batting_data)
display(df_batting_stats)

,Matches - Test,Matches - ODI,Matches - T20,Matches - IPL,Innings - Test,Innings - ODI,Innings - T20,Innings - IPL,Runs - Test,Runs - ODI,Runs - T20,Runs - IPL,Balls - Test,Balls - ODI,Balls - T20,Balls - IPL,Highest - Test,Highest - ODI,Highest - T20,Highest - IPL,Average - Test,Average - ODI,Average - T20,Average - IPL,SR - Test,SR - ODI,SR - T20,SR - IPL,Not Out - Test,Not Out - ODI,Not Out - T20,Not Out - IPL,Fours - Test,Fours - ODI,Fours - T20,Fours - IPL,Sixes - Test,Sixes - ODI,Sixes - T20,Sixes - IPL,Ducks - Test,Ducks - ODI,Ducks - T20,Ducks - IPL,50s - Test,50s - ODI,50s - T20,50s - IPL,100s - Test,100s - ODI,100s - T20,100s - IPL,200s - Test,200s - ODI,200s - T20,200s - IPL,300s - Test,300s - ODI,300s - T20,300s - IPL,400s - Test,400s - ODI,400s - T20,400s - IPL
0,37.0,55.0,22.0,118.0,69.0,55.0,22.0,115.0,2647.0,2775.0,598.0,3866.0,4309.0,2787.0,424.0,2787.0,269.0,208.0,126.0,129.0,41.36,59.04,31.47,39.45,61.43,99.57,141.04,138.72,5.0,8.0,3.0,17.0,295.0,314.0,62.0,372.0,43.0,59.0,23.0,119.0,5.0,1.0,1.0,4.0,7.0,15.0,3.0,26.0,9.0,8.0,1.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_batting_stats['player_id'] = player_id
display(df_batting_stats.head())

,Matches - Test,Matches - ODI,Matches - T20,Matches - IPL,Innings - Test,Innings - ODI,Innings - T20,Innings - IPL,Runs - Test,Runs - ODI,Runs - T20,Runs - IPL,Balls - Test,Balls - ODI,Balls - T20,Balls - IPL,Highest - Test,Highest - ODI,Highest - T20,Highest - IPL,Average - Test,Average - ODI,Average - T20,Average - IPL,SR - Test,SR - ODI,SR - T20,SR - IPL,Not Out - Test,Not Out - ODI,Not Out - T20,Not Out - IPL,Fours - Test,Fours - ODI,Fours - T20,Fours - IPL,Sixes - Test,Sixes - ODI,Sixes - T20,Sixes - IPL,Ducks - Test,Ducks - ODI,Ducks - T20,Ducks - IPL,50s - Test,50s - ODI,50s - T20,50s - IPL,100s - Test,100s - ODI,100s - T20,100s - IPL,200s - Test,200s - ODI,200s - T20,200s - IPL,300s - Test,300s - ODI,300s - T20,300s - IPL,400s - Test,400s - ODI,400s - T20,400s - IPL,player_id
0,37.0,55.0,22.0,118.0,69.0,55.0,22.0,115.0,2647.0,2775.0,598.0,3866.0,4309.0,2787.0,424.0,2787.0,269.0,208.0,126.0,129.0,41.36,59.04,31.47,39.45,61.43,99.57,141.04,138.72,5.0,8.0,3.0,17.0,295.0,314.0,62.0,372.0,43.0,59.0,23.0,119.0,5.0,1.0,1.0,4.0,7.0,15.0,3.0,26.0,9.0,8.0,1.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11808

In [ ]:
df_batting_stats.to_sql('batting_stats', conn_crickbuzz, if_exists='replace', index=False)

# Verify by reading from the database
pd.read_sql('SELECT * FROM batting_stats', conn_crickbuzz)

,Matches - Test,Matches - ODI,Matches - T20,Matches - IPL,Innings - Test,Innings - ODI,Innings - T20,Innings - IPL,Runs - Test,Runs - ODI,Runs - T20,Runs - IPL,Balls - Test,Balls - ODI,Balls - T20,Balls - IPL,Highest - Test,Highest - ODI,Highest - T20,Highest - IPL,Average - Test,Average - ODI,Average - T20,Average - IPL,SR - Test,SR - ODI,SR - T20,SR - IPL,Not Out - Test,Not Out - ODI,Not Out - T20,Not Out - IPL,Fours - Test,Fours - ODI,Fours - T20,Fours - IPL,Sixes - Test,Sixes - ODI,Sixes - T20,Sixes - IPL,Ducks - Test,Ducks - ODI,Ducks - T20,Ducks - IPL,50s - Test,50s - ODI,50s - T20,50s - IPL,100s - Test,100s - ODI,100s - T20,100s - IPL,200s - Test,200s - ODI,200s - T20,200s - IPL,300s - Test,300s - ODI,300s - T20,300s - IPL,400s - Test,400s - ODI,400s - T20,400s - IPL,player_id
0,37.0,55.0,22.0,118.0,69.0,55.0,22.0,115.0,2647.0,2775.0,598.0,3866.0,4309.0,2787.0,424.0,2787.0,269.0,208.0,126.0,129.0,41.36,59.04,31.47,39.45,61.43,99.57,141.04,138.72,5.0,8.0,3.0,17.0,295.0,314.0,62.0,372.0,43.0,59.0,23.0,119.0,5.0,1.0,1.0,4.0,7.0,15.0,3.0,26.0,9.0,8.0,1.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11808

In [13]:
#fetch match list data
query = "SELECT * FROM match_list"
match_list = pd.read_sql(query, conn_crickbuzz)

In [15]:
# fetch only match id where team id 2,11,9
match_list_filtered = match_list[(match_list['team2_id'] == 2) | (match_list['team1_id'] == 11) | (match_list['team1_id'] == 9)]
match_list_filtered

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,...,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,...,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,...,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,...,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,...,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926

In [16]:
matchID = [ 130008,130019,105802,105794,105788]

In [17]:
# Filter the match_list DataFrame based on the matchID list
df_filtered_matches = match_list[match_list['matchId'].isin(matchID)]

# Display the filtered DataFrame
display(df_filtered_matches)

,matchId,seriesId,seriesName,matchDesc,matchFormat,startDate,endDate,state,status,currBatTeamId,...,team2_id,team2_name,team2_sname,team2_image_id,venue_id,ground,city,timezone,latitude,longitude
0,130019,10587,Asia Cup 2025,"2nd Match, Group A",T20,2025-09-10 14:30:00,2025-09-10 18:00:00,Complete,India won by 9 wkts,2.0,...,2,India,IND,719031,153,Dubai International Cricket Stadium,Dubai,+04:00,25.046842,55.218969
1,130008,10587,Asia Cup 2025,"1st Match, Group B",T20,2025-09-09 14:30:00,2025-09-09 18:00:00,Complete,Afghanistan won by 94 runs,96.0,...,8,Hong Kong,HK,172122,94,Sheikh Zayed Stadium,Abu Dhabi,+04:00,24.416138,54.453566
2,105802,8788,"South Africa tour of England, 2025",1st T20I,T20,2025-09-10 17:30:00,2025-09-10 21:00:00,Complete,South Africa won by 14 runs (DLS Method),11.0,...,9,England,ENG,172123,62,Sophia Gardens,Cardiff,+01:00,51.484257,-3.189187
3,105794,8788,"South Africa tour of England, 2025",3rd ODI,ODI,2025-09-07 10:00:00,2025-09-07 18:00:00,Complete,England won by 342 runs,9.0,...,11,South Africa,RSA,172126,21,The Rose Bowl,Southampton,+01:00,50.924131,-1.322163
4,105788,8788,"South Africa tour of England, 2025",2nd ODI,ODI,2025-09-04 12:00:00,2025-09-04 20:00:00,Complete,South Africa won by 5 runs,11.0,...,9,England,ENG,172123,19,Lord's,London,+01:00,51.529488,-0.172926

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{matchid)/hscard"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

In [18]:
def fetch_and_process_scorecards(match_ids):
    """
    Fetches scorecard data for a list of match IDs and processes it into a DataFrame.
    """
    all_scorecard_data = []
    url_template = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{}/hscard"
    headers = {
        "x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e", # Replace with your actual API key
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    for match_id in match_ids:
        url = url_template.format(match_id)
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
            data = response.json()
            # Add match_id to the data for later reference
            data['matchId'] = match_id
            all_scorecard_data.append(data)
        except requests.exceptions.RequestException as e:
            print(f"Error fetching scorecard for match ID {match_id}: {e}")
            continue # Continue to the next match if there's an error

    # Process the collected data (this part might need refinement based on the actual API response structure)
    # For now, we'll just create a DataFrame from the list of dictionaries.
    # You might need to flatten or further process the nested structure depending on your needs.
    df_scorecards = pd.DataFrame(all_scorecard_data)

    return df_scorecards

# Fetch and process scorecards for the specified match IDs
df_scorecards = fetch_and_process_scorecards(matchID)

# Display the resulting DataFrame
display(df_scorecards)

,scoreCard,matchHeader,isMatchComplete,status,videos,responseLastUpdated,matchId
0,"[{'matchId': 130008, 'inningsId': 1, 'timeScor...","{'matchId': 130008, 'matchDescription': '1st M...",True,Afghanistan won by 94 runs,"[{'commId': 127613, 'matchId': 130008, 'inning...",1757748026,130008
1,"[{'matchId': 130019, 'inningsId': 1, 'timeScor...","{'matchId': 130019, 'matchDescription': '2nd M...",True,India won by 9 wkts,"[{'commId': 127693, 'matchId': 130019, 'inning...",1757748027,130019
2,"[{'matchId': 105802, 'inningsId': 1, 'timeScor...","{'matchId': 105802, 'matchDescription': '1st T...",True,South Africa won by 14 runs (DLS Method),[],1757748029,105802
3,"[{'matchId': 105794, 'inningsId': 1, 'timeScor...","{'matchId': 105794, 'matchDescription': '3rd O...",True,England won by 342 runs,[],1757748029,105794
4,"[{'matchId': 105788, 'inningsId': 1, 'timeScor...","{'matchId': 105788, 'matchDescription': '2nd O...",True,South Africa won by 5 runs,[],1757748028,105788

In [25]:
df_scorecards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   scoreCard            5 non-null      object
 1   matchHeader          5 non-null      object
 2   isMatchComplete      5 non-null      bool
 3   status               5 non-null      object
 4   videos               5 non-null      object
 5   responseLastUpdated  5 non-null      int64
 6   matchId              5 non-null      int64
dtypes: bool(1), int64(2), object(4)
memory usage: 377.0+ bytes

In [23]:
# scorecard uniq
# df_scorecards['scoreCard'].unique() # This will cause a TypeError because lists are unhashable

# Instead, let's inspect the first few entries in the 'scoreCard' column
print("First 5 entries in the 'scoreCard' column:")
for i, entry in enumerate(df_scorecards['scoreCard'].head()):
    print(f"Entry {i}: {entry}")
    if i >= 4: # Print only first 5 entries
        break

First 5 entries in the 'scoreCard' column:

In [30]:
# save this dataa to scoradard data in db
df_innings_data.to_sql('innings_stats', conn_crickbuzz, if_exists='replace', index=False)

# Verify by reading from the database
pd.read_sql('SELECT * FROM innings_stats', conn_crickbuzz)

,matchId,inningsId,teamId,teamName,playerType,playerId,playerName,runs,balls,fours,...,bat1Id,bat1Name,bat1Runs,bat1Balls,bat2Id,bat2Name,bat2Runs,bat2Balls,totalRuns,totalBalls
0,130008,1,96,Afghanistan,Batsman,14204.0,Sediqullah Atal,73.0,52.0,6.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
1,130008,1,96,Afghanistan,Batsman,13213.0,Gurbaz,8.0,5.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
2,130008,1,96,Afghanistan,Batsman,12173.0,Ibrahim Zadran,1.0,4.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
3,130008,1,96,Afghanistan,Batsman,3007.0,Nabi,33.0,26.0,3.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
4,130008,1,96,Afghanistan,Batsman,8030.0,Gulbadin,5.0,8.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,2258.0,Buttler,24.0,18.0,12258.0,Will Jacks,15.0,18.0,40.0,36.0
245,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11436.0,Brydon Carse,7.0,9.0,12258.0,Will Jacks,24.0,13.0,32.0,22.0
246,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,1.0,2.0,12258.0,Will Jacks,0.0,2.0,2.0,4.0
247,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,16.0,6.0,1742.0,Adil Rashid,2.0,4.0,23.0,10.0
248,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,10.0,6.0,10394.0,Saqib Mahmood,2.0,3.0,12.0,9.0

In [34]:
all_innings_data = []

# Iterate through each match's scorecard in the df_scorecards DataFrame
for index, row in df_scorecards.iterrows():
    match_id = row['matchId']
    scorecard_list = row['scoreCard']

    # Iterate through each innings within the scorecard
    for innings in scorecard_list:
        innings_id = innings.get('inningsId')
        batting_team_details = innings.get('batTeamDetails', {})
        bowling_team_details = innings.get('bowlTeamDetails', {})
        score_details = innings.get('scoreDetails', {})
        extras_data = innings.get('extrasData', {})
        wickets_data = innings.get('wicketsData', {})
        partnerships_data = innings.get('partnershipsData', {})


        # Extract batting data
        batsmen_data = batting_team_details.get('batsmenData', {})
        for bat_key, bat_details in batsmen_data.items():
            player_data = {
                'matchId': match_id,
                'inningsId': innings_id,
                'teamId': batting_team_details.get('batTeamId'),
                'teamName': batting_team_details.get('batTeamName'),
                'playerType': 'Batsman',
                'playerId': bat_details.get('batId'),
                'playerName': bat_details.get('batName'),
                'runs': bat_details.get('runs'),
                'balls': bat_details.get('balls'),
                'fours': bat_details.get('fours'),
                'sixes': bat_details.get('sixes'),
                'strikeRate': bat_details.get('strikeRate'),
                'outDesc': bat_details.get('outDesc'),
                'bowlerId': bat_details.get('bowlerId'),
                'fielderId1': bat_details.get('fielderId1'),
                'fielderId2': bat_details.get('fielderId2'),
                'fielderId3': bat_details.get('fielderId3')
                # Add other batting details as needed
            }
            all_innings_data.append(player_data)

        # Extract bowling data
        bowlers_data = bowling_team_details.get('bowlersData', {})
        for bowl_key, bowl_details in bowlers_data.items():
             player_data = {
                'matchId': match_id,
                'inningsId': innings_id,
                'teamId': bowling_team_details.get('bowlTeamId'),
                'teamName': bowling_team_details.get('bowlTeamName'),
                'playerType': 'Bowler',
                'playerId': bowl_details.get('bowlerId'),
                'playerName': bowl_details.get('bowlName'),
                'overs': bowl_details.get('overs'),
                'maidens': bowl_details.get('maidens'),
                'runs': bowl_details.get('runs'),
                'wickets': bowl_details.get('wickets'),
                'economy': bowl_details.get('economy'),
                # Add other bowling details as needed
            }
             all_innings_data.append(player_data)

        # Extract score details
        score_details_data = {
            'matchId': match_id,
            'inningsId': innings_id,
            'teamId': batting_team_details.get('batTeamId'),
            'teamName': batting_team_details.get('batTeamName'),
            'playerType': 'Innings Summary', # Indicate this row is for innings summary
            'overs': score_details.get('overs'),
            'runs': score_details.get('runs'),
            'wickets': score_details.get('wickets'),
            'runRate': score_details.get('runRate'),
            'isDeclared': score_details.get('isDeclared'),
            'isFollowOn': score_details.get('isFollowOn')
            # Add other score details as needed
        }
        all_innings_data.append(score_details_data)

        # Extract partnership data
        partnerships_data = innings.get('partnershipsData', {})
        for pat_key, pat_details in partnerships_data.items():
            partnership_data = {
                'matchId': match_id,
                'inningsId': innings_id,
                'teamId': batting_team_details.get('batTeamId'),
                'teamName': batting_team_details.get('batTeamName'),
                'playerType': 'Partnership', # Indicate this row is for partnership details
                'bat1Id': pat_details.get('bat1Id'),
                'bat1Name': pat_details.get('bat1Name'),
                'bat1Runs': pat_details.get('bat1Runs'),
                'bat1Balls': pat_details.get('bat1balls'),
                'bat2Id': pat_details.get('bat2Id'),
                'bat2Name': pat_details.get('bat2Name'),
                'bat2Runs': pat_details.get('bat2Runs'),
                'bat2Balls': pat_details.get('bat2balls'),
                'totalRuns': pat_details.get('totalRuns'),
                'totalBalls': pat_details.get('totalBalls')
                # Add other partnership details as needed
            }
            all_innings_data.append(partnership_data)


# Create a DataFrame from the extracted data
df_innings_data = pd.DataFrame(all_innings_data)

# Display the new DataFrame
display(df_innings_data.head())

,matchId,inningsId,teamId,teamName,playerType,playerId,playerName,runs,balls,fours,...,bat1Id,bat1Name,bat1Runs,bat1Balls,bat2Id,bat2Name,bat2Runs,bat2Balls,totalRuns,totalBalls
0,130008,1,96,Afghanistan,Batsman,14204.0,Sediqullah Atal,73.0,52.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130008,1,96,Afghanistan,Batsman,13213.0,Gurbaz,8.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,130008,1,96,Afghanistan,Batsman,12173.0,Ibrahim Zadran,1.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,130008,1,96,Afghanistan,Batsman,3007.0,Nabi,33.0,26.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130008,1,96,Afghanistan,Batsman,8030.0,Gulbadin,5.0,8.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_innings_data

,matchId,inningsId,teamId,teamName,playerType,playerId,playerName,runs,balls,fours,sixes,strikeRate,outDesc,bowlerId,fielderId1,fielderId2,fielderId3,overs,maidens,wickets,economy,runRate,isDeclared,isFollowOn,bat1Id,bat1Name,bat1Runs,bat1Balls,bat2Id,bat2Name,bat2Runs,bat2Balls,totalRuns,totalBalls
0,130008,1,96,Afghanistan,Batsman,14204.0,Sediqullah Atal,73.0,52.0,6.0,3.0,140.38,not out,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130008,1,96,Afghanistan,Batsman,13213.0,Gurbaz,8.0,5.0,0.0,1.0,160.00,c Nizakat Khan b Ayush Shukla,28220.0,9980.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,130008,1,96,Afghanistan,Batsman,12173.0,Ibrahim Zadran,1.0,4.0,0.0,0.0,25.00,c Zeeshan Ali b Ateeq Iqbal,29711.0,13552.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,130008,1,96,Afghanistan,Batsman,3007.0,Nabi,33.0,26.0,3.0,1.0,126.92,c Nizakat Khan b Kinchit Shah,9981.0,9980.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130008,1,96,Afghanistan,Batsman,8030.0,Gulbadin,5.0,8.0,0.0,0.0,62.50,c Yasim Murtaza b Kinchit Shah,9981.0,13554.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,105788,2,9,England,Partnership,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2258.0,Buttler,24.0,18.0,12258.0,Will Jacks,15.0,18.0,40.0,36.0
245,105788,2,9,England,Partnership,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11436.0,Brydon Carse,7.0,9.0,12258.0,Will Jacks,24.0,13.0,32.0,22.0
246,105788,2,9,England,Partnership,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,1.0,2.0,12258.0,Will Jacks,0.0,2.0,2.0,4.0
247,105788,2,9,England,Partnership,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,16.0,6.0,1742.0,Adil Rashid,2.0,4.0,23.0,10.0
248,105788,2,9,England,Partnership,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,10.0,6.0,10394.0,Saqib Mahmood,2.0,3.0,12.0,9.0

In [35]:
df_innings_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   matchId     249 non-null    int64
 1   inningsId   249 non-null    int64
 2   teamId      249 non-null    int64
 3   teamName    249 non-null    object
 4   playerType  249 non-null    object
 5   playerId    164 non-null    float64
 6   playerName  164 non-null    object
 7   runs        174 non-null    float64
 8   balls       110 non-null    float64
 9   fours       110 non-null    float64
 10  sixes       110 non-null    float64
 11  strikeRate  110 non-null    float64
 12  outDesc     110 non-null    object
 13  bowlerId    110 non-null    float64
 14  fielderId1  110 non-null    float64
 15  fielderId2  110 non-null    float64
 16  fielderId3  110 non-null    float64
 17  overs       64 non-null     float64
 18  maidens     54 non-null     float64
 19  wickets     64 non-null     float64
 20  economy     54 non-null     float64
 21  runRate     10 non-null     float64
 22  isDeclared  10 non-null     object
 23  isFollowOn  10 non-null     object
 24  bat1Id      75 non-null     float64
 25  bat1Name    75 non-null     object
 26  bat1Runs    75 non-null     float64
 27  bat1Balls   75 non-null     float64
 28  bat2Id      75 non-null     float64
 29  bat2Name    75 non-null     object
 30  bat2Runs    75 non-null     float64
 31  bat2Balls   75 non-null     float64
 32  totalRuns   75 non-null     float64
 33  totalBalls  75 non-null     float64
dtypes: float64(23), int64(3), object(8)
memory usage: 66.3+ KB

In [36]:
# save this dataa to scoradard data in db
df_innings_data.to_sql('innings_stats', conn_crickbuzz, if_exists='replace', index=False)

# Verify by reading from the database
pd.read_sql('SELECT * FROM innings_stats', conn_crickbuzz)

,matchId,inningsId,teamId,teamName,playerType,playerId,playerName,runs,balls,fours,...,bat1Id,bat1Name,bat1Runs,bat1Balls,bat2Id,bat2Name,bat2Runs,bat2Balls,totalRuns,totalBalls
0,130008,1,96,Afghanistan,Batsman,14204.0,Sediqullah Atal,73.0,52.0,6.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
1,130008,1,96,Afghanistan,Batsman,13213.0,Gurbaz,8.0,5.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
2,130008,1,96,Afghanistan,Batsman,12173.0,Ibrahim Zadran,1.0,4.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
3,130008,1,96,Afghanistan,Batsman,3007.0,Nabi,33.0,26.0,3.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
4,130008,1,96,Afghanistan,Batsman,8030.0,Gulbadin,5.0,8.0,0.0,...,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,2258.0,Buttler,24.0,18.0,12258.0,Will Jacks,15.0,18.0,40.0,36.0
245,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11436.0,Brydon Carse,7.0,9.0,12258.0,Will Jacks,24.0,13.0,32.0,22.0
246,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,1.0,2.0,12258.0,Will Jacks,0.0,2.0,2.0,4.0
247,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,16.0,6.0,1742.0,Adil Rashid,2.0,4.0,23.0,10.0
248,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,...,11540.0,Jofra Archer,10.0,6.0,10394.0,Saqib Mahmood,2.0,3.0,12.0,9.0

In [3]:
import sqlite3
# cooonect database crickbuzz.db
conn_crickbuzz = sqlite3.connect('crickbuzz.db')

In [26]:
# show crickbuzz.db tables
query = "SELECT name FROM sqlite_master WHERE type='table';"
cursor = conn_crickbuzz.cursor()
cursor.execute(query)
tables = cursor.fetchall()
for table in tables:
    print(table[0])

match_list
players
venue_stats
international_series
innings_stats
batting_stats
bowling_stats

In [28]:
# batting_stats table view
query = "SELECT * FROM innings_stats"
batting_stats = pd.read_sql(query, conn_crickbuzz)
batting_stats

,matchId,inningsId,teamId,teamName,playerType,playerId,playerName,runs,balls,fours,sixes,strikeRate,outDesc,bowlerId,fielderId1,fielderId2,fielderId3,overs,maidens,wickets,economy,runRate,isDeclared,isFollowOn,bat1Id,bat1Name,bat1Runs,bat1Balls,bat2Id,bat2Name,bat2Runs,bat2Balls,totalRuns,totalBalls
0,130008,1,96,Afghanistan,Batsman,14204.0,Sediqullah Atal,73.0,52.0,6.0,3.0,140.38,not out,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
1,130008,1,96,Afghanistan,Batsman,13213.0,Gurbaz,8.0,5.0,0.0,1.0,160.00,c Nizakat Khan b Ayush Shukla,28220.0,9980.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
2,130008,1,96,Afghanistan,Batsman,12173.0,Ibrahim Zadran,1.0,4.0,0.0,0.0,25.00,c Zeeshan Ali b Ateeq Iqbal,29711.0,13552.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
3,130008,1,96,Afghanistan,Batsman,3007.0,Nabi,33.0,26.0,3.0,1.0,126.92,c Nizakat Khan b Kinchit Shah,9981.0,9980.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
4,130008,1,96,Afghanistan,Batsman,8030.0,Gulbadin,5.0,8.0,0.0,0.0,62.50,c Yasim Murtaza b Kinchit Shah,9981.0,13554.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2258.0,Buttler,24.0,18.0,12258.0,Will Jacks,15.0,18.0,40.0,36.0
245,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11436.0,Brydon Carse,7.0,9.0,12258.0,Will Jacks,24.0,13.0,32.0,22.0
246,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,1.0,2.0,12258.0,Will Jacks,0.0,2.0,2.0,4.0
247,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,16.0,6.0,1742.0,Adil Rashid,2.0,4.0,23.0,10.0
248,105788,2,9,England,Partnership,NaN,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11540.0,Jofra Archer,10.0,6.0,10394.0,Saqib Mahmood,2.0,3.0,12.0,9.0

In [5]:
# players table
query = "SELECT * FROM players"
players = pd.read_sql(query, conn_crickbuzz)
players

,id,name,fullName,nickName,captain,role,keeper,substitute,teamId,battingStyle,...,teamName,faceImageId,squad_type,match_id,team_id,isSupportStaff,playingXIChange,isOverseas,inMatchChange,splSubstitute
0,18987,Muhammad Waseem,Muhammad Waseem,Muhammad Waseem,1.0,Batsman,0.0,0.0,7,RIGHT,...,UAE,244736,Playing XI,130019,7,NaN,None,NaN,None,NaN
1,14227,Alishan Sharafu,Alishan Sharafu,Alishan Sharafu,0.0,Batting Allrounder,0.0,0.0,7,RIGHT,...,UAE,244727,Playing XI,130019,7,NaN,None,NaN,None,NaN
2,1452926,Muhammad Zohaib,Muhammad Zohaib,Muhammad Zohaib,0.0,Batsman,0.0,0.0,7,LEFT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
3,52666,Rahul Chopra,Rahul Chopra,Rahul Chopra,0.0,WK-Batsman,1.0,0.0,7,RIGHT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
4,15793,Asif Khan,Asif Khan,Asif Khan,0.0,Batsman,0.0,0.0,7,RIGHT,...,UAE,182026,Playing XI,130019,7,NaN,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,23956,Jannillea Glasgow,Jannillea Glasgow,Jannillea Glasgow,0.0,Bowling Allrounder,0.0,0.0,1139,LEFT,...,None,227429,Playing XI,122082,1139,NaN,None,NaN,None,NaN
1795,1449536,Abigail Bryce,Abigail Bryce,Abigail Bryce,0.0,Batsman,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1796,28731,Keila Elliott,Keila Elliott,Keila Elliott,0.0,Bowling Allrounder,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1797,1430401,Nerissa Crafton,Nerissa Crafton,Nerissa Crafton,0.0,Batsman,0.0,1.0,1139,LEFT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN
1798,15702,Shawnisha Hector,Shawnisha Hector,Shawnisha Hector,0.0,Bowler,0.0,1.0,1139,RIGHT,...,None,182026,Bench,122082,1139,NaN,None,NaN,None,NaN

In [ ]:
# whole player fetch players id in such waay each team battar,bowler and all rounder must be but only 60 player id fetch randomly

In [6]:
# Filter players by role
batters = players[players['role'].str.contains('Batsman|WK-Batsman', na=False)]
bowlers = players[players['role'].str.contains('Bowler', na=False)]
all_rounders = players[players['role'].str.contains('Allrounder', na=False)]

# Calculate the number of players to sample from each category per team
# This is a simple approach; more complex logic might be needed for perfect distribution
total_players = 60
num_teams = players['teamId'].nunique()

# Determine how many players to aim for from each role per team
# Distribute the total sample size roughly equally among roles and teams
players_per_role_per_team = total_players // (3 * num_teams) # 3 roles: Batsman, Bowler, Allrounder
remaining_players = total_players % (3 * num_teams)

sampled_player_ids = []

# Sample from each team and role
for team_id in players['teamId'].unique():
    team_batters = batters[batters['teamId'] == team_id]
    team_bowlers = bowlers[bowlers['teamId'] == team_id]
    team_all_rounders = all_rounders[all_rounders['teamId'] == team_id]

    # Sample players from each category, ensuring we don't sample more than available
    sampled_batters = team_batters.sample(min(len(team_batters), players_per_role_per_team), random_state=42)
    sampled_bowlers = team_bowlers.sample(min(len(team_bowlers), players_per_role_per_team), random_state=42)
    sampled_all_rounders = team_all_rounders.sample(min(len(team_all_rounders), players_per_role_per_team), random_state=42)

    sampled_player_ids.extend(sampled_batters['id'].tolist())
    sampled_player_ids.extend(sampled_bowlers['id'].tolist())
    sampled_player_ids.extend(sampled_all_rounders['id'].tolist())

# If we still need more players to reach 60, sample randomly from the remaining players
if len(sampled_player_ids) < total_players:
    remaining_players_df = players[~players['id'].isin(sampled_player_ids)]
    additional_sample_size = total_players - len(sampled_player_ids)
    additional_players = remaining_players_df.sample(min(len(remaining_players_df), additional_sample_size), random_state=42)
    sampled_player_ids.extend(additional_players['id'].tolist())

# Ensure the final list has unique player IDs and is limited to 60
sampled_player_ids = list(set(sampled_player_ids))[:total_players]

print(f"Sampled {len(sampled_player_ids)} player IDs:")
print(sampled_player_ids)

Sampled 59 player IDs:
[33281, 1462533, 13958, 11141, 19592, 1461641, 43013, 9975, 10636, 15877, 33806, 33295, 1460498, 47763, 43157, 23831, 1447449, 50458, 54175, 13088, 13089, 21536, 1456809, 19756, 7854, 51886, 11442, 13748, 52666, 15804, 49725, 10940, 1460541, 3009, 14536, 1450314, 9804, 1462221, 18509, 37840, 41424, 13907, 1460692, 50010, 55004, 11485, 1460575, 48997, 1456613, 45159, 1005, 1460717, 9585, 1425265, 13810, 10101, 49527, 32252, 12926]

In [7]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/33281/bowling"

headers = {
	"x-rapidapi-key": "489e95dca2msh710eaa155c22b18p103e11jsn0192b4f5db8e",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20'], 'values': [{'values': ['Matches', '0', '0', '36']}, {'values': ['Innings', '0', '0', '3']}, {'values': ['Balls', '0', '0', '18']}, {'values': ['Runs', '0', '0', '25']}, {'values': ['Maidens', '0', '0', '0']}, {'values': ['Wickets', '0', '0', '0']}, {'values': ['Avg', '0.0', '0.0', '0.0']}, {'values': ['Eco', '0', '0', '8.33']}, {'values': ['SR', '0.0', '0.0', '0.0']}, {'values': ['BBI', '-/-', '-/-', '0/4']}, {'values': ['BBM', '-/-', '-/-', '0/4']}, {'values': ['4w', '0', '0', '0']}, {'values': ['5w', '0', '0', '0']}, {'values': ['10w', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Hinase Goto Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/33281/hinase-goto'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 10702, 'seriesName': 'ICC Womens T20 World Cup East Asia Pacific Qualifier 2025'}]}

In [8]:
# understanding patten
data = response.json()
print(data.keys())

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [9]:
print(data.keys())
if 'values' in data:
    print("\nStructure of 'values':")
    print(data['values'])
if 'headers' in data:
    print("\nStructure of 'headers':")
    print(data['headers'])

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

Structure of 'values':
[{'values': ['Matches', '0', '0', '36']}, {'values': ['Innings', '0', '0', '3']}, {'values': ['Balls', '0', '0', '18']}, {'values': ['Runs', '0', '0', '25']}, {'values': ['Maidens', '0', '0', '0']}, {'values': ['Wickets', '0', '0', '0']}, {'values': ['Avg', '0.0', '0.0', '0.0']}, {'values': ['Eco', '0', '0', '8.33']}, {'values': ['SR', '0.0', '0.0', '0.0']}, {'values': ['BBI', '-/-', '-/-', '0/4']}, {'values': ['BBM', '-/-', '-/-', '0/4']}, {'values': ['4w', '0', '0', '0']}, {'values': ['5w', '0', '0', '0']}, {'values': ['10w', '0', '0', '0']}]

Structure of 'headers':
['ROWHEADER', 'Test', 'ODI', 'T20']

In [ ]:
# extract details

In [11]:
bowling_data_values = data.get('values', [])
bowling_headers = data.get('headers', [])

# Create a dictionary to hold the extracted bowling data
extracted_bowling_data = {}

# The first value in each entry of 'values' is the metric name (e.g., 'Matches', 'Innings')
# The subsequent values correspond to the formats in 'headers' (skipping the first header which is 'ROWHEADER')
for entry in bowling_data_values:
    metric_name = entry['values'][0]
    metric_values = entry['values'][1:] # Get values for each format

    # Ensure the number of values matches the number of headers (excluding 'ROWHEADER')
    if len(metric_values) == len(bowling_headers) - 1:
        for i, format_name in enumerate(bowling_headers[1:]): # Iterate through format headers
            # Create a key like 'Matches - Test', 'Wickets - ODI', etc.
            column_name = f"{metric_name} - {format_name}"
            # Store the value, handling potential errors if the value is not a number
            try:
                extracted_bowling_data[column_name] = [float(metric_values[i])]
            except (ValueError, TypeError):
                extracted_bowling_data[column_name] = [metric_values[i]] # Keep as is if not convertible to float
    else:
        print(f"Warning: Mismatch between number of values and headers for metric '{metric_name}'. Skipping.")


df_bowling_stats = pd.DataFrame(extracted_bowling_data)
display(df_bowling_stats)

,Matches - Test,Matches - ODI,Matches - T20,Innings - Test,Innings - ODI,Innings - T20,Balls - Test,Balls - ODI,Balls - T20,Runs - Test,...,BBM - T20,4w - Test,4w - ODI,4w - T20,5w - Test,5w - ODI,5w - T20,10w - Test,10w - ODI,10w - T20
0,0.0,0.0,36.0,0.0,0.0,3.0,0.0,0.0,18.0,0.0,...,0/4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# Define the player_id (from the previous API call URL)
player_id = 33281

# Add the player ID to the DataFrame
df_bowling_stats['player_id'] = player_id
display(df_bowling_stats.head())

,Matches - Test,Matches - ODI,Matches - T20,Innings - Test,Innings - ODI,Innings - T20,Balls - Test,Balls - ODI,Balls - T20,Runs - Test,...,4w - Test,4w - ODI,4w - T20,5w - Test,5w - ODI,5w - T20,10w - Test,10w - ODI,10w - T20,player_id
0,0.0,0.0,36.0,0.0,0.0,3.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33281

In [15]:
# Iterate through sampled player IDs
for player_id in sampled_player_ids:
    # Find the player's role(s) in the players DataFrame
    player_info = players[players['id'] == player_id].iloc[0]
    player_role = player_info['role']

    # Fetch batting data if the player is a Batsman or WK-Batsman
    if 'Batsman' in player_role or 'WK-Batsman' in player_role:
        url_batting = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"
        headers = {
            "x-rapidapi-key": "af412425bamsh0d5d43bcb05971ap11b4ccjsn1e3f99f58a33", # Replace with your actual API key
            "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
        }
        try:
            response_batting = requests.get(url_batting, headers=headers)
            response_batting.raise_for_status()
            batting_data = response_batting.json()

            # Extract and process batting data
            batting_data_values = batting_data.get('values', [])
            batting_headers = batting_data.get('headers', [])
            extracted_batting_data = {}

            for entry in batting_data_values:
                metric_name = entry['values'][0]
                metric_values = entry['values'][1:]
                if len(metric_values) == len(batting_headers) - 1:
                    for i, format_name in enumerate(batting_headers[1:]):
                        column_name = f"{metric_name} - {format_name}"
                        try:
                            extracted_batting_data[column_name] = float(metric_values[i])
                        except (ValueError, TypeError):
                            extracted_batting_data[column_name] = metric_values[i]
                else:
                    print(f"Warning: Mismatch in batting data for player {player_id}, metric '{metric_name}'.")

            extracted_batting_data['player_id'] = player_id
            all_batting_data.append(extracted_batting_data)

        except requests.exceptions.RequestException as e:
            print(f"Error fetching batting data for player {player_id}: {e}")

    # Fetch bowling data if the player is a Bowler or Allrounder
    if 'Bowler' in player_role or 'Allrounder' in player_role:
        url_bowling = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/bowling"
        headers = {
            "x-rapidapi-key": "af412425bamsh0d5d43bcb05971ap11b4ccjsn1e3f99f58a33", # Replace with your actual API key
            "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
        }
        try:
            response_bowling = requests.get(url_bowling, headers=headers)
            response_bowling.raise_for_status()
            bowling_data = response_bowling.json()

            # Extract and process bowling data
            bowling_data_values = bowling_data.get('values', [])
            bowling_headers = bowling_data.get('headers', [])
            extracted_bowling_data = {}

            for entry in bowling_data_values:
                metric_name = entry['values'][0]
                metric_values = entry['values'][1:]
                if len(metric_values) == len(bowling_headers) - 1:
                    for i, format_name in enumerate(bowling_headers[1:]):
                        column_name = f"{metric_name} - {format_name}"
                        try:
                            extracted_bowling_data[column_name] = float(metric_values[i])
                        except (ValueError, TypeError):
                            extracted_bowling_data[column_name] = metric_values[i]
                else:
                     print(f"Warning: Mismatch in bowling data for player {player_id}, metric '{metric_name}'.")


            extracted_bowling_data['player_id'] = player_id
            all_bowling_data.append(extracted_bowling_data)

        except requests.exceptions.RequestException as e:
            print(f"Error fetching bowling data for player {player_id}: {e}")


# Create DataFrames from the collected data
df_all_batting_stats = pd.DataFrame(all_batting_data)
df_all_bowling_stats = pd.DataFrame(all_bowling_data)

# Display the resulting DataFrames
print("\nBatting Stats DataFrame:")
display(df_all_batting_stats.head())

print("\nBowling Stats DataFrame:")
display(df_all_bowling_stats.head())

Batting Stats DataFrame:

,Matches - Test,Matches - ODI,Matches - T20,Innings - Test,Innings - ODI,Innings - T20,Runs - Test,Runs - ODI,Runs - T20,Balls - Test,...,SR - IPL,Not Out - IPL,Fours - IPL,Sixes - IPL,Ducks - IPL,50s - IPL,100s - IPL,200s - IPL,300s - IPL,400s - IPL
0,0.0,0.0,36.0,0.0,0.0,30.0,0.0,0.0,231.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,26.0,1.0,0.0,25.0,1.0,0.0,582.0,17.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,1.0,0.0,6.0,1.0,0.0,63.0,22.0,0.0,164.0,...,154.31,2.0,76.0,68.0,1.0,9.0,1.0,0.0,0.0,0.0
4,0.0,21.0,53.0,0.0,19.0,53.0,0.0,225.0,917.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Bowling Stats DataFrame:

,Matches - Test,Matches - ODI,Matches - T20,Matches - IPL,Innings - Test,Innings - ODI,Innings - T20,Innings - IPL,Balls - Test,Balls - ODI,...,4w - IPL,5w - Test,5w - ODI,5w - T20,5w - IPL,10w - Test,10w - ODI,10w - T20,10w - IPL,player_id
0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13958
1,1.0,17.0,11.0,0.0,2.0,16.0,11.0,0.0,216.0,644.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,19592
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1461641
3,0.0,0.0,21.0,NaN,0.0,0.0,19.0,NaN,0.0,0.0,...,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,43013
4,0.0,19.0,93.0,0.0,0.0,19.0,84.0,0.0,0.0,734.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9975

In [14]:
# Initialize empty lists to store batting and bowling data for all players
all_batting_data = []
all_bowling_data = []

In [16]:
all_batting_data

[{'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 36.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 30.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 231.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 423.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 44.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 8.56,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 54.61,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 3.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 13.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 3.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 33281},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 0.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 0.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 0.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 0.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 0.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 0.0,
  'Average - IPL': 0.0,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 0.0,
  'SR - IPL': 0.0,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 0.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 0.0,
  'Fours - IPL': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Sixes - IPL': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 1462533},
 {'Matches - Test': 0.0,
  'Matches - ODI': 26.0,
  'Matches - T20': 1.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 25.0,
  'Innings - T20': 1.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 582.0,
  'Runs - T20': 17.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 991.0,
  'Balls - T20': 15.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 57.0,
  'Highest - T20': 17.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,
  'Average - ODI': 23.28,
  'Average - T20': 0.0,
  'Average - IPL': 0.0,
  'SR - Test': 0.0,
  'SR - ODI': 58.73,
  'SR - T20': 113.34,
  'SR - IPL': 0.0,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 1.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 64.0,
  'Fours - T20': 1.0,
  'Fours - IPL': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 2.0,
  'Sixes - T20': 1.0,
  'Sixes - IPL': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 1.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 3.0,
  '50s - T20': 0.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 11141},
 {'Matches - Test': 3.0,
  'Matches - ODI': 1.0,
  'Matches - T20': 0.0,
  'Matches - IPL': 42.0,
  'Innings - Test': 6.0,
  'Innings - ODI': 1.0,
  'Innings - T20': 0.0,
  'Innings - IPL': 38.0,
  'Runs - Test': 63.0,
  'Runs - ODI': 22.0,
  'Runs - T20': 0.0,
  'Runs - IPL': 1111.0,
  'Balls - Test': 164.0,
  'Balls - ODI': 16.0,
  'Balls - T20': 0.0,
  'Balls - IPL': 720.0,
  'Highest - Test': 32.0,
  'Highest - ODI': 22.0,
  'Highest - T20': 0.0,
  'Highest - IPL': 112.0,
  'Average - Test': 10.5,
  'Average - ODI': 22.0,
  'Average - T20': 0.0,
  'Average - IPL': 30.86,
  'SR - Test': 38.42,
  'SR - ODI': 137.5,
  'SR - T20': 0.0,
  'SR - IPL': 154.31,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 0.0,
  'Not Out - IPL': 2.0,
  'Fours - Test': 9.0,
  'Fours - ODI': 3.0,
  'Fours - T20': 0.0,
  'Fours - IPL': 76.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 1.0,
  'Sixes - T20': 0.0,
  'Sixes - IPL': 68.0,
  'Ducks - Test': 2.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 1.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '50s - IPL': 9.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 1.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 10636},
 {'Matches - Test': 0.0,
  'Matches - ODI': 21.0,
  'Matches - T20': 53.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 19.0,
  'Innings - T20': 53.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 225.0,
  'Runs - T20': 917.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 342.0,
  'Balls - T20': 744.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 45.0,
  'Highest - T20': 86.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,
  'Average - ODI': 13.24,
  'Average - T20': 18.34,
  'Average - IPL': 0.0,
  'SR - Test': 0.0,
  'SR - ODI': 65.79,
  'SR - T20': 123.26,
  'SR - IPL': 0.0,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 2.0,
  'Not Out - T20': 3.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 24.0,
  'Fours - T20': 100.0,
  'Fours - IPL': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 3.0,
  'Sixes - T20': 32.0,
  'Sixes - IPL': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 4.0,
  'Ducks - T20': 4.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 5.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 15877},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 45.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 9.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 15.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 48.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 5.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 2.14,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 31.25,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 2.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 5.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 33806},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 50.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 52.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 629.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 893.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 64.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 14.98,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 70.44,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 10.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 51.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 3.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 6.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 2.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 33295},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 64.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 56.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 572.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 858.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 53.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 13.0,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 66.67,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 12.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 48.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 8.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 2.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 23831},
 {'Matches - Test': 2.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 2.0,
  'Matches - IPL': 74.0,
  'Innings - Test': 3.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 2.0,
  'Innings - IPL': 74.0,
  'Runs - Test': 90.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 38.0,
  'Runs - IPL': 1806.0,
  'Balls - Test': 197.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 38.0,
  'Balls - IPL': 1430.0,
  'Highest - Test': 65.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 29.0,
  'Highest - IPL': 101.0,
  'Average - Test': 30.0,
  'Average - ODI': 0.0,
  'Average - T20': 19.0,
  'Average - IPL': 25.44,
  'SR - Test': 45.69,
  'SR - ODI': 0.0,
  'SR - T20': 100.0,
  'SR - IPL': 126.3,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 0.0,
  'Not Out - IPL': 3.0,
  'Fours - Test': 12.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 2.0,
  'Fours - IPL': 190.0,
  'Sixes - Test': 1.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 1.0,
  'Sixes - IPL': 56.0,
  'Ducks - Test': 1.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 6.0,
  '50s - Test': 1.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '50s - IPL': 11.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 1.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 13088},
 {'Matches - Test': 2.0,
  'Matches - ODI': 6.0,
  'Matches - T20': 10.0,
  'Matches - IPL': 1.0,
  'Innings - Test': 3.0,
  'Innings - ODI': 6.0,
  'Innings - T20': 10.0,
  'Innings - IPL': 1.0,
  'Runs - Test': 14.0,
  'Runs - ODI': 467.0,
  'Runs - T20': 151.0,
  'Runs - IPL': 14.0,
  'Balls - Test': 55.0,
  'Balls - ODI': 453.0,
  'Balls - T20': 123.0,
  'Balls - IPL': 12.0,
  'Highest - Test': 13.0,
  'Highest - ODI': 150.0,
  'Highest - T20': 51.0,
  'Highest - IPL': 14.0,
  'Average - Test': 4.67,
  'Average - ODI': 77.83,
  'Average - T20': 16.78,
  'Average - IPL': 14.0,
  'SR - Test': 25.46,
  'SR - ODI': 103.1,
  'SR - T20': 122.77,
  'SR - IPL': 116.67,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 1.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 1.0,
  'Fours - ODI': 44.0,
  'Fours - T20': 13.0,
  'Fours - IPL': 1.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 12.0,
  'Sixes - T20': 6.0,
  'Sixes - IPL': 1.0,
  'Ducks - Test': 1.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 4.0,
  '50s - T20': 1.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 1.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 13089},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 0.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 0.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 0.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 0.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 0.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 0.0,
  'Average - IPL': 0.0,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 0.0,
  'SR - IPL': 0.0,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 0.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 0.0,
  'Fours - IPL': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Sixes - IPL': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 0.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 21536},
 {'Matches - Test': 0.0,
  'Matches - ODI': 16.0,
  'Matches - T20': 30.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 16.0,
  'Innings - T20': 26.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 403.0,
  'Runs - T20': 603.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 525.0,
  'Balls - T20': 511.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 101.0,
  'Highest - T20': 80.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,
  'Average - ODI': 25.19,
  'Average - T20': 30.15,
  'Average - IPL': 0.0,
  'SR - Test': 0.0,
  'SR - ODI': 76.77,
  'SR - T20': 118.01,
  'SR - IPL': 0.0,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 6.0,
  'Not Out - IPL': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 34.0,
  'Fours - T20': 48.0,
  'Fours - IPL': 0.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 10.0,
  'Sixes - T20': 21.0,
  'Sixes - IPL': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 2.0,
  'Ducks - T20': 1.0,
  'Ducks - IPL': 0.0,
  '50s - Test': 0.0,
  '50s - ODI': 2.0,
  '50s - T20': 4.0,
  '50s - IPL': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 1.0,
  '100s - T20': 0.0,
  '100s - IPL': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '200s - IPL': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '300s - IPL': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  '400s - IPL': 0.0,
  'player_id': 52666},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 76.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 48.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 226.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 316.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 25.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 7.79,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 71.52,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 19.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 17.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 11.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 14536},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 12.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 6.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 35.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 60.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 11.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 5.83,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 58.34,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 0.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 3.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 1.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 0.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 1450314},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 31.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 38.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 489.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 556.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 88.0,
  'Average - Test': 0.0,
  'Average - ODI': 0.0,
  'Average - T20': 14.38,
  'SR - Test': 0.0,
  'SR - ODI': 0.0,
  'SR - T20': 87.95,
  'Not Out - Test': 0.0,
  'Not Out - ODI': 0.0,
  'Not Out - T20': 4.0,
  'Fours - Test': 0.0,
  'Fours - ODI': 0.0,
  'Fours - T20': 46.0,
  'Sixes - Test': 0.0,
  'Sixes - ODI': 0.0,
  'Sixes - T20': 0.0,
  'Ducks - Test': 0.0,
  'Ducks - ODI': 0.0,
  'Ducks - T20': 9.0,
  '50s - Test': 0.0,
  '50s - ODI': 0.0,
  '50s - T20': 1.0,
  '100s - Test': 0.0,
  '100s - ODI': 0.0,
  '100s - T20': 0.0,
  '200s - Test': 0.0,
  '200s - ODI': 0.0,
  '200s - T20': 0.0,
  '300s - Test': 0.0,
  '300s - ODI': 0.0,
  '300s - T20': 0.0,
  '400s - Test': 0.0,
  '400s - ODI': 0.0,
  '400s - T20': 0.0,
  'player_id': 37840},
 {'Matches - Test': 0.0,
  'Matches - ODI': 0.0,
  'Matches - T20': 0.0,
  'Matches - IPL': 0.0,
  'Innings - Test': 0.0,
  'Innings - ODI': 0.0,
  'Innings - T20': 0.0,
  'Innings - IPL': 0.0,
  'Runs - Test': 0.0,
  'Runs - ODI': 0.0,
  'Runs - T20': 0.0,
  'Runs - IPL': 0.0,
  'Balls - Test': 0.0,
  'Balls - ODI': 0.0,
  'Balls - T20': 0.0,
  'Balls - IPL': 0.0,
  'Highest - Test': 0.0,
  'Highest - ODI': 0.0,
  'Highest - T20': 0.0,
  'Highest - IPL': 0.0,
  'Average - Test': 0.0,

In [17]:
# all batting and bowling data extract and make dataframe from each
battiner_carrear = pd.DataFrame(all_batting_data)
bowler_carrear = pd.DataFrame(all_bowling_data)

In [21]:
# set full column view
pd.set_option('display.max_columns', None)

In [25]:
battiner_carrear.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 65 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Matches - Test  18 non-null     float64
 1   Matches - ODI   18 non-null     float64
 2   Matches - T20   18 non-null     float64
 3   Innings - Test  18 non-null     float64
 4   Innings - ODI   18 non-null     float64
 5   Innings - T20   18 non-null     float64
 6   Runs - Test     18 non-null     float64
 7   Runs - ODI      18 non-null     float64
 8   Runs - T20      18 non-null     float64
 9   Balls - Test    18 non-null     float64
 10  Balls - ODI     18 non-null     float64
 11  Balls - T20     18 non-null     float64
 12  Highest - Test  18 non-null     float64
 13  Highest - ODI   18 non-null     float64
 14  Highest - T20   18 non-null     float64
 15  Average - Test  18 non-null     float64
 16  Average - ODI   18 non-null     float64
 17  Average - T20   18 non-null     float64
 18  SR - Test       18 non-null     float64
 19  SR - ODI        18 non-null     float64
 20  SR - T20        18 non-null     float64
 21  Not Out - Test  18 non-null     float64
 22  Not Out - ODI   18 non-null     float64
 23  Not Out - T20   18 non-null     float64
 24  Fours - Test    18 non-null     float64
 25  Fours - ODI     18 non-null     float64
 26  Fours - T20     18 non-null     float64
 27  Sixes - Test    18 non-null     float64
 28  Sixes - ODI     18 non-null     float64
 29  Sixes - T20     18 non-null     float64
 30  Ducks - Test    18 non-null     float64
 31  Ducks - ODI     18 non-null     float64
 32  Ducks - T20     18 non-null     float64
 33  50s - Test      18 non-null     float64
 34  50s - ODI       18 non-null     float64
 35  50s - T20       18 non-null     float64
 36  100s - Test     18 non-null     float64
 37  100s - ODI      18 non-null     float64
 38  100s - T20      18 non-null     float64
 39  200s - Test     18 non-null     float64
 40  200s - ODI      18 non-null     float64
 41  200s - T20      18 non-null     float64
 42  300s - Test     18 non-null     float64
 43  300s - ODI      18 non-null     float64
 44  300s - T20      18 non-null     float64
 45  400s - Test     18 non-null     float64
 46  400s - ODI      18 non-null     float64
 47  400s - T20      18 non-null     float64
 48  player_id       18 non-null     int64
 49  Matches - IPL   10 non-null     float64
 50  Innings - IPL   10 non-null     float64
 51  Runs - IPL      10 non-null     float64
 52  Balls - IPL     10 non-null     float64
 53  Highest - IPL   10 non-null     float64
 54  Average - IPL   10 non-null     float64
 55  SR - IPL        10 non-null     float64
 56  Not Out - IPL   10 non-null     float64
 57  Fours - IPL     10 non-null     float64
 58  Sixes - IPL     10 non-null     float64
 59  Ducks - IPL     10 non-null     float64
 60  50s - IPL       10 non-null     float64
 61  100s - IPL      10 non-null     float64
 62  200s - IPL      10 non-null     float64
 63  300s - IPL      10 non-null     float64
 64  400s - IPL      10 non-null     float64
dtypes: float64(64), int64(1)
memory usage: 9.3 KB

In [24]:
bowler_carrear.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 57 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Matches - Test  38 non-null     float64
 1   Matches - ODI   38 non-null     float64
 2   Matches - T20   38 non-null     float64
 3   Matches - IPL   27 non-null     float64
 4   Innings - Test  38 non-null     float64
 5   Innings - ODI   38 non-null     float64
 6   Innings - T20   38 non-null     float64
 7   Innings - IPL   27 non-null     float64
 8   Balls - Test    38 non-null     float64
 9   Balls - ODI     38 non-null     float64
 10  Balls - T20     38 non-null     float64
 11  Balls - IPL     27 non-null     float64
 12  Runs - Test     38 non-null     float64
 13  Runs - ODI      38 non-null     float64
 14  Runs - T20      38 non-null     float64
 15  Runs - IPL      27 non-null     float64
 16  Maidens - Test  38 non-null     float64
 17  Maidens - ODI   38 non-null     float64
 18  Maidens - T20   38 non-null     float64
 19  Maidens - IPL   27 non-null     float64
 20  Wickets - Test  38 non-null     float64
 21  Wickets - ODI   38 non-null     float64
 22  Wickets - T20   38 non-null     float64
 23  Wickets - IPL   27 non-null     float64
 24  Avg - Test      38 non-null     float64
 25  Avg - ODI       38 non-null     float64
 26  Avg - T20       38 non-null     float64
 27  Avg - IPL       27 non-null     float64
 28  Eco - Test      38 non-null     float64
 29  Eco - ODI       38 non-null     float64
 30  Eco - T20       38 non-null     float64
 31  Eco - IPL       27 non-null     float64
 32  SR - Test       38 non-null     float64
 33  SR - ODI        38 non-null     float64
 34  SR - T20        38 non-null     float64
 35  SR - IPL        27 non-null     float64
 36  BBI - Test      38 non-null     object
 37  BBI - ODI       38 non-null     object
 38  BBI - T20       38 non-null     object
 39  BBI - IPL       27 non-null     object
 40  BBM - Test      38 non-null     object
 41  BBM - ODI       38 non-null     object
 42  BBM - T20       38 non-null     object
 43  BBM - IPL       27 non-null     object
 44  4w - Test       38 non-null     float64
 45  4w - ODI        38 non-null     float64
 46  4w - T20        38 non-null     float64
 47  4w - IPL        27 non-null     float64
 48  5w - Test       38 non-null     float64
 49  5w - ODI        38 non-null     float64
 50  5w - T20        38 non-null     float64
 51  5w - IPL        27 non-null     float64
 52  10w - Test      38 non-null     float64
 53  10w - ODI       38 non-null     float64
 54  10w - T20       38 non-null     float64
 55  10w - IPL       27 non-null     float64
 56  player_id       38 non-null     int64
dtypes: float64(48), int64(1), object(8)
memory usage: 17.1+ KB

In [23]:
# add both data in db
battiner_carrear.to_sql('batting_stats', conn_crickbuzz, if_exists='replace', index=False)
bowler_carrear.to_sql('bowling_stats', conn_crickbuzz, if_exists='replace', index=False)

38